// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#include "mongo/base/error_codes.h"
#include "mongo/base/status_with.h"
#include "mongo/bson/bsonobjbuilder.h"
#include "mongo/db/auth/action_type.h"
#include "mongo/db/auth/authorization_session.h"
#include "mongo/db/auth/resource_pattern.h"
#include "mongo/db/cancelable_operation_context.h"
#include "mongo/db/client.h"
#include "mongo/db/commands.h"
#include "mongo/db/database_name.h"
#include "mongo/db/dbdirectclient.h"
#include "mongo/db/global_catalog/ddl/commit_chunk_migration_gen.h"
#include "mongo/db/global_catalog/ddl/sharding_catalog_manager.h"
#include "mongo/db/global_catalog/type_chunk.h"
#include "mongo/db/namespace_string.h"
#include "mongo/db/operation_context.h"
#include "mongo/db/repl/intent_guard.h"
#include "mongo/db/repl/read_concern_args.h"
#include "mongo/db/repl/read_concern_level.h"
#include "mongo/db/repl/replication_coordinator.h"
#include "mongo/db/replication_state_transition_lock_guard.h"
#include "mongo/db/server_options.h"
#include "mongo/db/service_context.h"
#include "mongo/db/sharding_environment/grid.h"
#include "mongo/db/topology/cluster_role.h"
#include "mongo/db/versioning_protocol/chunk_version.h"
#include "mongo/rpc/op_msg.h"
#include "mongo/util/assert_util.h"
#include "mongo/util/cancellation.h"

#include <memory>
#include <string>

#include <boost/move/utility_core.hpp>

#define MONGO_LOGV2_DEFAULT_COMPONENT ::mongo::logv2::LogComponent::kSharding

namespace mongo {
namespace {

/**
 * This command takes the chunk being migrated ("migratedChunk") and generates a new version for it
 * that is written along with its new shard location ("toShard") to the chunks collection.
 *
 * The new chunk version is generated by querying the highest chunk version of the collection, and
 * then incrementing that major value for migrated chunks and setting the minor to
 * 0 for the migrated chunk. A global exclusive lock is held for the
 * duration of generating the new chunk version and writing to the chunks collection so that
 * yielding cannot occur. This assures that generated ChunkVersions are strictly monotonically
 * increasing -- a second process will not be able to query for max chunk version until the first
 * finishes writing the new highest chunk version it generated.
 *
 * Command Format:
 * {
 *   _configsvrCommitChunkMigration: <database>.<collection>,
 *   fromShard: "<from_shard_name>",
 *   toShard: "<to_shard_name>",
 *   migratedChunk: {min: <min_value>, max: <max_value>, etc. },
 *   fromShardCollectionVersion: { shardVersionField: <version> }, (for backward compatibility only)
 * }
 *
 * Returns:
 * {
 *   migratedChunkVersion: <ChunkVersion_BSON>,
 * }
 *
 */


ChunkType toChunkType(const MigratedChunkType& migratedChunk) {

    ChunkType chunk;
    chunk.setRange({migratedChunk.getMin(), migratedChunk.getMax()});
    chunk.setVersion(migratedChunk.getLastmod());
    return chunk;
}

// TODO (SERVER-127253): Remove this command once v9.0 branches out
class ConfigSvrCommitChunkMigrationCommand
    : public TypedCommand<ConfigSvrCommitChunkMigrationCommand> {
public:
    using Request = CommitChunkMigrationRequest;
    using Response = ConfigSvrCommitChunkMigrationResponse;

    bool skipApiVersionCheck() const override {
        // Internal command (server to server).
        return true;
    }

    std::string help() const override {
        return "should not be calling this directly";
    }

    AllowedOnSecondary secondaryAllowed(ServiceContext*) const override {
        return AllowedOnSecondary::kNever;
    }

    bool adminOnly() const override {
        return true;
    }

    bool supportsRetryableWrite() const final {
        return true;
    }

    class Invocation : public InvocationBase {
    public:
        using InvocationBase::InvocationBase;

        ConfigSvrCommitChunkMigrationResponse typedRun(OperationContext* opCtx) {

            uassert(ErrorCodes::IllegalOperation,
                    "_configsvrCommitChunkMigration can only be run on config servers",
                    serverGlobalParams.clusterRole.has(ClusterRole::ConfigServer));

            // Mark opCtx as interruptible to ensure that all reads and writes to the metadata
            // collections under the exclusive _kChunkOpLock happen on the same term. Take the RSTL
            // and confirm this node can accept writes before setting the flag, so the opCtx is not
            // left unkilled if a stepdown races with a naked
            // setAlwaysInterruptAtStepDownOrUp_UNSAFE (see SERVER-105214).
            // TODO (SERVER-105181): Remove the RSTL/canAcceptWrites guard once intent registration
            // makes it redundant.
            boost::optional<rss::consensus::WriteIntentGuard> writeGuard;
            if (gFeatureFlagIntentRegistration.isEnabled()) {
                writeGuard.emplace(opCtx);
            }
            {
                repl::ReplicationStateTransitionLockGuard rstl(opCtx, MODE_IX);
                auto const replCoord = repl::ReplicationCoordinator::get(opCtx);
                uassert(ErrorCodes::InterruptedDueToReplStateChange,
                        "Node is not primary",
                        replCoord->canAcceptWritesForDatabase(opCtx, ns().dbName()));
                opCtx->setAlwaysInterruptAtStepDownOrUp_UNSAFE();
            }

            const NamespaceString nss = ns();
            auto migratedChunk = toChunkType(request().getMigratedChunk());

            // The donor's move range coordinator sets this flag to request the authoritative
            // commit path. The legacy path leaves it unset, which means the legacy commit path.
            const bool isAuthoritative = request().getAuthoritative().value_or(false);

            ShardingCatalogManager::ShardAndCollectionPlacementVersions shardAndCollVers;
            if (!isAuthoritative) {
                // Legacy non-authoritative path: keep the pre-existing behavior. No ACR and no
                // dummy write.
                repl::ReadConcernArgs::get(opCtx) =
                    repl::ReadConcernArgs(repl::ReadConcernLevel::kLocalReadConcern);

                shardAndCollVers =
                    uassertStatusOK(ShardingCatalogManager::get(opCtx)->commitChunkMigration(
                        opCtx,
                        nss,
                        migratedChunk,
                        request().getFromShardCollectionVersion().epoch(),
                        request().getFromShardCollectionVersion().getTimestamp(),
                        request().getFromShard(),
                        request().getToShard()));
            } else {
                // Authoritative path. The donor's move range coordinator attaches a session id and
                // installs the post-migration metadata into its shard catalog after this command
                // returns. Run the commit under an ACR so the session id stays held; the dummy
                // write below bumps the session's txnNumber so a stale request cannot replay onto a
                // newer state.
                {
                    auto newClient = opCtx->getServiceContext()->getService()->makeClient(
                        "CommitChunkMigration");
                    AlternativeClientRegion acr(newClient);
                    auto executor = Grid::get(opCtx->getServiceContext())
                                        ->getExecutorPool()
                                        ->getFixedExecutor();
                    auto newOpCtxPtr = CancelableOperationContext(
                        cc().makeOperationContext(), opCtx->getCancellationToken(), executor);

                    AuthorizationSession::get(newOpCtxPtr.get()->getClient())
                        ->grantInternalAuthorization();
                    newOpCtxPtr->setWriteConcern(opCtx->getWriteConcern());
                    repl::ReadConcernArgs::get(newOpCtxPtr.get()) =
                        repl::ReadConcernArgs(repl::ReadConcernLevel::kLocalReadConcern);

                    shardAndCollVers = uassertStatusOK(
                        ShardingCatalogManager::get(newOpCtxPtr.get())
                            ->commitChunkMigration(
                                newOpCtxPtr.get(),
                                nss,
                                migratedChunk,
                                request().getFromShardCollectionVersion().epoch(),
                                request().getFromShardCollectionVersion().getTimestamp(),
                                request().getFromShard(),
                                request().getToShard()));
                }

                // No write happened on this txnNumber in the parent opCtx, so make a dummy write
                // to protect against older requests with old txnNumbers being replayed.
                DBDirectClient client(opCtx);
                client.update(NamespaceString::kServerConfigurationNamespace,
                              BSON("_id" << "commitChunkMigrationStats"),
                              BSON("$inc" << BSON("count" << 1)),
                              true /* upsert */,
                              false /* multi */);
            }

            return Response{shardAndCollVers.shardPlacementVersion};
        }

    private:
        bool supportsWriteConcern() const override {
            return true;
        }

        NamespaceString ns() const override {
            return request().getCommandParameter();
        }

        void doCheckAuthorization(OperationContext* opCtx) const override {
            uassert(ErrorCodes::Unauthorized,
                    "Unauthorized",
                    AuthorizationSession::get(opCtx->getClient())
                        ->isAuthorizedForActionsOnResource(
                            ResourcePattern::forClusterResource(request().getDbName().tenantId()),
                            ActionType::internal));
        }
    };
};
MONGO_REGISTER_COMMAND(ConfigSvrCommitChunkMigrationCommand).forShard();

}  // namespace
}  // namespace mongo
