# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# This file defines the format of documents stored in config.ddl.dropCollections on the coordinator
# shard for a drop collection operation.

global:
    mod_visibility: private
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/global_catalog/type_collection.h"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/global_catalog/ddl/sharding_coordinator.idl"
    - "mongo/db/sharding_environment/sharding_types.idl"

enums:
    DropCollectionCoordinatorPhase:
        description: "The current state of a drop collection operation on the coordinator."
        type: string
        values:
            kUnset: "unset"
            kFreezeCollection: "freezeCollection"
            kEnterCriticalSection: "enterCriticalSection"
            kDropCollection: "dropCollection"
            kReleaseCriticalSection: "releaseCriticalSection"

types:
    CollectionInfo:
        description: "Information of the collection to drop."
        bson_serialization_type: object
        cpp_type: CollectionType
        serializer: "mongo::CollectionType::toBSON"
        deserializer: "mongo::CollectionType"
        # CollectionType members are non view types.
        is_view: false

structs:
    DropCollectionCoordinatorDocument:
        description: "Represents a drop collection operation on the coordinator shard."
        generate_comparison_operators: false
        strict: false
        chained_structs:
            ShardingCoordinatorMetadata: ShardingCoordinatorMetadata
        fields:
            phase:
                type: DropCollectionCoordinatorPhase
                default: kUnset
            collInfo:
                description: "Information of the collection to drop, used only for sharded collection."
                type: CollectionInfo
                optional: true
            collectionUUID:
                type: uuid
                description: "The expected UUID of the collection, only set and used in C2C replication."
                optional: true
            # TODO SERVER-73741 remove reference to changeStreamPreciseShardTargetingEnabled once 9.0 becomes last LTS.
            changeStreamsNotifier:
                type: shard_id
                description:
                    "The identity of the Shard that will be responsible to generate the op log entries supporting change stream readers.
                    Only set/consumed when featureFlagChangeStreamPreciseShardTargeting is true."
                optional: true
