# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    mod_visibility: private
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

commands:
    recreateRangeDeletionTasks:
        description: "The public recreateRangeDeletionTasks command on mongos."
        command_name: recreateRangeDeletionTasks
        cpp_name: RecreateRangeDeletionTasksRequest
        namespace: concatenate_with_db
        allow_global_collection_name: true
        api_version: ""
        reply_type: OkReply
        strict: false
        fields:
            skipEmptyRanges:
                description: "If true, only recreate range deletion document if needed"
                type: bool
