# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# refineCollectionShardKey IDL file

global:
    mod_visibility: private
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

commands:
    refineCollectionShardKey:
        description: "The public refineCollectionShardKey command on mongos"
        command_name: refineCollectionShardKey
        strict: false
        namespace: type
        api_version: ""
        type: namespacestring
        fields:
            key:
                type: object
                description: "The index specification document to use as the new shard key."
                optional: false
            collectionUUID:
                type: uuid
                description: "The expected UUID of the collection."
                optional: true
            enforceUniquenessCheck:
                description: >-
                    Controls whether this command verifies that any unique indexes are prefixed by
                    the shard key pattern if unique is true. If true then it will verify and if
                    false then it won't.
                type: optionalBool
