# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# This file defines the format of documents stored in config.ddl.refineCollectionShardKey, used by the
# shard coordinator to serialize with other DDL operations.

global:
    mod_visibility: private
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/global_catalog/ddl/sharding_coordinator.idl"
    - "mongo/db/global_catalog/ddl/sharded_ddl_commands.idl"

enums:
    RefineCollectionShardKeyCoordinatorPhase:
        description: "Current refine collection shard key coordinator's operation state."
        type: string
        values:
            kUnset: "unset"
            kRemoteIndexValidation: "RemoteIndexValidation"
            kBlockCrud: "BlockCrud"
            kCommit: "Commit"
            kReleaseCritSec: "ReleaseCritSec"
            kResumeMigrations: "ResumeMigrations"

structs:
    RefineCollectionShardKeyCoordinatorDocument:
        description: "Object with neccessary fields to refine a collection's shard key"
        generate_comparison_operators: false
        strict: false
        chained_structs:
            ShardingCoordinatorMetadata: ShardingCoordinatorMetadata
            RefineCollectionShardKeyRequest: RefineCollectionShardKeyRequest
        fields:
            phase:
                type: RefineCollectionShardKeyCoordinatorPhase
                description: "Coordinator phase."
                default: kUnset
            newEpoch:
                type: objectid
                description: "The new epoch for the collection."
                optional: true
            newTimestamp:
                type: timestamp
                description: "The new timestamp for the collection."
                optional: true
            uuid:
                type: uuid
                description: "Expected collection uuid."
                optional: true
            oldEpoch:
                type: objectid
                description: "The old epoch of the namespace."
                optional: true
            oldKey:
                type: KeyPattern
                description: "The index specification document that represents the old key."
                optional: true
            oldTimestamp:
                type: timestamp
                description: "Old timestamp for the collection."
                optional: true
