# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# This file defines the format of a state document to be used in test coordinators (not used in
# any actual production coordinator).

global:
    mod_visibility: private
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/global_catalog/type_collection.h"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/shard_role/ddl/coll_mod.idl"
    - "mongo/db/global_catalog/ddl/sharding_coordinator.idl"
    - "mongo/db/sharding_environment/sharding_types.idl"

enums:
    TestChunkOperationShardingCoordinatorPhase:
        description: "State enumeration"
        type: string
        values:
            kUnset: "unset"
            kPhase1: "kPhase1"
            kPhase2: "kPhase2"

structs:
    TestChunkOperationShardingCoordinatorDocument:
        description: "State document."
        generate_comparison_operators: false
        strict: false
        chained_structs:
            ShardingCoordinatorMetadata: ShardingCoordinatorMetadata
        fields:
            phase:
                type: TestChunkOperationShardingCoordinatorPhase
                default: kUnset
