# -*- mode: python -*-

Import("env")

env.Library(
    target='replset_dist_lock_manager',
    source=[
        'replset_dist_lock_manager.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/s/catalog/dist_lock_catalog_interface',
        '$BUILD_DIR/mongo/s/catalog/dist_lock_manager'
    ],
)

env.CppUnitTest(
    target='replset_dist_lock_manager_test',
    source=[
        'replset_dist_lock_manager_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/service_context',
        '$BUILD_DIR/mongo/s/catalog/dist_lock_catalog_mock',
        '$BUILD_DIR/mongo/util/foundation',
        '$BUILD_DIR/mongo/util/tick_source_mock',
        'replset_dist_lock_manager'
    ]
)

env.Library(
    target='catalog_manager_replica_set',
    source=[
        'catalog_manager_replica_set.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/s/catalog/catalog_manager',
        '$BUILD_DIR/mongo/s/catalog/dist_lock_manager',
        '$BUILD_DIR/mongo/s/client/sharding_client',
    ]
)

env.CppUnitTest(
    target='catalog_manager_replica_set_test',
    source=[
        'catalog_manager_replica_set_add_shard_test.cpp',
        'catalog_manager_replica_set_drop_coll_test.cpp',
        'catalog_manager_replica_set_log_action_test.cpp',
        'catalog_manager_replica_set_log_change_test.cpp',
        'catalog_manager_replica_set_remove_shard_test.cpp',
        'catalog_manager_replica_set_shard_collection_test.cpp',
        'catalog_manager_replica_set_test.cpp',
        'catalog_manager_replica_set_test_fixture.cpp',
        'catalog_manager_replica_set_upgrade_test.cpp',
    ],
    LIBDEPS=[
        'catalog_manager_replica_set',
        '$BUILD_DIR/mongo/client/remote_command_targeter_mock',
        '$BUILD_DIR/mongo/db/auth/authorization_manager_mock_init',
        '$BUILD_DIR/mongo/executor/network_test_env',
        '$BUILD_DIR/mongo/s/catalog/dist_lock_manager_mock',
        '$BUILD_DIR/mongo/s/coreshard',
        '$BUILD_DIR/mongo/s/mongoscore',
        '$BUILD_DIR/mongo/util/net/message_port_mock',
    ]
)
