# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0
global:
    cpp_namespace: "mongo"

structs:
    GenericArguments:
        description: "Adding new generic arguments, removing an unstable generic argument should still pass"
        is_generic_cmd_list: "arg"
        fields:
            genericArgument:
                type: dummyType
                stability: stable
                forward_to_shards: false
            unstableGenericArgument:
                type: dummyType
                forward_to_shards: false
                stability: unstable
            addedGenericArgument:
                type: dummyType
                forward_to_shards: false
            addedUnstableGenericArgument:
                type: dummyType
                stability: unstable
                forward_to_shards: false

    GenericReplyFields:
        description: "Adding new generic reply fields, removing an unstable generic reply field should still pass"
        is_generic_cmd_list: "reply"
        fields:
            genericReplyField:
                type: dummyType
                forward_from_shards: false
            unstableGenericReplyField:
                type: dummyType
                forward_from_shards: false
                stability: unstable
            addedGenericReplyField:
                type: dummyType
                forward_from_shards: false
            addedUnstableGenericReplyField:
                type: dummyType
                stability: unstable
                forward_from_shards: false
            addedInternalGenericReplyField:
                type: dummyType
                stability: internal
                forward_from_shards: false
