# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"

configs:
    "net.compression.compressors":
        mod_visibility: public
        description: "Comma-separated list of compressors to use for network messages"
        source: [cli, ini, yaml]
        arg_vartype: String
        short_name: networkMessageCompressors
        default: disabled
        hidden: true
