# -*- mode: python -*-

Import('env')

env = env.Clone()

env.Library(
    target='fault_manager',
    source=[
        'fault_impl.cpp',
        'fault_manager.cpp',
        'health_observer_base.cpp',
        'health_observer_registration.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/service_context',
    ],
    LIBDEPS_PRIVATE=[
    ],
)

env.CppUnitTest(
    target='fault_base_classes_test',
    source=[
        'fault_impl_test.cpp',
        'fault_facet_test.cpp',
        'health_observer_test.cpp',
        'fault_manager_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/util/clock_source_mock',
        'fault_manager',
    ],
)
