# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Benchmark(
    target="key_gen_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="second_half_bm",
)

env.CppUnitTest(
    target="db_index_test",
    source=[],
    LIBDEPS=[],
)
