# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    mod_visibility: public

imports:
    - "mongo/db/basic_types.idl"

enums:
    PhaseTransitionProgress:
        description: >-
            Progress of a phase transition for use with PauseDuringPhaseTransitionFailPoint. The 
            failpoint should be evaluated at the following times for each progress value:
                Before: Prior to updating phase in any way.
                Partial: After writing to disk, but before updating in-memory phase.
                After: After phase is updated on-disk and in-memory.
        type: string
        values:
            kBefore: "before"
            kPartial: "partial"
            kAfter: "after"
