# -*- mode: python; -*-

Import("env")

env = env.Clone()

env.BazelProgram(
    target="bson_column_encoder",
    source=[],
)

env.Benchmark(
    target="simple8b_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="bsoncolumn_bm",
)

env.CppUnitTest(
    target="bsoncolumn_test",
    source=[],
)

env.Benchmark(
    target="bson_column_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="bsoncolumn_bm",
)

env.CppLibfuzzerTest(
    target="simple8b_fuzzer",
    source=[],
)

env.CppLibfuzzerTest(
    target="bson_column_validate_fuzzer",
    source=[],
)

env.CppLibfuzzerTest(
    target="bsoncolumn_decompress_fuzzer",
    source=[],
)

env.CppLibfuzzerTest(
    target="bsoncolumn_builder_fuzzer",
    source=[],
)

env.CppLibfuzzerTest(
    target="bsoncolumn_decompress_paths_fuzzer",
    source=[],
)

env.CppLibfuzzerTest(
    target="bsoncolumnbuilder_reopen_fuzzer",
    source=[],
)
