load("//bazel:mongo_src_rules.bzl", "mongo_cc_library")

package(default_visibility = ["//visibility:public"])

exports_files(glob([
    "*.cpp",
    "*.h",
]))

mongo_cc_library(
    name = "represent_as_util",
    hdrs = [
        "represent_as_util.h",
    ],
    deps = [
        "//src/mongo:base",
    ],
)
