# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='sharding_client',
    source=[
        'shard_remote.cpp',
         env.Idlc('shard_remote.idl')[0],
    ],
    LIBDEPS=[
        '$BUILD_DIR/merizo/client/fetcher',
        '$BUILD_DIR/merizo/db/commands',
        '$BUILD_DIR/merizo/db/lasterror',
        '$BUILD_DIR/merizo/executor/task_executor_pool',
        '$BUILD_DIR/merizo/s/grid',
        'shard_interface',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/merizo/idl/server_parameter',
    ],
)

env.CppUnitTest(
    target='shard_remote_test',
    source=[
        'shard_remote_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/merizo/s/sharding_router_test_fixture',
        '$BUILD_DIR/merizo/s/query/async_results_merger',
        'sharding_client',
    ],
)

env.CppUnitTest(
    target='shard_registry_test',
    source=[
        'shard_registry_data_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/merizo/s/coreshard',
        '$BUILD_DIR/merizo/s/sharding_router_test_fixture',
    ],
)

env.Library(
    target='shard_interface',
    source=[
        'shard.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/merizo/base',
        '$BUILD_DIR/merizo/client/remote_command_retry_scheduler',
        '$BUILD_DIR/merizo/s/common_s',
        '$BUILD_DIR/merizo/s/write_ops/batch_write_types',
    ],
)

env.Library(
    target='rs_local_client',
    source=[
        'rs_local_client.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/merizo/client/clientdriver_minimal',
        '$BUILD_DIR/merizo/db/dbdirectclient',
        '$BUILD_DIR/merizo/db/repl/repl_coordinator_interface',
    ],
)

env.Library(
    target='shard_local',
    source=[
        'shard_local.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/merizo/client/clientdriver_minimal',
        '$BUILD_DIR/merizo/db/repl/repl_coordinator_interface',
        'rs_local_client',
        'shard_interface',
    ],
)

env.CppUnitTest(
    target='shard_local_test',
    source=[
        'shard_local_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/merizo/db/auth/authmocks',
        '$BUILD_DIR/merizo/db/repl/replmocks',
        '$BUILD_DIR/merizo/db/service_context_d_test_fixture',
        '$BUILD_DIR/merizo/s/grid',
        'shard_local',
    ],
)
