Import(
    [
        "env",
    ]
)

env = env.Clone()

env.Benchmark(
    target="plan_cache_key_encoding_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)

env.Benchmark(
    target="plan_cache_classic_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)
