load("@poetry//:dependencies.bzl", "dependency")
load("//bazel:mongo_script_rules.bzl", "mongo_toolchain_py_cxx_test")
load("@rules_python//python:defs.bzl", "py_library")

mongo_toolchain_py_cxx_test(
    name = "test_clang_tidy",
    srcs = [
        "test_clang_tidy.py",
    ],
    main = "test_clang_tidy.py",
    visibility = ["//visibility:public"],
    deps = [
        "//buildscripts:clang_tidy_lib",
        "//buildscripts:mongo_toolchain",
        dependency(
            "pyyaml",
            group = "core",
        ),
    ],
)

py_test(
    name = "test_benchmark_profiler",
    srcs = ["test_benchmark_profiler.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//buildscripts:benchmark_profiler",
    ],
)

py_test(
    name = "test_generate_version_expansions",
    srcs = ["test_generate_version_expansions.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//buildscripts:generate_version_expansions",
    ],
)

py_test(
    name = "test_gather_failed_tests",
    srcs = ["test_gather_failed_tests.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//buildscripts:gather_failed_tests",
    ],
)

py_test(
    name = "test_package_test_provenance",
    srcs = ["test_package_test_provenance.py"],
    data = ["//:.bazelversion"],
    visibility = ["//visibility:public"],
    deps = [
        "//buildscripts:generate_bazel_spawn_pb2",
        "//buildscripts:package_test_provenance",
    ],
)

# TODO(SERVER-105817): The following library is autogenerated, please split these out into individual python targets
py_library(
    name = "all_python_files",
    srcs = glob(["*.py"]),
    visibility = ["//visibility:public"],
)
