# Copyright (C) 2020-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

# This file defines the format of documents stored in config.reshardingOperations on the config
# server.

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/s/resharding/common_types.idl"

structs:
    DonorShardEntry:
        description: "Represents a donor shard for a particular resharding operation on the
                      coordinator."
        inline_chained_structs: true
        chained_structs:
            MinFetchTimestamp: MinFetchTimestampStruct
            AbortReason: AbortReasonStruct
        generate_comparison_operators: false
        strict: true
        fields:
            id: shard_id
            state:
                type: DonorState
                optional: true
            cloneSizeInfo:
                type: ReshardingCloneSize
                optional: true

    RecipientShardEntry:
        description: "Represents a recipient shard for a particular resharding operation on the
                      coordinator."
        inline_chained_structs: true
        chained_structs:
            StrictConsistencyTimestamp: StrictConsistencyTimestampStruct
            AbortReason: AbortReasonStruct
        generate_comparison_operators: false
        strict: true
        fields:
            id: shard_id
            state:
                type: RecipientState
                optional: true

    ReshardingCoordinatorDocument:
        description: "Represents a resharding operation on the coordinator."
        inline_chained_structs: true
        chained_structs:
            CommonReshardingMetadata: CommonReshardingMetadata
            FetchTimestamp: FetchTimestampStruct
            AbortReason: AbortReasonStruct
        generate_comparison_operators: false
        strict: true
        fields:
            tempReshardingNss:
                type: namespacestring
                description: "The namespace of the temporary resharding collection that exists on
                            recipient shards."
            state: CoordinatorState
            donorShards:
                type: array<DonorShardEntry>
                description: "The list of all donor shards for this resharding operation."
            recipientShards:
                type: array<RecipientShardEntry>
                description: "The list of all recipient shards for this resharding operation."
            zones:
                type: array<object_owned>
                description: "The zones associated with the new shard key."
                optional: true
            presetReshardedChunks:
                type: array<object_owned>
                description: >-
                    Mapping of chunk ranges to be used as the initial split output. This is only
                    for testing purposes.
                optional: true         
