# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# This file defines the document used for storing progress by the resharding oplog applier.

global:
    mod_visibility: private
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/s/resharding/donor_oplog_id.idl"
    - "mongo/s/resharding/common_types.idl"
    - "mongo/db/sharding_environment/sharding_types.idl"

structs:
    ReshardingOplogApplierProgress:
        description: "Used for storing the progress made by the resharding oplog applier."
        # Use strict:false to avoid complications around upgrade/downgrade. This isn't technically
        # required for resharding because durable state from all resharding operations is cleaned up
        # before the upgrade or downgrade can complete.
        strict: false
        fields:
            _id:
                type: ReshardingSourceId
                description: "The identifier for the source of the oplog entries."
                cpp_name: oplogSourceId
            progress:
                type: ReshardingDonorOplogId
                description: >-
                    The minimum point where the resharding oplog applier can start without missing
                    any oplog it needs to process.
            numEntriesApplied:
                type: long
                description: >-
                    The total number of oplog entries that have been applied by this
                    ReshardingOplogApplier.
            insertsApplied:
                type: safeInt64
                default: 0
                description: >-
                    The total number of insert type oplog entries that have been applied by this
                    ReshardingOplogApplier.
            updatesApplied:
                type: safeInt64
                default: 0
                description: >-
                    The total number of update type oplog entries that have been applied by this
                    ReshardingOplogApplier.
            deletesApplied:
                type: safeInt64
                default: 0
                description: >-
                    The total number of delete type oplog entries that have been applied by this
                    ReshardingOplogApplier.
            writesToStashCollections:
                type: safeInt64
                default: 0
                description: >-
                    The total number of insert/update/delete to stash collections (including writes
                    that resulted in no-op).
