# Copyright (C) 2026-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

# This file defines the internal commands sent by the resharding coordinator to shard servers.

global:
    mod_visibility: private
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/s/resharding/common_types.idl"

structs:
    ShardsvrReshardingDonorFetchFinalCollectionStatsResponse:
        description: "Response for the _shardsvrReshardingDonorFetchFinalCollectionStats command."
        is_command_reply: true
        strict: false
        fields:
            documentsDelta:
                type: safeInt64
                description: "The change in the number of documents since the provided cloneTimestamp."

commands:
    _shardsvrReshardDonorInitialize:
        description:
            "The internal command sent by the coordinator to donor shards to
            initialize the resharding donor state machine."
        command_name: _shardsvrReshardDonorInitialize
        cpp_name: ShardsvrReshardDonorInitialize
        type: uuid
        strict: false
        namespace: type
        reply_type: OkReply
        api_version: ""
        fields:
            commonReshardingMetadata: CommonReshardingMetadata
            recipientShards:
                type: array<shard_id>
                description: "The list of recipient shards participating in the resharding operation."

    _shardsvrReshardingDonorStartChangeStreamsMonitor:
        command_name: _shardsvrReshardingDonorStartChangeStreamsMonitor
        cpp_name: ShardsvrReshardingDonorStartChangeStreamsMonitor
        description:
            "The internal command for making a resharding donor shard start monitoring the
            changes in the collection being resharded between the start of
            the cloning phase and the start of the critical section."
        namespace: type
        type: namespacestring
        reply_type: OkReply
        api_version: ""
        strict: false
        fields:
            reshardingUUID:
                type: uuid
                description: "The UUID for the resharding operation."
            cloneTimestamp:
                type: timestamp
                description: "The clone timestamp for the resharding operation."

    _shardsvrReshardingDonorFetchFinalCollectionStats:
        command_name: _shardsvrReshardingDonorFetchFinalCollectionStats
        cpp_name: ShardsvrReshardingDonorFetchFinalCollectionStats
        description:
            "The internal command for querying a resharding donor shard for the changes in
            the number of documents in the collection being resharded between the start of
            the cloning phase and the start of the critical section."
        namespace: type
        type: namespacestring
        reply_type: ShardsvrReshardingDonorFetchFinalCollectionStatsResponse
        api_version: ""
        strict: false
        fields:
            reshardingUUID:
                type: uuid
                description: "The UUID for the resharding operation."

    _shardsvrReshardRecipientInitialize:
        description:
            "The internal command sent by the coordinator to recipient shards to
            initialize the resharding recipient state machine."
        command_name: _shardsvrReshardRecipientInitialize
        cpp_name: ShardsvrReshardRecipientInitialize
        type: uuid
        strict: false
        namespace: type
        reply_type: OkReply
        api_version: ""
        fields:
            commonReshardingMetadata: CommonReshardingMetadata
            recipientOptions: ReshardingRecipientOptions

    _shardsvrReshardRecipientClone:
        description: "The internal recipient clone command."
        command_name: _shardsvrReshardRecipientClone
        cpp_name: ShardsvrReshardRecipientClone
        type: uuid
        strict: false
        namespace: type
        reply_type: OkReply
        api_version: ""
        fields:
            cloneTimestamp:
                type: timestamp
                description: "The timestamp for the snapshot read while cloning from the donors."
            donorShards:
                type: array<DonorShardFetchTimestamp>
                description: "The list of donors to clone from."
            approxCopySize:
                type: ReshardingApproxCopySize
                description: "Not meant to be used directly. Only use internal fields."

    _shardsvrReshardRecipientCriticalSectionStarted:
        description:
            "The internal command run by coordinator against recipients to notify them that the
            critical section has started."
        command_name: _shardsvrReshardRecipientCriticalSectionStarted
        cpp_name: ShardsvrReshardRecipientCriticalSectionStarted
        type: uuid
        strict: false
        namespace: type
        reply_type: OkReply
        api_version: ""
