# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0
global:
    mod_visibility: private
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/util/assert_util_parameters.h"

server_parameters:
    enableDiagnosticLogging:
        description: "Enables additional diagnostic logging during tassert, invariant, and signal handing. If set to false, diagnostic logging won't happen in any scenario."
        set_at: ["startup", "runtime"]
        cpp_varname: "enableDiagnosticLogging"
        cpp_vartype: Atomic<bool>
        default: true
        redact: false
        on_update: onUpdateEnableDiagnosticLogging

    signalHandlerUsesDiagnosticLogging:
        description: "When true, diagnostic logging will occur during invariant and signal handling."
        set_at: ["startup", "runtime"]
        cpp_varname: "signalHandlerUsesDiagnosticLogging"
        cpp_vartype: Atomic<bool>
        default: true
        redact: false
        on_update: onUpdateSignalHandlerUsesDiagnosticLogging
