# Copyright (C) 2024-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
  cpp_namespace: "mongo"

imports:
  - "mongo/db/basic_types.idl"

structs:
  BuildInfoOpenSSL:
    description: "Information about the SSL implementation used (OpenSSL, SChannel, or SecureTransport)"
    fields:
      running:
        description: "The version of OpenSSL actually loaded as a shared object"
        type: string
      compiled:
        description: "The version of OpenSSL used to compile MongoDB"
        type: string
        optional: true

  BuildInfoMacOS:
    description: "Reply fields specific to macOS"
    fields:
      osProductVersion:
        description: "Value of kern.osproductversion"
        type: string
      osRelease:
        description: "Value of kern.osrelease"
        type: string
      version:
        description: "Value of kern.version"
        type: string

  BuildInfo:
    description: "Response from the buildInfo command"
    inline_chained_structs: true
    fields:
      version:
        description: "The current MongoDB server version, e.g. '1.2.3-rc0'"
        type: string
      versionArray:
        description: "The current MongoDB server version broken down by numeric component, e.g. [1, 2, 3, 4]"
        type: array<safeInt>

      # Fields which may depend on level of authentication
      gitVersion:
        description: "Source repository git hash at build time"
        type: string
        optional: true
      targetMinOS:
        description: "Windows only: The minimum OS required for this build; e.g. 'Windows 7/Windows Server 2008 R2'"
        type: string
        optional: true
      modules:
        description: "The set of modules included in this build; e.g. ['enterprise']"
        type: array<string>
        optional: true
      allocator:
        description: "The memory allocator used in this build; e.g. 'system'"
        type: string
        optional: true
      javascriptEngine:
        description: "The Javascript runtime engine used in this build; e.g. 'mozjs'"
        type: string
        optional: true
      sysinfo:
        description: "DEPRECATED: This field always contains the string 'deprecated' if present"
        type: string
        optional: true
      openssl:
        description: "Information about the SSL implementation used (OpenSSL, SChannel, or SecureTransport)"
        type: BuildInfoOpenSSL
        optional: true
      buildEnvironment:
        description: "Properties relating to the build conditions when MongoDB was compiled"
        type: object # key/value pairs
        optional: true
      bits:
        description: "Word size on the system architecture; e.g. 64"
        type: safeInt
        optional: true
      debug:
        description: "Whether or not this is a debug build"
        type: safeBool
        optional: true
      maxBsonObjectSize:
        description: "Size limit for BSON objects; e.g. 16777216 (16MB)"
        type: safeInt64
        optional: true
      macOS:
        description: "macOS specific buildInfo data"
        type: BuildInfoMacOS
        optional: true
      storageEngines:
        description: "List of available storage engines; e.g. ['wt']"
        type: array<string>
        optional: true

      mongotmock:
        description: "TRUE when provided by mongotmock"
        type: safeBool
        optional: true
