# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    mod_visibility: private
    cpp_namespace: mongo

server_parameters:
    newLineAfterPasswordPromptForTest:
        description: >
            The askPassword function will print a new line after the "Enter password:" prompt
            so that tests see the prompt in log output immediately.
        set_at:
            - startup
        cpp_vartype: bool
        cpp_varname: newLineAfterPasswordPromptForTest
        default: false
        redact: false
