load("//bazel/uv:defs.bzl", "dependency")
load(":separate_debug.bzl", "gdb_index_message")
load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load(":test_exec_properties_test.bzl", "test_exec_properties_test_suite")

package(default_visibility = ["//visibility:public"])

# Expose script for external usage through bazel.
exports_files([
    "hermetic_container/hermetic_container.py",
    "install_rules.py",
    "run_under_working_dir.sh",
])

sh_binary(
    name = "lint",
    srcs = ["lint.sh"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "gdb-add-index-noop",
    srcs = ["gdb_add_index_noop.sh"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "gdb-generate-index-noop",
    srcs = ["gdb_add_index_noop.sh"],
    visibility = ["//visibility:public"],
)

sh_binary(
    name = "gdb-apply-index",
    srcs = ["gdb_apply_index.sh"],
    visibility = ["//visibility:public"],
)

gdb_index_message(
    name = "gdb-index-message",
    enabled = select({
        "//bazel/config:gdb_index_enabled_linux": True,
        "//conditions:default": False,
    }),
)

py_binary(
    name = "bazelisk",
    srcs = ["bazelisk.py"],
)

py_library(
    name = "bazelisk_lib",
    srcs = ["bazelisk.py"],
    imports = ["."],
)

py_binary(
    name = "merge_tidy_configs",
    srcs = [
        "merge_tidy_configs.py",
    ],
    main = "merge_tidy_configs.py",
    visibility = ["//visibility:public"],
    deps = [
        dependency(
            "pyyaml",
            group = "core",
        ),
    ],
)

py_binary(
    name = "gpg_signer",
    srcs = ["gpg_signer.py"],
    main = "gpg_signer.py",
    visibility = ["//visibility:public"],
)

py_test(
    name = "gpg_signer_test",
    srcs = ["gpg_signer_test.py"],
    data = ["gpg_signer.py"],
    main = "gpg_signer_test.py",
)

filegroup(
    name = "test_wrapper",
    srcs = ["test_wrapper.sh"],
)

# TODO(SERVER-129799): add these tests to CI.
test_exec_properties_test_suite(name = "test_exec_properties_tests")
