# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="db_timeseries_write_ops_test",
    source=[
        "timeseries_write_ops_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/catalog/catalog_test_fixture",
        "$BUILD_DIR/mongo/db/collection_crud/collection_crud",
        "$BUILD_DIR/mongo/db/query/write_ops/write_ops_exec",
        "$BUILD_DIR/mongo/db/timeseries/write_ops/timeseries_write_ops",
    ],
)
