# -*- mode: python -*-

Import(
    [
        "env",
    ]
)

env = env.Clone()

env.CppUnitTest(
    target="cursor_manager_test",
    source=[
        "cursor_manager_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query_exec",
        "$BUILD_DIR/mongo/db/service_context",
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "$BUILD_DIR/mongo/db/service_context_test_fixture",
        "$BUILD_DIR/mongo/util/clock_source_mock",
        "client_cursor",
    ],
)
