#!/bin/bash

cd `dirname $0`

export CLASSPATH=.:jars:
for j in `find jars \( -name webtest -type d \) -prune -o -type f -name '*.jar' -print`; do
    export CLASSPATH="$CLASSPATH":$j
done
export CLASSPATH="$CLASSPATH":/opt/java/lib/tools.jar

export java_lib_path="-Djava.library.path=include"
export headless="-Djava.awt.headless=true"

export standard_options="-enableassertions $java_lib_path $headless $jruby_home"

export memory_large="-Xmx1000m -XX:MaxDirectMemorySize=600M"
export memory_small="-Xmx200m  -XX:MaxDirectMemorySize=200M"

export java_memory_large="java $standard_options $memory_large"
export java_memory_small="java $standard_options $memory_small"

$java_memory_small ed.db.Shell "$@"

