# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/query/search/search_index_options.h"
    mod_visibility: private

server_parameters:
    searchIndexManagementHostAndPort:
        description: "Search index management host address"
        set_at: [startup]
        default: ""
        cpp_varname: "globalSearchIndexParams.host"
        validator:
            callback: "SearchIndexParams::onValidateHost"
        redact: false

    skipAuthenticationToSearchIndexManagementServer:
        description: "Skip authentication for mongod->search-index-server connections, even if auth is enabled on mongod"
        set_at: [startup]
        cpp_varname: "globalSearchIndexParams.skipAuthToSearchIndexServer"
        default: false
        redact: false
