#!/bin/bash
# 
# Script that generates keyfile for replicasets/shards
#
# Tomas Srnka <tomas.srnka@relbit.com>
#

KEYFILE_PATH="/etc/mongod/keyfile"

if [ -f $KEYFILE_PATH ] && [ "$1" != "-f" ]; then
	echo "KeyFile exists at $KEYFILE_PATH"
	echo "Use -f to overwrite the file."	
	exit 1	
fi

key=`cat /dev/urandom |tr -dc A-Za-z0-9 | head -c 256`
echo -e $key > $KEYFILE_PATH
chmod 700 $KEYFILE_PATH
chown mongod:mongod $KEYFILE_PATH
echo "File generated"

exit 0


