"""FCV and Server binary version constants used for multiversion testing."""

LAST_STABLE_BIN_VERSION = "4.2"
LAST_STABLE_FCV = "4.2"
LATEST_FCV = "4.4"

LAST_STABLE_MONGO_BINARY = "mongo-" + LAST_STABLE_BIN_VERSION
LAST_STABLE_MONGOD_BINARY = "mongod-" + LAST_STABLE_BIN_VERSION
LAST_STABLE_MONGOS_BINARY = "mongos-" + LAST_STABLE_BIN_VERSION
REQUIRES_FCV_TAG = "requires_fcv_44"
