// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#pragma once

#include "mongo/util/modules.h"

#include <string>

namespace mongo {
namespace unicode {

/**
 * There are currently two options supported for the delimiter list. The only difference between the
 * English and NotEnglish modes is that in English, the apostrophe is considered a delimiter, while
 * in NotEnglish, it is not.
 */
enum class DelimiterListLanguage {
    kEnglish,
    kNotEnglish,
};

/**
 * There are currently two Case folding modes supported. The only difference between the Normal mode
 * and the Turkish mode is that in the Turkish mode, the letter I is lowercased to ı, and the letter
 * İ is lowercased to i. In the normal mode, the letter I is lowercased to i, and there is no
 * mapping for İ.
 */
enum class CaseFoldMode {
    kNormal,
    kTurkish,
};

/**
 * Returns whether or not the given codepoint is a diacritic. In 'D' normalized Unicode text,
 * diacritics are removed by removing characters with these codepoints.
 */
bool codepointIsDiacritic(char32_t codepoint);

/**
 * Returns whether or not the given codepoint is considered a delimiter in the language 'lang'.
 * Currently, there is only a difference between English and non-English languages (the apostrophe).
 * To see which Unicode character categories were considered delimiters, see gen_delimiter_list.py.
 */
bool codepointIsDelimiter(char32_t codepoint, DelimiterListLanguage lang);

/**
 * Return a version of the given codepoint without any diacritics. These mappings are generated by
 * taking all of the characters within a set of Unicode code blocks (see gen_diacritic_map.py to see
 * which code blocks are used), decomposing them to the NFD normalization form, removing any
 * combining marks, and renormalizing them to the NFC form. The result is a mapping from original
 * codepoint to a codepoint with no diacritics.
 *
 * Returns 0 if codepoint is a pure diacritic mark (ie if codepointIsDiacritic() would return true).
 * You will need to distinguish this case from the input codepoint being 0 either by explicit
 * checking or avoiding a call to this function if codepoint is in the ASCII range (<0x80).
 */
char32_t codepointRemoveDiacritics(char32_t codepoint);

/**
 * Return the lowercased version of the given codepoint, applying the special Turkish version of
 * case folding if specified.
 */
char32_t codepointToLower(char32_t codepoint, CaseFoldMode mode = CaseFoldMode::kNormal);

}  // namespace unicode
}  // namespace mongo
