# -*- mode: python; -*-

Import("env")
Import("get_option")
Import("has_option")
Import("wiredtiger")

env = env.Clone()

env.BazelProgram(
    target="dbtest",
    source=[],
    LIBDEPS=[],
    AIB_COMPONENT="dbtest",
    AIB_COMPONENTS_EXTRA=[
        "tests",
    ],
)
