// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#include "mongo/db/commands/query_cmd/acquire_locks.h"

#include "mongo/db/profile_settings.h"
#include "mongo/db/repl/speculative_majority_read_info.h"
#include "mongo/util/scopeguard.h"

namespace mongo {

namespace {
void applyCursorReadConcern(OperationContext* opCtx, repl::ReadConcernArgs rcArgs) {
    const auto isReplSet = repl::ReplicationCoordinator::get(opCtx)->getSettings().isReplSet();

    // Select the appropriate read source. If we are in a transaction with read concern majority,
    // this will already be set to kNoTimestamp, so don't set it again.
    if (isReplSet && rcArgs.getLevel() == repl::ReadConcernLevel::kMajorityReadConcern &&
        !opCtx->inMultiDocumentTransaction()) {
        switch (rcArgs.getMajorityReadMechanism()) {
            case repl::ReadConcernArgs::MajorityReadMechanism::kMajoritySnapshot: {
                // Make sure we read from the majority snapshot.
                shard_role_details::getRecoveryUnit(opCtx)->setTimestampReadSource(
                    RecoveryUnit::ReadSource::kMajorityCommitted);
                uassertStatusOK(shard_role_details::getRecoveryUnit(opCtx)
                                    ->majorityCommittedSnapshotAvailable());
                break;
            }
            case repl::ReadConcernArgs::MajorityReadMechanism::kSpeculative: {
                // Mark the operation as speculative and select the correct read source.
                repl::SpeculativeMajorityReadInfo::get(opCtx).setIsSpeculativeRead();
                shard_role_details::getRecoveryUnit(opCtx)->setTimestampReadSource(
                    RecoveryUnit::ReadSource::kNoOverlap);
                break;
            }
        }
    }

    if (isReplSet && rcArgs.getLevel() == repl::ReadConcernLevel::kSnapshotReadConcern &&
        !opCtx->inMultiDocumentTransaction()) {
        auto atClusterTime = rcArgs.getArgsAtClusterTime();
        invariant(atClusterTime && *atClusterTime != LogicalTime::kUninitialized);
        shard_role_details::getRecoveryUnit(opCtx)->setTimestampReadSource(
            RecoveryUnit::ReadSource::kProvided, atClusterTime->asTimestamp());
    }

    // For cursor commands that take locks internally, the read concern on the
    // OperationContext may affect the timestamp read source selected by the storage engine.
    // We place the cursor read concern onto the OperationContext so the lock acquisition
    // respects the cursor's read concern.
    {
        std::lock_guard<Client> lk(*opCtx->getClient());
        repl::ReadConcernArgs::get(opCtx) = rcArgs;
    }
}
}  // namespace

void applyConcernsAndReadPreference(OperationContext* opCtx, const ClientCursor& cursor) {
    applyCursorReadConcern(opCtx, cursor.getReadConcernArgs());
    opCtx->setWriteConcern(cursor.getWriteConcernOptions());
    ReadPreferenceSetting::get(opCtx) = cursor.getReadPreferenceSetting();
}

CursorLocks::CursorLocks(OperationContext* opCtx,
                         const NamespaceString& nss,
                         ClientCursorPin& cursorPin) {
    extDataSourceScopeGuard = ExternalDataSourceScopeGuard::get(cursorPin.getCursor());

    // Update opCtx of the decorated ExternalDataSourceScopeGuard object so that it can drop
    // virtual collections in the new 'opCtx'.
    ExternalDataSourceScopeGuard::updateOperationContext(cursorPin.getCursor(), opCtx);

    ScopeGuard cursorDeleter([&] {
        cursorPin.deleteUnderlying();
        if (txnResourcesHandler) {
            txnResourcesHandler->dismissRestoredResources();
        }
    });

    // Cursors come in one of two flavors:
    //
    // - Cursors which read from a single collection, such as those generated via the
    //   find command. For these cursors, we hold the appropriate collection lock for the
    //   duration of the getMore using shard role acquisitions. These cursors have the
    //   'kLockExternally' lock policy.
    //
    // - Cursors which may read from many collections, e.g. those generated via the
    //   aggregate command, or which do not read from a collection at all, e.g. those
    //   generated by the listIndexes command. We don't need to acquire locks to use these
    //   cursors, since they either manage locking themselves or don't access data protected
    //   by collection locks. These cursors have the 'kLocksInternally' lock policy.
    //
    // While we only need to acquire locks for 'kLockExternally' cursors, we need to create
    // an AutoStatsTracker in either case. This is responsible for updating statistics in
    // CurOp and Top.
    if (cursorPin->getExecutor()->lockPolicy() == PlanExecutor::LockPolicy::kLocksInternally) {
        // Profile whole-db/cluster change stream getMore commands.
        if (!nss.isCollectionlessCursorNamespace() ||
            CurOp::get(opCtx)->debug().isChangeStreamQuery) {
            statsTracker.emplace(opCtx,
                                 nss,
                                 Top::LockType::NotLocked,
                                 AutoStatsTracker::LogMode::kUpdateTopAndCurOp,
                                 DatabaseProfileSettings::get(opCtx->getServiceContext())
                                     .getDatabaseProfileLevel(nss.dbName()));
        }
    } else {
        invariant(cursorPin->getExecutor()->lockPolicy() ==
                  PlanExecutor::LockPolicy::kLockExternally);

        // Restore the acquisitions used in the original call. This takes care of
        // checking that the preconditions for the original acquisition still hold and
        // restores any locks necessary.
        txnResourcesHandler.emplace(opCtx, cursorPin.getCursor());

        statsTracker.emplace(opCtx,
                             nss,
                             Top::LockType::ReadLocked,
                             AutoStatsTracker::LogMode::kUpdateTopAndCurOp,
                             DatabaseProfileSettings::get(opCtx->getServiceContext())
                                 .getDatabaseProfileLevel(nss.dbName()));

        // Check whether we are allowed to read from this node after acquiring our locks.
        // Only check when there is at least one acquired collection/view – it is possible that a
        // ShardRole acquisition is empty when the enclosed executor is a trivial EOF plan.
        if (!shard_role_details::TransactionResources::get(opCtx).isEmpty()) {
            uassertStatusOK(
                repl::ReplicationCoordinator::get(opCtx)->checkCanServeReadsFor(opCtx, nss, true));
        }
    }

    cursorDeleter.dismiss();
}

}  // namespace mongo
