# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    mod_visibility: private
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/topology/cluster_parameters/cluster_server_parameter_refresher.h"

imports:
    - "mongo/db/basic_types.idl"

server_parameters:
    clusterServerParameterRefreshIntervalSecs:
        description: >
            On a mongos instance, specifies the interval (in seconds) at which the mongos instance
            refreshes its in-memory cache of cluster server parameters.
        cpp_varname: clusterServerParameterRefreshIntervalSecs
        cpp_vartype: Atomic<int>
        set_at: [startup, runtime]
        default: 30
        on_update: clusterServerParameterRefreshIntervalSecsNotify
        validator:
            gte: 1
            lte: 86400
        redact: false
