#!/bin/env bash

cat << EOF > ${WORK_DIR}/sast_report_generation_credentials.env
COVERITY_USERNAME=${SAST_REPORT_COVERITY_USERNAME}
COVERITY_PASSWORD=${SAST_REPORT_COVERITY_PASSWORD}
GOOGLE_CLIENT_ID=${SAST_REPORT_UPLOAD_GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_REFRESH_TOKEN=${SAST_REPORT_UPLOAD_GOOGLE_CLIENT_REFRESH_TOKEN}
GOOGLE_CLIENT_SECRET=${SAST_REPORT_UPLOAD_GOOGLE_CLIENT_SECRET}
EOF
