#!/bin/bash

set -e

# Write temporary AWS credentials to Silkbomb environment file
# Requires: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN, SILKBOMB_ENV_FILE

cat <<EOF >${SILKBOMB_ENV_FILE}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
EOF
