# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

types:
    string:
        bson_serialization_type: string
        description: "A BSON UTF-8 string"
        cpp_type: "std::string"
        deserializer: "mongo::BSONElement::str"
        is_view: false

structs:
    ErrorReply:
        description: "ErrorReply struct should pass"
        strict: false
        fields:
            errorLabels:
                type: StructType
                stability: stable

    StructType:
        description: "This struct contains a field that is optional in the old
            command and non-optional in the new command."
        fields:
            structField:
                type: string
                optional: true
                stability: stable
