# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

structs:
    ImportedStableNewFieldReply:
        description:
            "This reply contains a field that is unstable in the old command but is
            stable in the new command."
        fields:
            stableNewField:
                type: string
                stability: stable

commands:
    importCommand:
        description: "Defines command in import file."
        command_name: importCommand
        namespace: ignored
        cpp_name: importCommand
        strict: true
        api_version: "1"
        reply_type: OkReply
