# -*- mode: python -*-

Import("env")

env = env.Clone()

env.SConscript(
    must_exist=1,
    dirs=[
        "unicode",
    ],
    exports=[
        "env",
    ],
)

env.CppUnitTest(
    target="db_fts_test",
    source=[],
    LIBDEPS=[],
)
