# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    mod_visibility: private
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/ftdc/ftdc_mongod.h"

imports:
    - "mongo/db/basic_types.idl"

server_parameters:
    diagnosticDataCollectionStatsNamespaces:
        description: "Specifies a comma-separated list of collections to collect metrics on"
        set_at: [startup, runtime]
        cpp_vartype: "synchronized_value<std::vector<std::string>>"
        cpp_varname: "gDiagnosticDataCollectionStatsNamespaces"
        validator:
            callback: validateCollectionStatsNamespaces
        redact: false
