# Copyright (C) 2018-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
  cpp_namespace: "mongo"
  cpp_includes:
    - "mongo/db/ftdc/ftdc_server.h"

imports:
  - "mongo/db/basic_types.idl"

server_parameters:

  diagnosticDataCollectionEnabled:
    description: "Determines whether to enable the collecting and logging of data for diagnostic purposes"
    set_at: [startup, runtime]
    cpp_varname: "ftdcStartupParams.enabled"
    on_update: "onUpdateFTDCEnabled"

  diagnosticDataCollectionPeriodMillis:
    description: "Specifies the interval, in milliseconds, at which to collect diagnostic data."
    set_at: [startup, runtime]
    cpp_varname: "ftdcStartupParams.periodMillis"
    on_update: "onUpdateFTDCPeriod"
    validator:
        gte: 100

  diagnosticDataCollectionDirectorySizeMB:
    description: "Specifies the maximum size, in megabytes, of the diagnostic.data directory"
    set_at: [startup, runtime]
    cpp_varname: "ftdcStartupParams.maxDirectorySizeMB"
    on_update: "onUpdateFTDCDirectorySize"
    validator:
        gte: 10

  diagnosticDataCollectionFileSizeMB:
    description: Specifies the maximum size, in megabytes, of each diagnostic file"
    set_at: [startup, runtime]
    cpp_varname: "ftdcStartupParams.maxFileSizeMB"
    on_update: "onUpdateFTDCFileSize"
    validator:
        gte: 1

  diagnosticDataCollectionSamplesPerChunk:
    description: "Internal, Specifies the number of samples per diagnostic archive chunk"
    set_at: [startup, runtime]
    cpp_varname: "ftdcStartupParams.maxSamplesPerArchiveMetricChunk"
    on_update: "onUpdateFTDCSamplesPerChunk"
    validator:
        gte: 2

  diagnosticDataCollectionSamplesPerInterimUpdate:
    description: "Internal, Specifies the number of samples per diagnostic interim update"
    set_at: [startup, runtime]
    cpp_varname: "ftdcStartupParams.maxSamplesPerInterimMetricChunk"
    on_update: "onUpdateFTDCPerInterimUpdate"
    validator:
        gte: 2

  diagnosticDataCollectionDirectoryPath:
    description: "Specify the directory for the diagnostic data directory."
    set_at: [startup, runtime]
    cpp_class: DiagnosticDataCollectionDirectoryPathServerParameter

  diagnosticDataCollectionEnableLatencyHistograms:
    description: "Enable the capture of opLatencies: { histograms: true } } in FTDC."
    set_at: [startup, runtime]
    cpp_vartype: 'AtomicWord<bool>'
    cpp_varname: gDiagnosticDataCollectionEnableLatencyHistograms

  diagnosticDataCollectionVerboseTCMalloc:
     description: "Enable the capture of verbose tcmalloc in FTDC."
     set_at: [startup, runtime]
     cpp_vartype: 'AtomicWord<bool>'
     cpp_varname: gDiagnosticDataCollectionVerboseTCMalloc
