Import("env")

env = env.Clone()

yamlEnv = env.Clone()
yamlEnv.InjectThirdParty(libraries=["yaml"])

mongobridge = env.BazelProgram(
    target="mongobridge",
    source=[],
    AIB_COMPONENT="dist-test",
)
