# Image used by bazel remote execution hosts.

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y build-essential
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libffi8
RUN apt-get install -y libffi-dev

CMD ["/bin/bash"]
