# Copyright (C) 2020-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.

# This IDL file describes the BSON format for an APIParametersFromClient. 
# It also handles the serialization to / deserialization from its
# BSON representation for that class.

global:
  cpp_namespace: "mongo"

imports:
  - "mongo/db/basic_types.idl"

structs: 

  APIParametersFromClient: 
    description: "Parser for pulling out VersionedAPI parameters from commands"
    strict: false
    fields:
      apiVersion:
        description: "The api version specified by the command" 
        type: string
        optional: true 
      apiStrict: 
        description: "With apiVersion: 'V' and apiStrict: true, the server rejects requests to 
        use behaviors not included in V"
        type: bool 
        optional: true 
      apiDeprecationErrors: 
        description: "With apiVersion: 'V' and apiDeprecationErrors: true, the server rejects
        requests to use behaviors deprecated in V in the current MongoDB release"
        type: bool 
        optional: true

server_parameters:
  requireApiVersion:
    description: "Require clients to pass the 'apiVersion' parameter with all commands"
    test_only: true
    set_at: ["startup", "runtime"]
    cpp_vartype: AtomicWord<bool>
    cpp_varname: gRequireApiVersion
    default: false

  acceptApiVersion2:
    description: "Allow users to issue commands that include apiVersion: \"2\". Test only."
    test_only: true
    set_at: startup
    cpp_vartype: bool
    cpp_varname: acceptApiVersion2
    default: false
