# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# Cluster server parameter for change streams configuration options.

global:
    mod_visibility: private
    cpp_namespace: "mongo"

server_parameters:
    changeStreamOptions:
        description: "Cluster server parameter for change stream options"
        set_at: cluster
        omit_in_ftdc: false
        cpp_class:
            name: ChangeStreamOptionsParameter
            override_set: true
            override_validate: true
        redact: false
