# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: mongo::initialize_server_global_state
    cpp_includes:
        - mongo/logv2/constants.h
    mod_visibility: public

server_parameters:
    maxLogSizeKB:
        cpp_varname: gMaxLogAttributeSizeKB
        cpp_vartype: Atomic<int32_t>
        default:
            expr: logv2::constants::kDefaultMaxAttributeOutputSizeKB
        validator:
            gte: 0
        description: "Max log attribute size in kilobytes"
        set_at: [startup, runtime]
        redact: false

    honorSystemUmask:
        description: "Use the system provided umask, rather than overriding with processUmask config value"
        set_at: startup
        cpp_class: HonorSystemUMaskServerParameter
        condition:
            preprocessor: "!defined(_WIN32)"
        redact: false

    processUmask:
        description: >
            Override system umask for group/other permissions when honorSystemUmask is false.
            User umask is always preserved.
        set_at: startup
        cpp_class: ProcessUMaskServerParameter
        condition:
            preprocessor: "!defined(_WIN32)"
        redact: false

    backtraceLogFile:
        description: >
            File path to log backtraces to if test proctor is enabled.
        set_at: startup
        cpp_varname: gBacktraceLogFile
        cpp_vartype: std::string
        redact: false
