# Copyright (C) 2020-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/util/uuid.h"

imports:
    - "mongo/db/auth/access_checks.idl"
    - "mongo/db/auth/action_type.idl"
    - "mongo/idl/basic_types.idl"

structs:
    ListCollectionsReplyInfo:
        description: "Information about the collection."
        fields:
            readOnly:
                type: bool
                description: "If true, the data store is read only."
                optional: true
                stability: stable
            uuid:
                type: uuid
                description: "Unique, immutable collection ID."
                optional: true
                stability: stable

    ListCollectionsReplyItem:
        description: "Individual result"
        fields:
            name:
                type: string
                description: "Name of the collection."
                stability: stable
            type:
                type: string
                description: "Type of data store."
                stability: stable
            options:
                type: object_owned
                description: "Collection options."
                optional: true
                stability: stable
            info:
                type: ListCollectionsReplyInfo
                description: "Information about the collection."
                optional: true
                stability: stable
            idIndex:
                type: object_owned
                description: "Provides information on the _id index for the collection."
                optional: true
                stability: stable

    ListCollectionsReplyCursor:
        description: "Cursor object"
        fields:
            id: 
                type: long
                stability: stable
            ns: 
                type: namespacestring
                stability: stable
            firstBatch: 
                type: array<ListCollectionsReplyItem>
                stability: stable

    ListCollectionsReply:
        description: "The listCollection command's reply."
        is_command_reply: true
        fields:
            cursor:
                type: ListCollectionsReplyCursor
                stability: stable

commands:
    listCollections:
        description: "Parser for the listCollections command"
        command_name: listCollections
        namespace: ignored
        cpp_name: listCollections
        strict: true
        api_version: "1"
        access_check:
            complex:
                - check: is_authorized_for_any_action_on_resource
                - check: is_authorized_for_any_action_on_any_resource_in_db
                - check: should_ignore_auth_checks
                - check: check_authorized_to_list_collections
                - privilege:
                    resource_pattern: database
                    action_type: listCollections
        fields:
            cursor:
                type: SimpleCursorOptions
                optional: true
                stability: stable
            filter:
                type: object
                optional: true
                stability: stable
            nameOnly:
                type: bool
                default: false
                stability: stable
            authorizedCollections:
                type: bool
                default: false
                stability: stable
            includePendingDrops:
                type: safeBool
                stability: unstable
                optional: true
        reply_type: ListCollectionsReply
