# Copyright (C) 2017 MongoDB Inc.
#
# This program is free software: you can redistribute it and/or  modify
# it under the terms of the GNU Affero General Public License, version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This IDL file describes the BSON format for a LogicalSessionId, and
# handles the serialization to and deserialization from its BSON representation
# for that class.

global:
  cpp_namespace: "mongo"
  cpp_includes:
    - "mongo/util/uuid.h"

imports:
  - "mongo/idl/basic_types.idl"

types:

  UUIDIDL:
    description: "IDL representation of the UUID type"
    bson_serialization_type: object
    cpp_type: "mongo::UUID"
    deserializer: "mongo::UUID::parse"
    serializer: "mongo::UUID::toBSON"

  TxnNumber:
    description: "A strictly-increasing per-session counter, which indicates to which transaction
                  of a given session does the specified command belong. The combination of
                  LogicalSessionId:TxnNumber is referred to as the transaction identifier."
    bson_serialization_type: long
    cpp_type: "std::int64_t"
    deserializer: "mongo::BSONElement::_numberLong"

  StmtId:
    description: "A number representing an operation within a transaction."
    bson_serialization_type: long
    cpp_type: "std::int32_t"
    deserializer: "mongo::BSONElement::_numberLong"

structs:

  logical_session_id:
    description: "A struct representing a LogicalSessionId"
    strict: true
    fields:
      id: UUIDIDL
