# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    mod_visibility: private
    cpp_namespace: "mongo"

feature_flags:
    featureFlagTargetedMirrorReads:
        description: "Enables targeting hosts for read mirroring"
        cpp_varname: gFeatureFlagTargetedMirrorReads
        default: true
        fcv_gated: false
