# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    configs:
        source: [cli, ini]
        initializer:
            register: addMongodLegacyOptions

configs:
    #
    # The following are legacy options that are disallowed in the JSON config file
    #

    # This is a deprecated option that we are supporting for backwards compatibility
    # The first value for this option can be either 'dbpath' or 'run'.
    # If it is 'dbpath', mongod prints the dbpath and exits.  Any extra values are ignored.
    # If it is 'run', mongod runs normally.  Providing extra values is an error.
    command:
        description: Command
        arg_vartype: StringVector
        hidden: true
        positional: 1-3
    cacheSize:
        description: "Cache size (in MB) for rec store"
        arg_vartype: Long
        hidden: true

    #
    # The following are deprecated and unusable options.
    # Specifying them will result in a startup error.
    #

    pairwith:
        description: DEPRECATED
        arg_vartype: Switch
        hidden: true
    arbiter:
        description: DEPRECATED
        arg_vartype: Switch
        hidden: true
    opIdMem:
        description: DEPRECATED
        arg_vartype: Switch
        hidden: true
