# Copyright (C) 2019-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo"
    configs:
        source: [ cli, ini ]
        initializer:
            register: addMongodLegacyOptions

configs:
    #
    # The following are legacy options that are disallowed in the JSON config file	
    #

    # This is a deprecated option that we are supporting for backwards compatibility	
    # The first value for this option can be either 'dbpath' or 'run'.	
    # If it is 'dbpath', mongod prints the dbpath and exits.  Any extra values are ignored.	
    # If it is 'run', mongod runs normally.  Providing extra values is an error.
    command:
        description: Command
        arg_vartype: StringVector
        hidden: true
        positional: 1-3
    cacheSize:
        description: 'Cache size (in MB) for rec store'
        arg_vartype: Long
        hidden: true

    #
    # The following are deprecated and unusable options.
    # Specifying them will result in a startup error.
    #

    pairwith:
        description: DEPRECATED
        arg_vartype: Switch
        hidden: true
    arbiter:
        description: DEPRECATED
        arg_vartype: Switch
        hidden: true
    opIdMem:
        description: DEPRECATED
        arg_vartype: Switch
        hidden: true
 
