# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    mod_visibility: public

server_parameters:
    overdueInterruptCheckIntervalMillis:
        description: >-
            The interval in milliseconds after which an interrupt check is considered overdue.
            Interrupt checks are only tracked for a sample of operations.
        set_at: [startup, runtime]
        cpp_vartype: Atomic<int32_t>
        cpp_varname: gOverdueInterruptCheckIntervalMillis
        default: 30
        validator:
            gte: 10
        redact: false

    overdueInterruptCheckSamplingRate:
        description: >-
            The fraction of operations where time between interrupt checks are tracked.
        set_at: [startup, runtime]
        cpp_vartype: Atomic<double>
        cpp_varname: gOverdueInterruptCheckSamplingRate
        default: 0.001
        validator:
            gte: 0
            lte: 1
        redact: false
