# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0
global:
    cpp_namespace: "mongo"
    mod_visibility: public

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/repl/read_concern_args.idl"
    - "mongo/db/write_concern_options.idl"

enums:
    DefaultWriteConcernSource:
        description: "The source of the default write concern"
        type: string
        values:
            # The default write concern was set implicitly by the server
            kImplicit: "implicit"
            # The default write concern was set globally through setDefaultRWConcern
            kGlobal: "global"
    DefaultReadConcernSource:
        description: "The source of the default read concern"
        type: string
        values:
            # The default read concern was set implicitly by the server.
            kImplicit: "implicit"
            # The default read concern was set globally through setDefaultRWConcern.
            kGlobal: "global"

structs:
    RWConcernDefault:
        description: "Represents a set of read/write concern defaults, and associated metadata"
        strict: false
        fields:
            defaultReadConcern:
                description: "The default read concern"
                type: ReadConcern
                optional: true
            defaultWriteConcern:
                description: "The default write concern"
                type: WriteConcern
                optional: true
            updateOpTime:
                description:
                    "The optime of when the default read or write concern was last set. On
                    replica sets it advances with the primary's optime and on clusters it
                    advances with the config server primary's optime."
                type: timestamp
                optional: true
            updateWallClockTime:
                description:
                    "The wallclock time when the default read or write concern was last set
                    by an administrator. This value is only informational and must not be
                    used for any recency comparisons."
                type: date
                optional: true
            defaultWriteConcernSource:
                description: "The source of the default write concern."
                type: DefaultWriteConcernSource
                optional: true
            defaultReadConcernSource:
                description: "The source of the default read concern"
                type: DefaultReadConcernSource
                optional: true
