# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0
global:
    cpp_namespace: "mongo"
    mod_visibility: public

imports:
    - "mongo/db/basic_types.idl"

enums:
    ReadWriteConcernProvenanceSource:
        description: "Provenance sources"
        type: string
        values:
            clientSupplied: "clientSupplied"
            implicitDefault: "implicitDefault"
            customDefault: "customDefault"
            getLastErrorDefaults: "getLastErrorDefaults"
            internalWriteDefault: "internalWriteDefault"

structs:
    ReadWriteConcernProvenanceBase:
        description: "Represents the 'provenance' (ie. original source) of a read or write concern."
        strict: false
        fields:
            provenance:
                description: "The source for this provenance"
                cpp_name: source
                type: ReadWriteConcernProvenanceSource
                optional: true
