# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

enums:
    SetAtOption:
        mod_visibility: public
        description: "SetAt option value"
        type: string
        values:
            kStartup: "startup"
            kRuntime: "runtime"

# Options for the getParameter command. Describes the object "options" when the command is run as
# {getParameter: <options>}
structs:
    GetParameterOptions:
        mod_visibility: public
        description: "Optional flags to pass to {getParameter: options, ...}"
        fields:
            showDetails:
                description: "Return metadata about the server parameter along with its current value"
                type: safeBool
                default: false
            setAt:
                description: >-
                    Can be set to "runtime" or "startup". If set to "startup", then only startup-settable
                    parameters are returned from the requested ones. If set to "runtime", then only
                    runtime-settable parameters are returned from the requested ones.
                type: SetAtOption
                optional: true
            forIncrementalFeatureRollout:
                description: >-
                    Return only server parameters that can participate in Incremental Feature Rollout (IFR).
                type: safeBool
                default: false
            allParameters:
                description: "Return all server parameters, not just the ones specified"
                type: safeBool
                default: false
