# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    mod_visibility: private
    cpp_namespace: "mongo"

server_parameters:
    throwLoggingEnabled:
        description: "Log the stack when exceptions are thrown. By default, only exceptions not inheriting from mongo::DBException are logged."
        set_at: [startup, runtime]
        cpp_vartype: Atomic<bool>
        cpp_varname: gThrowLoggingEnabled
        default: false
        redact: false
    throwLoggingExceptionName:
        description: "Log the stack when the named exception is thrown. The provided name must match the (platform dependent) name given by std::type_info::name()."
        set_at: [startup, runtime]
        cpp_vartype: synchronized_value<std::string>
        cpp_varname: gThrowLoggingExceptionName
        default: ""
        redact: false
