# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/version_context.h"

imports:
    - "mongo/db/basic_types.idl"

types:
    version_context:
        bson_serialization_type: object
        description: "Holds metadata related to snapshots of the system state taken by OFCV-aware operations."
        cpp_type: "mongo::VersionContext"
        serializer: "mongo::VersionContext::toBSON"
        deserializer: "mongo::VersionContext"
        is_view: false
