# Copyright (C) 2025-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo"

feature_flags:
    # TODO (SERVER-110309): remove this feature flag
    featureFlagReplicateOFCVInOplog:
        description: >
            Enabled when all binaries support replicating the OFCV (versionContext) in the oplog.
            Snapshotting of OFCV for sharded operations is controlled by featureFlagSnapshotFCVInDDLCoordinators.

            (Enable on transitional FCV): Necessary to ensure that operations using OFCV have a
            stable view of all feature flags with a version greater or equal than this feature flag.
            See SERVER-102084 for more detail.
            If this feature flag is disabled by a FCV downgrade, all operations with an operation FCV
            are drained when finalizing the downgrade.
        cpp_varname: feature_flags::gReplicateOFCVInOplog
        default: true
        version: 8.2
        fcv_gated: true
        enable_on_transitional_fcv_UNSAFE: true

    # TODO (SERVER-110309): remove this feature flag
    featureFlagStrictlyEnforceOperationFCVOnlyFCVGatedFeatureFlags:
        description: >
            Enforce feature flags tagged with `check_against_fcv: operation_fcv_only` are checked with an OFCV.
            This can not be done until FCV 8.2 since ShardingDDLCoordinators (or their sub-commands)
            do not have an OFCV in FCV 8.0 (see featureFlagSnapshotFCVInDDLCoordinators).
        cpp_varname: feature_flags::gStrictlyEnforceOperationFCVOnlyFCVGatedFeatureFlags
        default: true
        version: 8.2
        fcv_gated: true
