# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/util/exception_filter_win32.h"
    configs:
        section: "Windows Service Control Manager options"
        source: [yaml, cli, ini]

configs:
    install:
        description: "Install Windows service"
        arg_vartype: Switch
        source: [cli, ini]
    remove:
        description: "Remove Windows service"
        arg_vartype: Switch
        source: [cli, ini]
    reinstall:
        description: "Reinstall Windows service (equivalent to --remove followed by --install)"
        arg_vartype: Switch
        source: [cli, ini]
    service:
        description: "Start mongodb service"
        arg_vartype: Switch
        source: [cli, ini]
        hidden: true

    "processManagement.windowsService.serviceName":
        description: "Windows service name"
        short_name: serviceName
        arg_vartype: String
    "processManagement.windowsService.displayName":
        description: "Windows service display name"
        short_name: serviceDisplayName
        arg_vartype: String
    "processManagement.windowsService.description":
        description: "Windows service description"
        short_name: serviceDescription
        arg_vartype: String
    "processManagement.windowsService.serviceUser":
        description: "Account for service execution"
        short_name: serviceUser
        arg_vartype: String
    "processManagement.windowsService.servicePassword":
        description: "Password used to authenticate serviceUser"
        short_name: servicePassword
        arg_vartype: String
        redact: true

server_parameters:
    win32MinidumpEnabled:
        description: "Enables or disables Windows minidump generation. This should be used to disable minidumps for testing recovery behavior."
        set_at: ["startup", "runtime"]
        cpp_vartype: Atomic<bool>
        cpp_varname: gWin32MinidumpEnabled
        default: true
        test_only: true
        redact: false
        on_update: onUpdateWin32MinidumpEnabled
