# -*- mode: python -*-

Import("env")

env.Command(['error_codes.h', 'error_codes.cpp'], ['generate_error_codes.py', 'error_codes.err'],
            '$PYTHON $SOURCES $TARGETS')

env.Library('base',
            ['error_codes.cpp',
             'global_initializer.cpp',
             'global_initializer_registerer.cpp',
             'init.cpp',
             'initializer.cpp',
             'initializer_context.cpp',
             'initializer_dependency_graph.cpp',
             'validate_locale.cpp',
             'make_string_vector.cpp',
             'parse_number.cpp',
             'status.cpp',
             'string_data.cpp',
            ],
            LIBDEPS=['$BUILD_DIR/mongo/quick_exit',
                     '$BUILD_DIR/third_party/murmurhash3/murmurhash3',
            ])

env.CppUnitTest('base_test',
                ['initializer_dependency_graph_test.cpp',
                 'initializer_test.cpp',
                 'owned_pointer_vector_test.cpp',
                 'owned_pointer_map_test.cpp',
                 'parse_number_test.cpp',
                 'status_test.cpp',
                 'encoded_value_storage_test.cpp',
                 'data_view_test.cpp',
                 'data_cursor_test.cpp',
                 'counter_test.cpp',
                 'string_data_test.cpp'
                ])
