// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#pragma once

#include "mongo/db/hasher.h"
#include "mongo/db/matcher/expression_leaf.h"
#include "mongo/util/modules.h"

#include <string_view>

namespace mongo {
using namespace std::literals::string_view_literals;

/**
 * An internal match expression node which represents a field path's hash being equal to the given
 * NumberLong constant. This expression is not intended to be written directly by users, but rather
 * generated by a rewrite of {$expr: {$eq: [{$toHashedIndexKey: '$fieldPath'}, NumberLong(123)]}}.
 * The purpose of this is to allow us to generate index bounds on a hashed index to satisfy such a
 * query.
 */
class InternalEqHashedKey : public ComparisonMatchExpressionBase {
public:
    static constexpr std::string_view kName = "$_internalEqHash"sv;

    InternalEqHashedKey(boost::optional<std::string_view> path, long long hashVal)
        : ComparisonMatchExpressionBase(MatchType::INTERNAL_EQ_HASHED_KEY,
                                        path,
                                        Value(hashVal),
                                        // Match the agg expression semantics for traversals.
                                        ElementPath::LeafArrayBehavior::kNoTraversal,
                                        ElementPath::NonLeafArrayBehavior::kMatchSubpath) {}

    InternalEqHashedKey(std::string path, long long hashVal)
        : InternalEqHashedKey(boost::optional<std::string_view>(path), hashVal) {}

    InternalEqHashedKey(boost::optional<std::string_view> path, BSONElement value)
        // Checking the type should happen earlier during parsing.
        : InternalEqHashedKey(path, value.numberLong()) {}

    std::unique_ptr<MatchExpression> clone() const final {
        auto clone = std::make_unique<InternalEqHashedKey>(path(), _rhs);
        clone->setCollator(_collator);
        if (getTag()) {
            clone->setTag(getTag()->clone());
        }
        return clone;
    }

    std::string_view name() const final {
        return kName;
    }

    void acceptVisitor(MatchExpressionMutableVisitor* visitor) final {
        visitor->visit(this);
    }

    void acceptVisitor(MatchExpressionConstVisitor* visitor) const final {
        visitor->visit(this);
    }

    void appendSerializedRightHandSide(BSONObjBuilder* bob,
                                       const query_shape::SerializationOptions& opts = {},
                                       bool includePath = true) const final {
        opts.appendLiteral(bob, name(), _rhs, Value((long long)1));
    }
};

}  // namespace mongo
