// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#pragma once

#include "mongo/db/matcher/expression.h"
#include "mongo/db/matcher/expression_text_base.h"
#include "mongo/db/matcher/expression_where_base.h"
#include "mongo/db/matcher/extensions_callback.h"
#include "mongo/db/namespace_string.h"
#include "mongo/db/operation_context.h"
#include "mongo/db/pipeline/expression_context.h"
#include "mongo/util/modules.h"

#include <memory>

#include <boost/smart_ptr/intrusive_ptr.hpp>

namespace mongo {
class NamespaceString;
class OperationContext;

/**
 * ExtensionsCallbackReal uses the provided OperationContext and namespace to capture context
 * necessary for parsing $text and $where clauses.
 */
class [[MONGO_MOD_PUBLIC]] ExtensionsCallbackReal : public ExtensionsCallback {
public:
    /**
     * Does not take ownership of 'nss' or 'opCtx'.
     *
     * 'nss' must outlive this object. 'opCtx' must outlive this object also; in addition, 'opCtx'
     * must outlive any MatchExpression objects generated by these callbacks (as the generated
     * objects are allowed to keep a reference to 'opCtx').
     */
    ExtensionsCallbackReal(OperationContext* opCtx, const NamespaceString* nss);

    ~ExtensionsCallbackReal() override {};

    std::unique_ptr<MatchExpression> createText(
        TextMatchExpressionBase::TextParams text) const final;

    std::unique_ptr<MatchExpression> createWhere(
        const boost::intrusive_ptr<ExpressionContext>& expCtx,
        WhereMatchExpressionBase::WhereParams where) const final;

private:
    OperationContext* const _opCtx;
    const NamespaceString* const _nss;
};

}  // namespace mongo
