# Image used by bazel remote execution hosts.

FROM debian:10

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    libfl2 \
    libxml2-dev \
    libssl-dev

CMD ["/bin/bash"]
