# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# Replication IDL File

global:
    cpp_namespace: "mongo::repl"
    mod_visibility: public
    cpp_includes:
        - "mongo/db/repl/optime.h"

imports:
    - "mongo/db/basic_types.idl"

types:
    optime:
        bson_serialization_type: any
        description: A document representing an OpTime.
        cpp_type: "OpTime"
        serializer: OpTime::append
        deserializer: OpTime::parse
        # OpTime has only non view members.
        is_view: false
