# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    mod_visibility: private

server_parameters:
    createRollbackDataFiles:
        description: >-
            Control whether or not the server will write out data files containing deleted documents during
            rollback, and data files containing rolled back oplog entries. This server parameter affects 
            rollback via recovery to stable timestamp.
        set_at: [startup, runtime]
        cpp_vartype: Atomic<bool>
        cpp_varname: gCreateRollbackDataFiles
        default: true
        redact: false

    rollbackTimeLimitSecs:
        description: >-
            This amount, measured in seconds, represents the maximum allowed rollback period.
            It is calculated by taking the difference of the wall clock times of the oplog entries
            at the top of the local oplog and the first oplog entry after the common point.
        set_at: [startup, runtime]
        cpp_vartype: Atomic<int>
        cpp_varname: gRollbackTimeLimitSecs
        default:
            expr: "60 * 60 * 24" # Default 1 day
        validator:
            gt: 0
        redact: false
