# -*- mode: python -*-

Import("env")
Import("wiredtiger")

env = env.Clone()

env.Benchmark(
    target="oplog_entry_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="repl_bm",
)

if wiredtiger:
    env.CppUnitTest(
        target="db_repl_idempotency_test",
        source=[],
        LIBDEPS=[],
    )

    env.CppUnitTest(
        target="db_repl_misc_test",
        source=[],
        LIBDEPS=[],
    )

env.CppUnitTest(
    target="db_repl_coordinator_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="oplog_application_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="rollback_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="initial_syncer_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="storage_timestamp_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="repl_set_config_and_heartbeat_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="replication_recovery_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="storage_interface_impl_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="topology_version_observer_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="db_repl_cloners_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="db_repl_set_aware_service_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="oplog_application_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="repl_bm",
)

env.Benchmark(
    target="oplog_applier_utils_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="repl_bm",
)

env.Benchmark(
    target="replication_consistency_markers_impl_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="repl_bm",
)

env.Benchmark(
    target="oplog_write_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="repl_bm",
)

env.Benchmark(
    target="replication_waiter_list_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="repl_bm",
)
