# Copyright (C) 2021-present MongoDB, Inc.  All Rights Reserved.

# voteCommitImportCollection IDL File.

global:
  cpp_namespace: "mongo::repl"

imports:
  - "mongo/idl/basic_types.idl"
  - "mongo/util/net/hostandport.idl"

enums:
  MigrationProgressStep:
    description: "Which step the recipient shard's nodes are doing together."
    type: string
    values:
      kNoStep: "no step"
      kCopiedFiles: "copied files"
      kImportedFiles: "imported files"

commands:
  voteCommitMigrationProgress:
    command_name: voteCommitMigrationProgress
    cpp_name: VoteCommitMigrationProgress
    description: "An internal mongod command to coordinate recipient steps of a multitenant
                  migration"
    strict: true
    namespace: ignored
    api_version: ""
    reply_type: OkReply
    fields:
      migrationId:
        description: "Unique identifier for the tenant migration."
        type: uuid
      from:
        type: HostAndPort
        description: "Replica set member identification"
      step:
        type: MigrationProgressStep
        description: "Which step the recipient shard's nodes are doing together."
      success:
        type: safeBool
        description: "Whether the calling node succeeded at doing the step."
      reason:
        type: string
        optional: true
        description: "Optional failure reason string"
