# Copyright (C) 2020-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/pipeline/aggregation_request_helper.h"
        - "mongo/db/query/count_request.h"
        - "mongo/db/query/explain_options.h"

imports:
    - "mongo/crypto/fle_field_schema.idl"
    - "mongo/db/auth/action_type.idl"
    - "mongo/db/auth/access_checks.idl"
    - "mongo/db/basic_types.idl"
    - "mongo/db/pipeline/exchange_spec.idl"
    - "mongo/db/pipeline/external_data_source_option.idl"
    - "mongo/db/pipeline/legacy_runtime_constants.idl"
    - "mongo/db/query/hint.idl"
    - "mongo/db/query/cursor_response.idl"
    - "mongo/db/write_concern_options.idl"

types:
    pipeline:
        bson_serialization_type: any
        description: "An array of objects specifying the aggregation pipeline."
        cpp_type: "std::vector<mongo::BSONObj>"
        deserializer: ::mongo::parsePipelineFromBSON
    aggregateCursor:
        bson_serialization_type: any
        description: "A cursor type representing the cursor field of aggregate command."
        cpp_type: SimpleCursorOptions
        serializer: ::mongo::serializeAggregateCursorToBSON
        deserializer: ::mongo::parseAggregateCursorFromBSON
    explainVerbosity:
        bson_serialization_type: any
        description: "The Verbosity value representing explain verbosity."
        cpp_type: "mongo::ExplainOptions::Verbosity"
        serializer: ::mongo::serializeExplainToBSON
        deserializer: ::mongo::parseExplainModeFromBSON

structs:
    PassthroughToShardOptions:
        description: "options for commands requesting a per shard cursor"
        fields:
            shard:
                description: "id of the shard to passthrough to"
                type: string
                stability: unstable

commands:
    aggregate:
        description: "Represents the user-supplied options to the aggregate command."
        cpp_name: AggregateCommandRequest
        command_name: aggregate
        strict: true
        namespace: concatenate_with_db
        allow_global_collection_name: true
        api_version: "1"
        access_check:
            complex:
                - check: check_cursor_session_privilege
                - check: is_coauthorized_with_client
                - check: is_coauthorized_with
                - check: should_ignore_auth_checks
                - check: get_authenticated_user
                - check: lookup_user
                - privilege: # many commands
                    resource_pattern: exact_namespace
                    action_type: [find, insert, update, remove]
                - privilege: # $planCacheStats
                    resource_pattern: exact_namespace
                    action_type: planCacheRead
                - privilege: # $telemetry
                    agg_stage: telemetry
                    resource_pattern: cluster
                    action_type: telemetryRead
                - privilege: # $changeStream
                    resource_pattern: exact_namespace
                    action_type: changeStream
                - privilege: # $changeStream
                    resource_pattern: database
                    action_type: changeStream
                - privilege: # $changeStream
                    resource_pattern: any_normal
                    action_type: changeStream
                - privilege: # $changeStream
                    resource_pattern: database
                    action_type: find
                - privilege: # $changeStream
                    resource_pattern: any_normal
                    action_type: find
                - privilege: # $changeStream
                    resource_pattern: cluster
                    action_type: internal
                - privilege: # $collstats
                    resource_pattern: exact_namespace
                    action_type: collStats
                - privilege: # $currentOp
                    resource_pattern: cluster
                    action_type: inprog
                - privilege: # $indexStats
                    resource_pattern: exact_namespace
                    action_type: indexStats
                - privilege: # $listCachedAndActiveUsers
                    resource_pattern: any_normal
                    action_type: listCachedAndActiveUsers
                - privilege: # $listCatalog
                    agg_stage: listCatalog
                    resource_pattern: exact_namespace
                    action_type: [listCollections, listIndexes]
                - privilege: # $listCatalog
                    agg_stage: listCatalog
                    resource_pattern: cluster
                    action_type: listDatabases
                - privilege: # $listCatalog
                    agg_stage: listCatalog
                    resource_pattern: any_normal
                    action_type: [listCollections, listIndexes]
                - privilege: # $listCatalog
                    agg_stage: listCatalog
                    resource_pattern: collection
                    action_type: [listCollections, listIndexes]
                - privilege: # $listCatalog
                    agg_stage: listCatalog
                    resource_pattern: any_system_buckets
                    action_type: [listCollections, listIndexes]
                - privilege: # $listSessions
                    resource_pattern: cluster
                    action_type: listSessions
                - privilege: # various
                    resource_pattern: exact_namespace
                    action_type: bypassDocumentValidation
                - privilege: # $operationMetrics
                    resource_pattern: cluster
                    action_type: operationMetrics
                - privilege: # $backupCursorExtend, backupCursor
                    resource_pattern: cluster
                    action_type: fsync
                - privilege: # $_internalAllCollectionStats
                     agg_stage: _internalAllCollectionStats
                     resource_pattern: cluster
                     action_type: allCollectionStats
                - privilege: # $shardedDataDistribution
                     agg_stage: shardedDataDistribution
                     resource_pattern: cluster
                     action_type: shardedDataDistribution
                - privilege: # $_analyzeShardKeyReadWriteDistribution
                     agg_stage: _analyzeShardKeyReadWriteDistribution
                     resource_pattern: exact_namespace
                     action_type: analyzeShardKey
        # Note that the 'CursorInitialReply' is not the only response that an aggregate command
        # could return. With 'explain' or 'exchange', the response would not include the fields in
        # 'CursorInitialReply'. But using 'explain' or 'exchange' is unstable, but otherwise the
        # aggregate response is guaranteed to be stable.
        reply_type: CursorInitialReply
        fields:
            pipeline:
                description: "An unparsed version of the pipeline."
                type: pipeline
                stability: stable
            explain:
                description: "Specifies to return the information on the processing of the pipeline."
                type: explainVerbosity
                optional: true
                stability: unstable
            allowDiskUse:
                description: "Enables writing to temporary files."
                type: optionalBool
                stability: stable
            cursor:
                description: "To indicate a cursor with a non-default batch size."
                type: aggregateCursor
                default: SimpleCursorOptions()
                stability: stable
            maxTimeMS:
                description: "Specifies a time limit in milliseconds for processing operations on a cursor. If you do not specify a value for maxTimeMS, operations will not time out."
                type: safeInt64
                validator: { gte: 0 }
                optional: true
                stability: stable
            bypassDocumentValidation:
                description: "True if this should bypass the document validation."
                type: safeBool
                optional: true
                stability: stable
            readConcern:
                description: "Specifies the read concern."
                type: object_owned
                optional: true
                stability: stable
            collation:
                description: "Specifies the collation to use for the operation."
                type: object_owned
                optional: true
                stability: stable
            hint:
                description: "The index name to use or the index specification document."
                type: indexHint
                optional: true
                stability: stable
            writeConcern:
                description: "A document that expresses the write concern to use with the $out or $merge stage."
                type: WriteConcern
                optional: true
                stability: stable
            let:
                description: "A document containing user-specified let parameter constants; i.e. values that do not change once computed."
                type: object_owned
                optional: true
                stability: stable
            needsMerge:
                description: "True if this request represents the shards part of a split pipeline, and should produce mergeable output."
                type: optionalBool
                stability: internal
            fromMongos:
                description: "True if this request originated from a mongoS."
                type: optionalBool
                stability: internal
            $queryOptions:
                description: "The unwrapped readPreference object, if one was given to us by the mongos command processor. This object will be empty when no readPreference is specified or if the request does not originate from mongos."
                cpp_name: unwrappedReadPref
                type: object_owned
                optional: true
                stability: unstable
            $_requestReshardingResumeToken:
                description: "True if this requests resharding resume token."
                cpp_name: requestReshardingResumeToken
                type: optionalBool
                stability: unstable
            exchange:
                description: "An optional exchange specification for this request. If set it means that the request represents a producer running as a part of the exchange machinery. This is an internal option; we do not expect it to be set on requests from users or drivers."
                type: ExchangeSpec
                optional: true
                stability: stable
            runtimeConstants:
                description: "A legacy way to specify constant variables available during execution. 'let' is now preferred."
                type: LegacyRuntimeConstants
                cpp_name: legacyRuntimeConstants
                optional: true
                stability: unstable
            isMapReduceCommand:
                description: "True if an aggregation was invoked by the MapReduce command."
                type: optionalBool
                stability: unstable
            collectionUUID:
                description: "The expected UUID of the namespace the aggregation executes on."
                type: uuid
                optional: true
                stability: unstable
            $_passthroughToShard:
                description: "An optional internal parameter for this request. If a shard key is specified, then that specific shard will be targeted."
                type: PassthroughToShardOptions
                cpp_name: passthroughToShard
                optional: true
                stability: unstable
            # TODO SERVER-65369: $_generateV2ResumeTokens can be removed after 7.0.
            $_generateV2ResumeTokens:
                description: "Internal parameter to signal whether v2 resume tokens should be generated."
                type: optionalBool
                cpp_name: generateV2ResumeTokens
                stability: internal
            encryptionInformation:
                description: "Encryption Information schema and other tokens for CRUD commands"
                type: EncryptionInformation
                optional: true
                stability: unstable
            $_externalDataSources:
                description: "Specification for external data sources."
                type: array<ExternalDataSourceOption>
                cpp_name: externalDataSources
                optional: true
                stability: unstable
            sampleId:
                description: "The unique sample id for the operation if it has been chosen for sampling."
                type: uuid
                optional: true
                stability: unstable
            stmtId:
                description: "The statement id of the write in the original write batch for a write
                              without shard key."
                type: int
                optional: true
                stability: internal
            $_isClusterQueryWithoutShardKeyCmd:
                description: "True if a _clusterQueryWithoutShardKey command is running a broadcast 
                              aggregate."
                type: optionalBool
                cpp_name: isClusterQueryWithoutShardKeyCmd
                stability: internal
            
