# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# ChangeStreamPreAndPostImages options IDL file.

global:
    cpp_namespace: "mongo"
    mod_visibility: needs_replacement

imports:
    - "mongo/db/basic_types.idl"

structs:
    ChangeStreamPreAndPostImagesOptions:
        description: "A type representing the adjustable options of a collection with change stream point-in-time pre- and post-images."
        strict: true
        generate_comparison_operators: true
        fields:
            enabled:
                description: "Determines whether point-in-time pre- and post-images are available for change streams."
                type: bool
                optional: false
                stability: stable
