// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#pragma once

#include "mongo/db/exec/document_value/document.h"

namespace mongo::change_stream {

/**
 * A collection of hashed field names that are frequently used for change stream processing.
 * Pre-hashing the field names and using the hashes during lookups has a performance advantage over
 * re-computing the hashes on every field lookup. This is only a struct to group the hashed field
 * names together.
 */
struct HashedFieldAccessors {
    // Hashed field names of frequently accessed fields in oplog entries, to avoid repeated hashing
    // when accessing these fields. The referred-to field names are all defined as constexpr
    // StringData.
    static const HashedFieldName kOpType;
    static const HashedFieldName kTimestamp;
    static const HashedFieldName kNss;
    static const HashedFieldName kUuid;
    static const HashedFieldName kObject;
    static const HashedFieldName kObject2;
    static const HashedFieldName kWallClockTime;
    static const HashedFieldName kFromMigrate;

    // The following are only present in oplog entries for transaction operations and are generated
    // by the unwind transactions stage. The referred-to field names are all defined as constexpr
    // StringData.
    static const HashedFieldName kTxnOpIndex;
    static const HashedFieldName kLsid;
    static const HashedFieldName kTxnNumber;
    static const HashedFieldName kCommitTimestamp;
    static const HashedFieldName kApplyOpsIndex;
    static const HashedFieldName kApplyOpsEntryTs;

    // Field names that are generated by the change stream transformation and that are used by
    // following pipeline stages. The referred-to field names are all defined as constexpr
    // StringData.
    static const HashedFieldName kOperationType;
    static const HashedFieldName kDocumentKey;
    static const HashedFieldName kNamespace;
    static const HashedFieldName kPreImageId;
    static const HashedFieldName kPreImage;
};

}  // namespace mongo::change_stream
