# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# Pre-image IDL file.

global:
    cpp_namespace: "mongo"
    mod_visibility: needs_replacement

imports:
    - "mongo/db/basic_types.idl"

server_parameters:
    disableExpiredPreImagesRemover:
        description: Disables the expired pre-images remover.
        set_at: [startup]
        cpp_vartype: bool
        cpp_varname: gPreImageRemoverDisabled
        default: false
        test_only: true
        redact: false

    expiredChangeStreamPreImageRemovalJobSleepSecs:
        description: >-
            Specifies the period within which expired pre-image removal job is running.
        set_at: [startup]
        cpp_vartype: Atomic<int>
        cpp_varname: gExpiredChangeStreamPreImageRemovalJobSleepSecs
        validator:
            gte: 1
        default: 10
        redact: false

    preImagesCollectionTruncateMarkersMinBytes:
        description: >-
            Server parameter that specifies the minimum number of bytes contained in each
            truncate marker.
        set_at: startup
        cpp_varname: gPreImagesCollectionTruncateMarkersMinBytes
        cpp_vartype: int32_t
        default: 33_554_432 # 32 MiB
        validator:
            gt: 0
        redact: false

    changeStreamPreImagesSamplePointsPerUUID:
        # Sampling of the pre-images collection happens in two scenarios:
        # - On ASC, the sampling happens on all replica set nodes as part of the node's
        #   onConsistentDataAvailable callback. Sampling should be very infrequent.
        # - On DSC, the sampling happens every time a node steps up as a primary. Only the
        #   current primary will perform the sampling, but it can occur multiple times
        #   during the lifetime of a node.
        description: >-
            Defines the maximum number of sample points to draw from each user collection that
            has change stream pre- and post-images enabled. The value of this parameter can affect
            the accuracy of the sampling and how frequent pre-image removal occurs. It can also
            affect number of I/O operations needed for pre-images sampling.
        set_at: [startup, runtime]
        cpp_varname: "gChangeStreamPreImagesSamplePointsPerUUID"
        cpp_vartype: Atomic<int>
        default: 10
        validator:
            gte: 1
            lte: 100
        redact: false

structs:
    ChangeStreamPreImageId:
        description: Uniquely identifies a pre-image for a given node or replica set.
        fields:
            nsUUID:
                description: UUID of the collection the pre-image of a document is from.
                type: uuid
            ts:
                description: Timestamp of an oplog entry associated with this document.
                type: timestamp
            applyOpsIndex:
                description:
                    Index of an operation in an applyOps entry of a transaction.
                    0 if the operation is not in a transaction or is the first operation in a transaction.
                type: safeInt64
                validator: {gte: 0}
    ChangeStreamPreImage:
        description: A version of a document just before replace, update, or delete operation.
        fields:
            _id:
                cpp_name: id
                type: ChangeStreamPreImageId
            operationTime:
                description:
                    Operation execution wall clock time. Used to determine if the
                    pre-image expired.
                type: date
            preImage:
                description: Pre-image of a document for an operation recorded to an oplog entry.
                type: object
