# Copyright (C) 2018-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

# Document source change stream stage IDL file

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/pipeline/resume_token.h"

imports:
    - "mongo/db/basic_types.idl"

types:
    # A resume token is an opaque document we return to the user that contains all the information
    # needed to resume a stream where they left off.  It also provides the ordering of streams
    # from multiple shards.
    resumeToken:
        bson_serialization_type: object
        description: An object representing a resume token for a change stream
        cpp_type: ResumeToken
        serializer: ResumeToken::toBSON
        deserializer: ResumeToken::parse

enums:
    FullDocumentBeforeChangeMode:
        description: Possible modes for the 'fullDocumentBeforeChange' parameter of the
                     $changeStream stage.
        type: string
        values:
            # Do not supply pre-images.
            kOff: "off"
            # Supply a pre-image if available. Otherwise, return null.
            kWhenAvailable: "whenAvailable"
            # Pre-images are required.Throw an exception if not available.
            kRequired: "required"

    FullDocumentMode:
        description: Possible modes for the 'fullDocument' parameter of the $changeStream stage.
        type: string
        values:
            # Post-images will only be populated for insert and replace events.
            kDefault: "default"
            # The current version of the document will be retrieved for update events.
            kUpdateLookup: "updateLookup"
            # Supply a post-image if available. Otherwise, return null.
            kWhenAvailable: "whenAvailable"
            # Post-images are required. Throw an exception if not available.
            kRequired: "required"

structs:
    ResumeTokenClusterTime:
        description: The IDL type of cluster time
        fields:
            ts:
                cpp_name: timestamp
                type: timestamp
                description: The timestamp of the logical time

    DocumentSourceChangeStreamSpec:
        description: A document used to specify the $changeStream stage of an aggregation
                     pipeline. The same spec is also used by the $_internalChangeStreamTransform
                     stage.
        fields:
            resumeAfter:
                cpp_name: resumeAfter
                type: resumeToken
                optional: true
                description: An object representing the point at which we should resume reporting
                             changes from. Only one of resumeAfter, startAfter, and
                             startAtOperationTime should be specified.

            startAfter:
                cpp_name: startAfter
                type: resumeToken
                optional: true
                description: An object representing the point at which we should start reporting
                             changes from. This is allowed to be a token from an invalidating
                             command. Only one of resumeAfter, startAfter, and startAtOperationTime
                             should be specified.

            startAtOperationTime:
                cpp_name: startAtOperationTime
                type: timestamp
                optional: true
                description: The operation time after which we should start reporting changes.
                             Only one of resumeAfter, startAfter, and startAtOperationTime should
                             be specified.

            fullDocument:
                cpp_name: fullDocument
                type: FullDocumentMode
                default: kDefault
                description: A string '"updateLookup"' or '"default"', indicating whether or not we
                             should return a full document or just changes for an update.

            fullDocumentBeforeChange:
                cpp_name: fullDocumentBeforeChange
                type: FullDocumentBeforeChangeMode
                default: kOff
                description: Valid values are "off", "whenAvailable", or "required". If set to
                             "off", the "fullDocumentBeforeChange" field of the output document
                             is always omitted. If set to "whenAvailable", the
                             "fullDocumentBeforeChange" field will be populated with the
                             pre-image of the document modified by the current change event if
                             such a pre-image is available, and will be omitted otherwise. If
                             set to "required", then the "fullDocumentBeforeChange" field is
                             always populated and an exception is thrown if the pre-image is not
                             available.

            allChangesForCluster:
                cpp_name: allChangesForCluster
                type: optionalBool
                description: A flag indicating whether the stream should report all changes that
                             occur on the deployment, aside from those on internal databases or
                             collections.

            showMigrationEvents:
                cpp_name: showMigrationEvents
                type: optionalBool
                description: A flag indicating whether the stream should report changes that occur
                             on the deployment that are related to chunk migrations. These
                             operations are reported like normal events. For example, inserts and
                             deletes may appear that do not reflect actual deletions or insertions
                             of data. Instead they reflect this data moving from one shard to
                             another.

            showSystemEvents:
                cpp_name: showSystemEvents
                type: optionalBool
                description: A flag indicating whether the stream should report events on system
                             collections.

            allowToRunOnConfigDB:
                cpp_name: allowToRunOnConfigDB
                type: optionalBool
                description: A flag indicating whether the change stream may be opened on the
                             'config' database, which is usually banned. This flag is used
                             internally to allow mongoS to open a stream on 'config.shards', in
                             order to monitor for the addition of new shards to the cluster.

            allowToRunOnSystemNS:
                cpp_name: allowToRunOnSystemNS
                type: optionalBool
                description: An internal flag indicating whether the change stream may be opened on
                             a system collection.

            showExpandedEvents:
                type: optionalBool
                description: A flag indicating whether the change stream output should include the
                             expanded events and parameters that may not be part of the stable API.

            showRawUpdateDescription:
                cpp_name: showRawUpdateDescription
                type: optionalBool
                description: An internal flag indicating whether each update event in a change
                             stream should contain a "rawUpdateDescription" field that exposes the
                             raw update description from the oplog entry for the corresponding
                             update command. When this flag is set to true, the standard
                             "updateDescription" field in update events will be omitted.

    DocumentSourceChangeStreamOplogMatchSpec:
        strict: true
        description: A document used to specify the $_internalChangeStreamOplogMatch stage of an
                     aggregation pipeline.
        fields:
            filter: object_owned

    DocumentSourceChangeStreamUnwindTransactionSpec:
        strict: true
        description: A document used to specify the $_internalChangeStreamUnwindTransaction stage of
                     an aggregation pipeline.
        fields:
            filter: object_owned

    DocumentSourceChangeStreamCheckInvalidateSpec:
        strict: true
        description: A document used to specify the $_internalChangeStreamCheckInvalidate stage of
                     an aggregation pipeline.
        fields:
            startAfterInvalidate:
                type: resumeToken
                optional: true
    
    DocumentSourceChangeStreamCheckResumabilitySpec:
        strict: true
        description: A document used to specify the $_internalChangeStreamCheckResumability stage of
                     an aggregation pipeline.
        fields:
            resumeToken:
                type: resumeToken
                optional: false

    DocumentSourceChangeStreamAddPreImageSpec:
        strict: true
        description: A document used to specify the $_internalChangeStreamAddPreImage stage of
                     an aggregation pipeline.
        fields:
            fullDocumentBeforeChange:
                type: FullDocumentBeforeChangeMode

    DocumentSourceChangeStreamAddPostImageSpec:
        strict: true
        description: A document used to specify the $_internalChangeStreamAddPostImage stage of
                     an aggregation pipeline.
        fields:
            fullDocument:
                type: FullDocumentMode
