# Copyright (C) 2025-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/pipeline/aggregate_command.idl"

structs:
    DocumentSourceLookupSpec:
        description: Specification for a $lookup stage.
        strict: true
        fields:
            pipeline:
                description: The pipeline to run on the foreign collection
                type: pipeline
                optional: true
            let:
                description: The variables to use in the pipeline stages
                cpp_name: letVars
                type: object
                optional: true
            $_internalUnwind:
                description: Internal use only. Used when an unwind is coalesced into a lookup.
                cpp_name: unwindSpec
                type: object
                optional: true
            from:
                description: The foreign collection to join into the local collection for the aggregation
                type: IDLAnyType
                optional: true
            as:
                description: The name of the new array field to add to the input documents
                type: string
            localField:
                description: The local field to use when joining the foreign collection
                type: string
                optional: true
            foreignField:
                description: The foreign field used to perform equality match with localField
                type: string
                optional: true
            # When a hybrid search stage is de-sugared, then serialized into sub-pipeline BSON to be sent
            # across the wire (i.e. from mongos to mongod), its unclear from inspecting the BSON that the
            # original query was a hybrid search, so this internal field preserves that information.
            $_internalIsHybridSearch:
                description: An optional internal field specifying if the subpipeline is a hybrid search.
                type: optionalBool
                stability: internal
                cpp_name: isHybridSearch
