# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    mod_visibility: private
    cpp_namespace: mongo::analyze_shard_key

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/s/analyze_shard_key_documents.idl"

structs:
    DocumentSourceListSampledQueriesSpec:
        description: Specification for a $listSampledQueries stage.
        strict: false
        query_shape_component: true
        fields:
            namespace:
                description:
                    The namespace to return sampled queries for. If unspecified,
                    all sampled queries will be returned.
                type: namespacestring
                optional: true
                query_shape: custom

    DocumentSourceListSampledQueriesResponse:
        description: The document that a $listSampledQueries stage outputs.
        strict: false
        inline_chained_structs: true
        chained_structs:
            SampledQueryDocument: sampledQueryDocument
