# Copyright (C) 2023-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#
global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/pipeline/document_source_query_stats_validators.h"
imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/query/query_stats/transform_algorithm.idl"

structs:
    TransformIdentifiersSpec:
        description: "Specification for the transformIdentifiers field of $queryStats."
        strict: true
        fields:
            algorithm:
                description: "The algorithm to use to transform the identifiers."
                type: TransformAlgorithm
                optional: false
                validator: {callback: "validateAlgo"}
            hmacKey:
                description: >
                    The hmac key to be used to transform the identifiers. This is considered sensitive
                    data and should be redacted from data dumps, output I/O, logs, and other persistent
                    storages.
                type: bindata_sensitive
                optional: true
                validator: {callback: "validateHmac"}
    DocumentSourceQueryStatsSpec:
        description: "Specification for a $queryStats stage."
        strict: true
        fields:
            transformIdentifiers:
                description: "The algorithm and hmac key to use when transforming identifiers."
                type: TransformIdentifiersSpec
                optional: true
