# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    mod_visibility: private
    cpp_namespace: "mongo"

server_parameters:
    mrEnableSingleReduceOptimization:
        description: >
            In version 4.2 and before, MongoDB MapReduce will not call the reduce function 
            for a key that has only a single value. In version 4.4 and later, the reduce 
            function is still called in order to validate the JavaScript reduce function 
            even when there is only one value. This setting will re-enable the old optimization.
        set_at: startup
        cpp_vartype: bool
        cpp_varname: mrSingleReduceOptimizationEnabled
        default: false
        redact: false
