# -*- mode: python -*-

Import("env")

env = env.Clone()

env.SConscript(
    must_exist=1,
    dirs=[
        "process_interface",
        "spilling",
    ],
    exports=[
        "env",
    ],
)

env.Benchmark(
    target="document_source_group_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="second_half_bm",
)

env.CppUnitTest(
    target="db_pipeline_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="db_percentile_algo_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="percentile_algo_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)

env.CppUnitTest(
    target="common_sort_key_optimization_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="group_with_acc_n_optimization_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="window_function_percentile_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)

env.Benchmark(
    target="window_function_concat_arrays_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)
