
Import("env")

env.Library(
    target='field_path',
    source=[
        'field_path.cpp',
        ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/util/foundation',
        ]
    )

env.CppUnitTest(
    target='field_path_test',
    source='field_path_test.cpp',
    LIBDEPS=[
        'field_path',
        ],
    )

env.Library(
    target='document_value',
    source=[
        'document.cpp',
        'value.cpp',
        ],
    LIBDEPS=[
        'field_path',
        '$BUILD_DIR/mongo/bson/bson',
        '$BUILD_DIR/mongo/util/foundation',
        '$BUILD_DIR/mongo/util/intrusive_counter',
        ]
    )

env.CppUnitTest(
    target='document_value_test',
    source='document_value_test.cpp',
    LIBDEPS=[
        'document_value',
        ],
    )

