# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    mod_visibility: public

imports:
    - "mongo/db/basic_types.idl"

structs:
    StorageStatsSpec:
        description: Represents the 'storageStats' argument to the $collStats stage.
        strict: false
        query_shape_component: true
        fields:
            scale:
                description: A number to use as a scaling factor applied to reported metrics.
                type: safeInt
                optional: true
                validator: {gte: 1}
                query_shape: literal
            verbose:
                type: optionalBool
                default: false
                query_shape: parameter
            waitForLock:
                type: optionalBool
                default: true
                query_shape: parameter
            numericOnly:
                type: optionalBool
                default: false
                query_shape: parameter
