# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/exec/document_value/value.h"
    mod_visibility: public

types:
    Value:
        bson_serialization_type: any
        description: A value with any BSON type.
        cpp_type: Value
        serializer: Value::serializeForIDL
        deserializer: Value::deserializeForIDL
        # Deserializer deep copies members.
        is_view: false
    numeric:
        bson_serialization_type:
            - int
            - decimal
            - double
            - long
        description: A value with any numeric BSON type.
        cpp_type: Value
        serializer: Value::serializeForIDL
        deserializer: Value::deserializeForIDL
        is_view: false
