#! /bin/sh

# Script to run Gimpel's flexlint program.

f()
{
	flexelint_binary +fll \
	    "-esym(534,fprintf,memcpy,memset)" \
	    "-emacro(776,WT_ALIGN)" \
	    "-emacro(776,WT_OVERFLOW_BYTES_TO_FRAGS)" \
	    "-emacro(737,WT_ALIGN)" \
	    "-e773" \
	    "-e506" \
	    "-e613" \
	    "-e717" \
	    "-e774" \
	    "-e801" \
	    "-e818" \
	    "-e826" \
	    "-function(exit,__wt_abort)" \
	    "-libdir(.)" \
	    "-libdir(../inc_posix)" \
	    "+libh(bitstring.h)" \
	    "+libh(queue.h)" \
	    "+libh(wiredtiger_config.h)" \
	    "-wlib(0)" \
	     "-i." "-i../inc_posix" "-i/usr/include" $1
}

update=0
while :
	do case "$1" in
	-u)
		update=1
		shift;;
	*)
		break;;
	esac
done

# List of source files.
l="../btree/*.c ../connect/*.c ../db/*.c ../env/*.c ../os_posix/*.c
   ../support/*.c"
l=`ls $l`

if [ $# -ne 0 ]; then
	f "$*"
else
	f "$l" > flexlint.out 2>&1

	f=../lint/flexlint.out

	if test "$update" -eq 1; then
		cp flexlint.out $f
	elif test -f "$f"; then
		cmp flexlint.out $f > /dev/null 2>&1 ||
		    diff flexlint.out $f | more
	else
		more flexlint.out
	fi
fi

exit 0
