#! /bin/sh
#
# Build Makefile.am

# Process Make.base, insert subdirs that exist from Make.subdirs
# (in release trees, some of the subdirs might be excluded).
(sed -n '1,/BEGIN SUBDIRS/p' Make.base

echo "SUBDIRS ="
sed -e 's/#.*$//' -e '/^$/d' Make.subdirs | (while read dir cond ; do
	test -d ../$dir || continue
	if test -n "$cond" ; then
		cat <<END_CONDITIONAL
if ${cond}
    SUBDIRS += $dir
endif
END_CONDITIONAL
	else
		echo "SUBDIRS += $dir"
	fi
done)

# Write the rest of Make.base, up to SOURCES
sed -n '/END SUBDIRS/,/BEGIN SOURCES/p' Make.base

echo
echo "libwiredtiger_la_LDFLAGS = -release @VERSION@"
echo "libwiredtiger_la_SOURCES=\\"
sed -e '/^[a-z]/!d' \
    -e 's/.*/	& \\/' \
    -e '$s/ \\$//' < ../dist/filelist

# Write the rest of Make.base
sed -n '/END SOURCES/,$p' Make.base
) > ../Makefile.am
