#! /bin/sh
#
# Copyright (c) 2008-2011 WiredTiger, Inc.
#	All rights reserved.

# Build Makefile.am
filelist=../dist/filelist
set_sources()
{
	echo
	echo "libwiredtiger_la_LDFLAGS = -release @VERSION@"
	echo "libwiredtiger_la_SOURCES=\\"
	sed -e '/^[a-z]/! d' \
	    -e 's/.*/	& \\/' \
	    -e '$s/ \\$//' < $filelist
}

(cat Make.base; set_sources) > ../Makefile.am
