#! /bin/sh
#
# Copyright (c) 2008-2011 WiredTiger, Inc.
#	All rights reserved.

t=/tmp/__configure.$$
trap 'rm -f $t; exit 0' 0 1 2 3 13 15

# There's a cleanup function so we can easily clean out the directory.
clean()
{
	test -f Makefile && make distclean > /dev/null
	rm -rf \
	    ChangeLog COPYING INSTALL Makefile.am Makefile.in NEWS \
	    README aclocal.m4 autom4te.cache config.hin config.hin~ \
	    configure flexlint.out mklog
}

while :
	do case "$1" in
	-c)
		clean			# Clean and leave empty
		exit 0;;
	*)
		clean			# Clean and then re-create
		break;;
	esac
done

# Initialize standard automake files.
cp ../LICENSE COPYING
cat << END > ChangeLog
To view release and installation documentation, load the distribution
file docs/index.html into your web browser.
END
cp ../README INSTALL
cat << END > NEWS
To view release and installation documentation, load the distribution
file docs/index.html into your web browser.
END
cp ../README README

# Build Makefile.am
sh ./makemake

autoreconf --install

# Make sure any missing files are writable
chmod 755 gnu-support/*

# Cleanup
rm -rf autom4te.cache config.hin~

exit 0
