dnl build by dist/s_version

VERSION_MAJOR=1
VERSION_MINOR=1
VERSION_PATCH=3
VERSION_STRING='"WiredTiger 1.1.3: (April  4, 2012)"'

AC_SUBST(VERSION_MAJOR)
AC_SUBST(VERSION_MINOR)
AC_SUBST(VERSION_PATCH)
AC_SUBST(VERSION_STRING)

VERSION_NOPATCH=1.1
AC_SUBST(VERSION_NOPATCH)
