dnl build by dist/s_version

VERSION_MAJOR=0
VERSION_MINOR=7
VERSION_PATCH=0
VERSION_STRING='"WiredTiger 0.7.0: (September  2, 2011)"'

AC_SUBST(VERSION_MAJOR)
AC_SUBST(VERSION_MINOR)
AC_SUBST(VERSION_PATCH)
AC_SUBST(VERSION_STRING)

VERSION_NOPATCH=.
AC_SUBST(VERSION_NOPATCH)
