dnl build by dist/s_version

VERSION_MAJOR=1
VERSION_MINOR=6
VERSION_PATCH=0
VERSION_STRING='"WiredTiger 1.6.0: (May 16, 2013)"'

AC_SUBST(VERSION_MAJOR)
AC_SUBST(VERSION_MINOR)
AC_SUBST(VERSION_PATCH)
AC_SUBST(VERSION_STRING)

VERSION_NOPATCH=1.6
AC_SUBST(VERSION_NOPATCH)
