# -*- mode: python -*-

Import("env")
Import("wiredtiger")

env = env.Clone()

env.CppLibfuzzerTest(
    target="protocol_fuzzer",
    source=[],
)

if wiredtiger:
    env.CppUnitTest(
        target="rpc_test",
        source=[],
        LIBDEPS=[],
    )

env.CppIntegrationTest(
    target="rpc_integration_test",
    source=[],
)
