# -*- mode: python -*-

Import("env")
Import("wiredtiger")

env = env.Clone()

env.CppLibfuzzerTest(
    target="protocol_fuzzer",
    source=[
        "protocol_fuzzer.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/concurrency/lock_manager",
        "$BUILD_DIR/mongo/db/query/write_ops/write_ops_parsers",
        "$BUILD_DIR/mongo/transport/message_compressor",
        "message",
        "rpc",
    ],
)

if wiredtiger:
    env.CppUnitTest(
        target="rpc_test",
        source=[],
        LIBDEPS=[],
    )
