# -*- mode: python -*-

Import("env")

env.Library(
    target='cluster_commands',
    source=[
        'cluster_explain_cmd.cpp',
        'cluster_enable_sharding_cmd.cpp',
        'cluster_find_cmd.cpp',
        'cluster_flush_router_config_cmd.cpp',
        'cluster_fsync_cmd.cpp',
        'cluster_get_last_error_cmd.cpp',
        'cluster_get_shard_version.cpp',
        'cluster_index_filter_cmd.cpp',
        'cluster_list_databases_cmd.cpp',
        'cluster_merge_chunks_cmd.cpp',
        'cluster_move_chunk_cmd.cpp',
        'cluster_move_primary_cmd.cpp',
        'cluster_netstat_cmd.cpp',
        'cluster_plan_cache_cmd.cpp',
        'cluster_repl_set_get_status_cmd.cpp',
        'cluster_reset_error.cpp',
        'cluster_shard_collection_cmd.cpp',
        'cluster_shutdown_cmd.cpp',
        'cluster_split_collection_cmd.cpp',
        'cluster_write_cmd.cpp',
    ],
    LIBDEPS=[

    ]
)
