Import("env")

env = env.Clone()

env.Library(
    target="server_rewrite",
    source=[
        'server_rewrite.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/matcher/expressions',
    ]
)

env.CppUnitTest(
    target="fle_server_rewrite_test",
    source=[
        "server_rewrite_test.cpp",
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/query/query_test_service_context',
        "server_rewrite",
    ],
)
