# -*- mode: python -*-

Import("env")

env = env.Clone()

env.SConscript(
    dirs=[
        'tom',
    ],
    exports=[
        'env',
    ],
)

env.Library('sha1_block',
    source=[
        'sha1_block.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/bongo/base',
        '$BUILD_DIR/bongo/util/secure_compare_memory',
    ])

env.Library(
    target='sha1_block_tom',
    source=[
        'sha1_block_tom.cpp'
    ],
    LIBDEPS=[
            '$BUILD_DIR/bongo/base',
            'sha1_block',
            'tom/tomcrypt'
    ])

env.Library('sha1_block_openssl',
    source=[
        'sha1_block_openssl.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/bongo/base',
        'sha1_block',
    ])

env.Library('scramauth',
            ['mechanism_scram.cpp'],
            LIBDEPS=['$BUILD_DIR/bongo/base',
                     '$BUILD_DIR/bongo/base/secure_allocator',
                     '$BUILD_DIR/bongo/util/secure_compare_memory',
                     '$BUILD_DIR/bongo/util/secure_zero_memory',
                     'sha1_block_${BONGO_CRYPTO}'])

env.CppUnitTest('sha1_block_test',
                ['sha1_block_test.cpp'],
                LIBDEPS=['sha1_block_${BONGO_CRYPTO}'])
