# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target="query_cost_model",
    source=[
        'cost_estimator.cpp',
        'cost_model.idl',
        'cost_model_manager.cpp',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/query/optimizer/optimizer_memo',
    ],
)

env.CppUnitTest(
    target="query_cost_model_test",
    source=[
        "cost_estimator_test.cpp",
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/query/optimizer/optimizer_memo',
        "$BUILD_DIR/mongo/unittest/unittest",
        'query_cost_model',
    ],
)
