# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target="query_cost_model",
    source=[
        'cost_model_manager.cpp',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/query/optimizer/optimizer',
    ],
)
