# -*- mode: python; -*-

Import("env")

env = env.Clone()

env.Library(
    target='storage_devnull_core',
    source=[
        'devnull_kv_engine.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/storage/ephemeral_for_test/ephemeral_for_test_record_store',
        '$BUILD_DIR/mongo/db/storage/kv/kv_prefix',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/snapshot_window_options',
    ],
)

env.Library(
    target='storage_devnull',
    source=[
        'devnull_init.cpp',
    ],
    LIBDEPS=[
        'storage_devnull_core',
        '$BUILD_DIR/mongo/db/storage/kv/kv_engine',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/storage/storage_engine_common',
    ],
)
