/*-
 * Copyright (c) 2008-2013 WiredTiger, Inc.
 *	All rights reserved.
 *
 * See the file LICENSE for redistribution information.
 */
package com.wiredtiger.db;

/**
 * An exception that is generated by the WiredTiger application during
 * encoding or decoding of packed values.
 */
public class WiredTigerPackingException extends WiredTigerException {
    /**
     * Constructor.
     */
    public WiredTigerPackingException(String msg) {
        super(msg);
    }
}

