# -*- mode: python -*-

Import("env")

env.CppUnitTest(
    target="boolean_simplification_test",
    source=[
        "bitset_algebra_test.cpp",
        "bitset_tree_test.cpp",
        "petrick_test.cpp",
        "quine_mccluskey_test.cpp",
    ],
    LIBDEPS=[
        "boolean_simplification",
    ],
)

env.Benchmark(
    target="quine_mccluskey_bm",
    source=[
        "bitset_algebra_bm.cpp",
        "dynamic_bitset_bm.cpp",
        "match_expression_bm.cpp",
        "petrick_bm.cpp",
        "quine_mccluskey_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query_expressions",
        "boolean_simplification",
    ],
)
