# -*- mode: python -*-

Import("env")

env = env.Clone()

env.SConscript(
    must_exist=1,
    dirs=[
        "document_value",
        "sbe",
    ],
    exports=[
        "env",
    ],
)

env.CppUnitTest(
    target="db_exec_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="distinct_scan_bm",
    source=[
        "distinct_scan_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query_exec",
        "$BUILD_DIR/mongo/db/service_context_d_test_fixture",
        "query_shard_server_test_fixture",
    ],
)
