# -*- mode: python -*-

Import("env")

env = env.Clone()

env.SConscript(
    dirs=[
        "document_value",
    ],
    exports=[
        "env",
    ],
)

# WorkingSet target and associated test
env.Library(
    target = "working_set",
    source = [
        "working_set.cpp",
    ],
    LIBDEPS = [
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/db/bson/dotted_path_support",
        "$BUILD_DIR/mongo/db/service_context",
        "document_value/document_value",
    ],
)

env.Library(
    target = "scoped_timer",
    source = [
        "scoped_timer.cpp",
    ],
    LIBDEPS = [
        '$BUILD_DIR/mongo/util/net/network',
    ],
)

sortExecutorEnv = env.Clone()
sortExecutorEnv.InjectThirdParty(libraries=['snappy'])
sortExecutorEnv.Library(
    target="sort_executor",
    source=[
        "sort_executor.cpp",
        "sort_key_comparator.cpp",
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/query/sort_pattern',
        '$BUILD_DIR/mongo/db/storage/encryption_hooks',
        '$BUILD_DIR/mongo/db/storage/storage_options',
        '$BUILD_DIR/mongo/s/is_mongos',
        '$BUILD_DIR/third_party/shim_snappy',
        'working_set',
    ],
)

env.Library(
    target='stagedebug_cmd',
    source=[
        'stagedebug_cmd.cpp'
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/index/index_access_methods",
        "$BUILD_DIR/mongo/db/query_exec",
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/commands/test_commands_enabled',
    ],
)

env.CppUnitTest(
    target='db_exec_test',
    source=[
        "document_value/document_comparator_test.cpp",
        "document_value/document_metadata_fields_test.cpp",
        "document_value/document_value_test.cpp",
        "document_value/document_value_test_util_self_test.cpp",
        "document_value/value_comparator_test.cpp",
        "find_projection_executor_test.cpp",
        "projection_exec_agg_test.cpp",
        "projection_exec_test.cpp",
        "projection_executor_test.cpp",
        "queued_data_stage_test.cpp",
        "sort_test.cpp",
        "working_set_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/db/projection_exec_agg",
        "$BUILD_DIR/mongo/db/query/collation/collator_factory_mock",
        "$BUILD_DIR/mongo/db/query/collation/collator_interface_mock",
        "$BUILD_DIR/mongo/db/query/query_test_service_context",
        "$BUILD_DIR/mongo/db/query_exec",
        "$BUILD_DIR/mongo/db/service_context_d",
        "$BUILD_DIR/mongo/db/service_context_d_test_fixture",
        "$BUILD_DIR/mongo/dbtests/mocklib",
        "$BUILD_DIR/mongo/util/clock_source_mock",
        "document_value/document_value",
        "document_value/document_value_test_util",
        "working_set",
    ],
)
