# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/index_builds/commit_quorum_options.h"

types:
    CommitQuorum:
        # Union of string and safeInt.
        bson_serialization_type:
            - long
            - int
            - decimal
            - double
            - string
        description:
            "CommitQuorumOptions defines the replica set membership required to be ready
            for commit in order for the primary to proceed to commit an index build."
        cpp_type: "mongo::CommitQuorumOptions"
        serializer: "mongo::CommitQuorumOptions::appendToBuilder"
        deserializer: "mongo::CommitQuorumOptions::deserializerForIDL"
        is_view: false
