Import("env")

env = env.Clone()

env.SConscript(
    must_exist=1,
    dirs=[
        "throughput_probing",
    ],
    exports=[
        "env",
    ],
)

env.CppUnitTest(
    target="tools_workload_characteristics_test",
    source=[],
    LIBDEPS=[],
)
