# -*- mode: python -*-

Import("env")

env.Library(
    target='views_mongod',
    source=[
        'durable_view_catalog.cpp',
        'view_sharding_check.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/dbhelpers',
        '$BUILD_DIR/mongo/db/views/views',
        '$BUILD_DIR/mongo/db/catalog/catalog',
        '$BUILD_DIR/mongo/db/s/sharding',
    ]
)

env.Library(
    target='views',
    source=[
        'view.cpp',
        'view_catalog.cpp',
        'resolved_view.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/server_parameters',
        '$BUILD_DIR/mongo/db/pipeline/aggregation',
        '$BUILD_DIR/mongo/db/repl/repl_coordinator_interface',
    ]
)
