# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="db_views_test",
    source=[
        "resolved_view_test.cpp",
        "view_catalog_test.cpp",
        "view_definition_test.cpp",
        "view_graph_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/db/catalog/catalog_test_fixture",
        "$BUILD_DIR/mongo/db/multitenancy",
        "$BUILD_DIR/mongo/db/query/collation/collator_interface_mock",
        "$BUILD_DIR/mongo/db/query/query_test_service_context",
        "$BUILD_DIR/mongo/db/repl/replmocks",
        "$BUILD_DIR/mongo/db/shard_role",
        "$BUILD_DIR/mongo/unittest/unittest",
        "view_catalog_helpers",
        "views",
    ],
)
