"""Compatibility shim mapping the prior rules_poetry `dependency()` API to
the `@pypi` hub generated by rules_pycross's `lock_import.import_uv()` in
//MODULE.bazel.

This exists so that the ~54 call sites of `dependency(name, group=...)`
across the repo continue to work after migrating from Poetry to uv. The
`group` kwarg is accepted for source compatibility but has no effect at
Bazel build time — group selection is a developer-side concern handled by
`uv sync --group X` / `uv sync --no-group Y`. All groups are merged into
`uv.lock` at generation time, so every locked package is available under
@pypi regardless of which group it lives in.

Naming under rules_pycross
--------------------------
The hub repo (`@pypi`) generated by rules_pycross's `lock_import.import_uv`
exposes each locked package as a root-level alias — `@pypi//:<name>` —
where <name> is the PEP 503 normalized distribution name (lowercased, with
runs of `-`, `_`, `.` collapsed to a single `-`). The target itself is a
`pycross_wheel_library`. Concretely:

    PyYAML          -> @pypi//:pyyaml
    types-PyYAML    -> @pypi//:types-pyyaml
    google-auth     -> @pypi//:google-auth
    zope.interface  -> @pypi//:zope-interface

Note the colon: it's `@pypi//:pyyaml` (root package, target `pyyaml`), NOT
`@pypi//pyyaml` (which would resolve to `@pypi//pyyaml:pyyaml`, a target
that doesn't exist — each per-package subdirectory only exposes `:wheel`
and `:sdist`, not a same-named target).
"""

def _normalize(name):
    """PEP 503 normalization used by rules_pycross's `@pypi//<name>` labels.

    Lowercase, then collapse runs of `-`, `_`, `.` into a single `-`.
    """
    out = name.lower()

    # Replace `_` and `.` with `-` first, then collapse runs of `-`.
    for ch in ("_", "."):
        out = out.replace(ch, "-")

    # Collapse runs of `-` into a single `-`. Starlark has no `while`, so
    # bound the loop by len(out): a run of N hyphens takes at most log2(N)
    # halving passes and always <= N total passes, so len(out) is a safe
    # upper bound with an early `break` when the fixed point is reached.
    for _ in range(len(out)):
        if "--" not in out:
            break
        out = out.replace("--", "-")
    return out

def dependency(name, group = None):
    """Return the Bazel label for a PyPI package locked in uv.lock.

    Args:
        name: PyPI distribution name (case-insensitive; will be normalized).
        group: Ignored. Accepted for compatibility with the old rules_poetry
            macro signature.

    Returns:
        A label string like "@pypi//:pyyaml".
    """
    _ = group  # buildifier: silence unused-argument
    return "@pypi//:" + _normalize(name)
