# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Benchmark(
    target="sbe_builder_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)

env.CppUnitTest(
    target="abt_unit_test_infra_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="sbe_abt_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="abt_lower_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="abt_lower_bm",
    source=[],
    LIBDEPS=[],
)
