# -*- mode: python; -*-

Import('env')

env = env.Clone()

env.Library(
    target='bson_extract',
    source=[
        'bson_extract.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ],
)

env.Library(
    target='bson_column',
    source=[
        'bsoncolumn.cpp',
        'bsoncolumn_interleaved.cpp',
        'bsoncolumnbuilder.cpp',
        'simple8b.cpp',
        'simple8b_type_util.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ],
)

env.Program(
    target="bson_column_encoder",
    source=[
        "bson_column_encoder.cpp",
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        'bson_column',
        'bson_extract',
    ],
)

env.Benchmark(
    target='simple8b_bm',
    source=[
        'simple8b_bm.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        'bson_column',
    ],
)

env.CppUnitTest(
    target='bson_util_test',
    source=[
        'bson_check_test.cpp',
        'bson_extract_test.cpp',
        'bsoncolumn_blockbased_test.cpp',
        'bsoncolumn_test.cpp',
        'builder_test.cpp',
        'simple8b_test.cpp',
        'simple8b_type_util_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/sbe_values',
        '$BUILD_DIR/mongo/util/safe_num',
        'bson_column',
        'bson_extract',
    ],
)

env.Benchmark(
    target='bsoncolumn_bm',
    source=[
        'bsoncolumn_bm.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/sbe_values',
        'bson_column',
    ],
)

env.CppLibfuzzerTest(
    target='simple8b_fuzzer',
    source=[
        'simple8b_fuzzer.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        'bson_column',
    ],
)

env.Benchmark(
    target='bufbuilder_bm',
    source=[
        'bufbuilder_bm.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ],
)
