# -*- mode: python; -*-

Import("env")

env = env.Clone()

env.Program(
    target="bson_corpus_gen",
    source=[
        "bson_corpus_gen.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
    ],
)

env.CppUnitTest(
    target="bson_util_test",
    source=[
        "bson_check_test.cpp",
        "bson_extract_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/util/safe_num",
        "bson_extract",
    ],
)

env.Benchmark(
    target="bufbuilder_bm",
    source=[
        "bufbuilder_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
    ],
)
