# -*- mode: python -*-

Import([
    'env',
    'version_extra',
    'version_parts',
])

env = env.Clone()

generateReleases = env.Command(
    target=[
        'releases.h',
    ],
    source=[
        '#buildscripts/cheetah_source_generator.py',
        'releases.h.tpl',
        'releases.yml',
    ],
    action=[
        '$PYTHON ${SOURCES[0]} -o ${TARGETS[0]} ${SOURCES[1]} ${SOURCES[2]} ${MONGO_VERSION}',
    ],
)

env.Alias('generated-sources', generateReleases)
