# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="shard_server_op_observer_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="db_s_shard_server_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="db_s_config_server_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="chunk_manager_refresh_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="sharding_bm",
)

env.Benchmark(
    target="migration_chunk_cloner_source_bm",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="sharding_write_router_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="sharding_bm",
)

env.Benchmark(
    target="placement_history_bm",
    source=[],
    LIBDEPS=[],
)
