# -*- mode: python; -*-

Import("env")

env = env.Clone()

capi = env.Library(
    target='mongo_embedded_capi',
    source=[
        'libmongodbcapi.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base', 
    ]
)

env.Alias( 'embedded_capi', capi)

env.CppUnitTest(
    target='mongo_embedded_capi_test',
    source=[
        'libmongodbcapi_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base', 
        'mongo_embedded_capi',
    ],
)
