/**
 * Tests that the oplog bytes transferred over the network for replication are tracked in
 * serverStatus under metrics.repl.network.bytes (received: oplog fetched from the sync source) and
 * metrics.repl.network.bytesSent (sent: oplog served to syncing nodes).
 *
 * @tags: [
 *   requires_replication,
 *   multiversion_incompatible,
 * ]
 */
import {after, before, describe, it} from "jstests/libs/mochalite.js";
import {ReplSetTest} from "jstests/libs/replsettest.js";

const kFields = ["bytes", "bytesSent"];

// serverStatus counters are reported as BSON NumberLong (typeof "object"), so coerce to a JS number
// for comparisons. The traffic generated by this test is well under 2^53, so this is exact.
function num(x) {
    return x instanceof NumberLong ? x.toNumber() : Number(x);
}

// Returns {bytes, bytesSent} from metrics.repl.network, asserting each is present and a non-negative
// count.
function replNetwork(conn) {
    const net = assert.commandWorked(conn.adminCommand({serverStatus: 1})).metrics.repl.network;
    for (const field of kFields) {
        assert(net.hasOwnProperty(field), "missing metrics.repl.network." + field, {net});
        assert.gte(
            num(net[field]),
            0,
            "metrics.repl.network." + field + " should be non-negative",
            {net},
        );
    }
    return {bytes: num(net.bytes), bytesSent: num(net.bytesSent)};
}

describe("oplog network bytes metrics", function () {
    let rst;
    let primary;
    let secondary;

    before(function () {
        // A priority-0 secondary keeps node 0 as the stable primary/sync source.
        rst = new ReplSetTest({nodes: [{}, {rsConfig: {priority: 0}}]});
        rst.startSet();
        rst.initiate();
        rst.awaitSecondaryNodes();
        primary = rst.getPrimary();
        secondary = rst.getSecondaries()[0];
    });

    after(function () {
        if (rst) {
            rst.stopSet();
        }
    });

    it("exposes both counters on every node", function () {
        replNetwork(primary);
        replNetwork(secondary);
    });

    it("records oplog bytes only on the transferring side of each node", function () {
        const primaryBefore = replNetwork(primary);
        const secondaryBefore = replNetwork(secondary);

        // Insert ~1MB of data with w:2. In a primary + (priority-0) secondary set, the write only
        // completes once the secondary has fetched and replicated it, so by the time execute()
        // returns the secondary has fetched that oplog and the sync source has served it -- no
        // polling needed.
        const kNumDocs = 1000;
        const kPayloadBytes = 1024;
        const bulk = primary.getDB("test").oplog_bytes.initializeUnorderedBulkOp();
        for (let i = 0; i < kNumDocs; i++) {
            bulk.insert({_id: i, payload: "x".repeat(kPayloadBytes)});
        }
        assert.commandWorked(bulk.execute({w: 2}));

        const primaryAfter = replNetwork(primary);
        const secondaryAfter = replNetwork(secondary);

        // The oplog entries wrap the inserted documents, so each transferring side must have moved at
        // least the inserted payload. Asserting on the full volume (not just "increased") guards
        // against accounting that bumps a counter by a token amount instead of the actual bytes.
        const minBytes = kNumDocs * kPayloadBytes;
        assert.gte(
            secondaryAfter.bytes - secondaryBefore.bytes,
            minBytes,
            "secondary should have fetched the oplog payload",
        );
        assert.gte(
            primaryAfter.bytesSent - primaryBefore.bytesSent,
            minBytes,
            "sync source should have served the oplog payload",
        );

        // Each counter advances only on the side that performs the transfer. The primary has no sync
        // source so it fetches nothing, and the priority-0 secondary serves no one, so the
        // opposite-direction counters must not move.
        assert.eq(
            primaryAfter.bytes - primaryBefore.bytes,
            0,
            "primary should not receive any oplog bytes",
        );
        assert.eq(
            secondaryAfter.bytesSent - secondaryBefore.bytesSent,
            0,
            "secondary should not send any oplog bytes",
        );

        assert.commandWorked(primary.getDB("test").dropDatabase());
    });
});
