#! /bin/sh

rm -f vgout.*

# Command line argument is the number of iterations.
r=1
test $# -eq 0 || r=$1

# Add
#	--db-attach=yes
# to wait on a debugger attach.
while test $r -gt 0; do
	r=`expr $r - 1`
	valgrind \
	    --leak-check=yes \
	    --log-file=vgout.%p \
	    --read-var-info=yes \
	    --suppressions=vt.suppress \
	    --track-fds=yes \
	    ./t -1
done
