# -*- mode: python -*-

Import(
    [
        "env",
        "get_option",
    ]
)

env = env.Clone()

env.CppUnitTest(
    target="db_query_query_stats_test",
    source=[
        "agg_key_test.cpp",
        "count_key_test.cpp",
        "distinct_key_test.cpp",
        "find_key_test.cpp",
        "key_test.cpp",
        "query_stats_test.cpp",
        "supplemental_metrics_test.cpp",
        "query_stats_store_test.cpp",
        "rate_limiting_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/db/query/query_common",
        "$BUILD_DIR/mongo/db/query/query_shape/query_shape",
        "$BUILD_DIR/mongo/db/query/query_test_service_context",
        "$BUILD_DIR/mongo/db/service_context_d_test_fixture",
        "query_stats",
        "rate_limiting",
    ],
)

env.Benchmark(
    target="rate_limiting_bm",
    source=[
        "rate_limiting_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/unittest/unittest",
        "$BUILD_DIR/mongo/util/processinfo",
        "rate_limiting",
    ],
    CONSOLIDATED_TARGET="query_bm",
)

env.Benchmark(
    target="shapifying_bm",
    source=[
        "shapifying_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/db/auth/auth",
        "$BUILD_DIR/mongo/db/pipeline/pipeline",
        "$BUILD_DIR/mongo/db/query/canonical_query",
        "$BUILD_DIR/mongo/db/query/query_shape/query_shape",
        "$BUILD_DIR/mongo/db/query/query_test_service_context",
        "$BUILD_DIR/mongo/db/server_base",
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "$BUILD_DIR/mongo/rpc/client_metadata",
        "$BUILD_DIR/mongo/unittest/unittest",
        "$BUILD_DIR/mongo/util/processinfo",
        "query_stats",
    ],
    CONSOLIDATED_TARGET="query_nond_bm",
)
