# -*- mode: python -*-

Import(
    [
        "env",
    ]
)

env = env.Clone()

env.CppUnitTest(
    target="db_query_query_stats_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="rate_limiting_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)

env.Benchmark(
    target="shapifying_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)
