load("@rules_python//python:defs.bzl", "py_test")
load(":install_rules_test.bzl", "install_rules_test_suite")

package(default_visibility = ["//visibility:public"])

# Expose script for external usage through bazel.
exports_files([
    "install_mongodbtoolchain.sh",
    "install_rules.py",
    "pretty_printer_test_creator.py",
])

sh_test(
    name = "install_mongodbtoolchain_test",
    srcs = ["install_mongodbtoolchain_test.sh"],
    data = ["install_mongodbtoolchain.sh"],
)

sh_test(
    name = "gdb_toolchain_folder_test",
    srcs = ["gdb_toolchain_folder_test.sh"],
    data = ["//:gdb_toolchain_folder"],
    target_compatible_with = ["@platforms//os:linux"],
)

install_rules_test_suite(name = "install_rules_analysis_test")

py_test(
    name = "install_rules_script_test",
    srcs = ["install_rules_script_test.py"],
    data = ["install_rules.py"],
)

py_test(
    name = "pretty_printer_test_launcher_test",
    srcs = ["pretty_printer_test_launcher_test.py"],
    data = ["//src/mongo/util:pretty_printer_test_launcher.py.in"],
)

test_suite(
    name = "install_rules_test",
    tests = [
        ":install_rules_analysis_test",
        ":install_rules_script_test",
        ":pretty_printer_test_launcher_test",
    ],
)
