# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/query/index_hint.h"
    mod_visibility: private

imports:
    - "mongo/db/basic_types.idl"

types:
    IndexHint:
        description: >-
            Type representing possible index hint definition, including index key 
            pattern, index name and $natural hint.
        cpp_type: IndexHint
        bson_serialization_type: any
        serializer: "mongo::IndexHint::append"
        deserializer: "mongo::IndexHint::parse"
        # Deserializer uses owned object or BSONElement::String().
        is_view: false
