// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#pragma once

#include "mongo/bson/bsonobj.h"
#include "mongo/db/exec/plan_stats.h"
#include "mongo/db/query/compiler/optimizer/cost_based_ranker/estimates_storage.h"
#include "mongo/db/query/compiler/physical_model/query_solution/query_solution.h"
#include "mongo/db/query/explain_options.h"
#include "mongo/db/query/plan_enumerator/plan_enumerator_explain_info.h"
#include "mongo/db/query/plan_summary_stats.h"
#include "mongo/db/query/stage_builder/classic_stage_builder.h"
#include "mongo/util/duration.h"
#include "mongo/util/modules.h"
#include "mongo/util/string_map.h"

#include <cstdint>

namespace mongo {

/**
 * A struct to hold a QuerySolution along with its corresponding PlanStage tree.
 * It is intended to hold root nodes both for the solution and also its corresponding execution tree
 * for explain purposes.
 */
struct SolutionWithPlanStage {
    std::unique_ptr<QuerySolution> solution;
    std::unique_ptr<PlanStage> planStage;
};

struct PlanExplainerData {
    std::unique_ptr<WorkingSet> workingSetForRejectedPlansExplain;
    std::vector<SolutionWithPlanStage> rejectedPlansWithStages;
    std::unique_ptr<mongo::PlanStageStats> multiPlannerWinningPlanTrialStats;
    boost::optional<double> multiPlannerWinningPlanScore;
    stage_builder::PlanStageToQsnMap planStageQsnMap;
    cost_based_ranker::EstimateMap estimates;
    // Namespace-keyed map of sampling metadata emitted under queryPlanner.ceSamplingMetadata.
    // Populated on the explain path when CBR used a sampling estimator.
    StringMap<cost_based_ranker::SamplingMetadata> ceSamplingMetadata;
    bool fromPlanCache = false;
    // Hash of the join plan cache key. Populated on the explain path of a join eligible query.
    boost::optional<uint32_t> joinPlanCacheKeyHash;
};

inline PlanExplainerData& operator<<(PlanExplainerData& lhs, PlanExplainerData&& rhs) {
    lhs.rejectedPlansWithStages.insert(lhs.rejectedPlansWithStages.end(),
                                       std::make_move_iterator(rhs.rejectedPlansWithStages.begin()),
                                       std::make_move_iterator(rhs.rejectedPlansWithStages.end()));
    lhs.planStageQsnMap.insert(rhs.planStageQsnMap.begin(), rhs.planStageQsnMap.end());
    for (auto& [k, v] : rhs.estimates) {
        lhs.estimates.insert_or_assign(k, std::move(v));
    }
    for (auto& [ns, meta] : rhs.ceSamplingMetadata) {
        tassert(12433204,
                "ceSamplingMetadata already has an entry for namespace during merge",
                !lhs.ceSamplingMetadata.contains(ns));
        lhs.ceSamplingMetadata.emplace(ns, std::move(meta));
    }
    return lhs;
}

inline boost::optional<PlanExplainerData>& operator<<(boost::optional<PlanExplainerData>& lhs,
                                                      boost::optional<PlanExplainerData>&& rhs) {
    if (!rhs) {
        return lhs;
    }
    if (!lhs) {
        lhs = std::move(rhs);
        return lhs;
    }
    *lhs << std::move(*rhs);
    return lhs;
}


/**
 * This interface defines an API to provide information on the execution plans generated by the
 * query planner for a user query in various formats.
 */
class PlanExplainer {
public:
    /**
     * A version of the explain format:
     * - "1" is used for the classic engine
     * - "2" for SBE stagebuilders
     * - "3" for the V3 explain format, requested via one of the V3 verbosity modes.
     *   Unlike "1"/"2", "3" is not determined by the execution engine.
     */
    using ExplainVersion = std::string;

    /**
     * This pair holds a serialized BSON document that details the plan selected by the query
     * planner, and optional summary stats for an execution tree if the verbosity level for the
     * generated stats is 'executionStats' or higher. The format of these stats are opaque to the
     * caller, and different implementations may choose to provide different stats.
     */
    using PlanStatsDetails = std::pair<BSONObj, boost::optional<PlanSummaryStats>>;

    PlanExplainer() {}
    PlanExplainer(const QuerySolution* solution)
        : _solution(solution),
          _enumeratorExplainInfo{_solution ? _solution->_enumeratorExplainInfo
                                           : PlanEnumeratorExplainInfo{}} {}
    PlanExplainer(const PlanEnumeratorExplainInfo& info) : _enumeratorExplainInfo{info} {}

    virtual ~PlanExplainer() = default;

    /**
     * Returns a version of the explain format supported by this explainer. This is determined by
     * the execution engine ("1" for the classic engine, "2" for SBE). To obtain the version that
     * explain should actually report depending on either engine or a given verbosity, use
     * getVerbosityVersion().
     */
    virtual const ExplainVersion& getVersion() const = 0;

    /**
     * Returns the explain version to report for the given 'verbosity'. When any of the V3 verbosity
     * modes is requested this is "3"; otherwise it is the engine-determined version from
     * getVersion(). Centralizing the decision here keeps getVersion() meaning the engine version
     * and ensures the V3 rule cannot be bypassed by, or diverge across, explainer implementations.
     */
    ExplainVersion getVerbosityVersion(ExplainOptions::Verbosity verbosity) const {
        return ExplainOptions::isV3Verbosity(verbosity) ? ExplainVersion{"3"} : getVersion();
    }

    /**
     * Returns 'true' if this PlanExplainer can provide information on the winning plan and rejected
     * candidate plans, meaning that the QueryPlanner generated multiple candidate plans and the
     * winning plan was chosen by the multi-planner.
     */
    virtual bool areThereRejectedPlansToExplain() const = 0;

    /**
     * Returns a short string, suitable for the logs, which summarizes the execution plan.
     */
    [[MONGO_MOD_NEEDS_REPLACEMENT]] virtual std::string getPlanSummary() const = 0;

    /**
     * Fills out 'statsOut' with summary stats collected during the execution of the underlying
     * plan. This is a lightweight alternative which is useful when operations want to request a
     * summary of the available debug information without generating complete explain output.
     *
     * The summary stats are consumed by debug mechanisms such as the profiler and the slow query
     * log.
     */
    [[MONGO_MOD_NEEDS_REPLACEMENT]] virtual void getSummaryStats(
        PlanSummaryStats* statsOut) const = 0;

    /**
     * Fills out 'statsOut' for the secondary collection 'secondaryColl'. Subclasses may
     * override this function if the summary stats for secondary collections need to be reported
     * separately.
     */
    virtual void getSecondarySummaryStats(const NamespaceString& secondaryColl,
                                          PlanSummaryStats* statsOut) const {}

    /**
     * Returns statistics that detail the winning plan selected by the multi-planner, or, if no
     * multi-planning has been performed, for the single plan selected by the QueryPlanner.
     *
     * The 'verbosity' level parameter determines the amount of information to be returned.
     */
    [[MONGO_MOD_NEEDS_REPLACEMENT]] virtual PlanStatsDetails getWinningPlanStats(
        ExplainOptions::Verbosity verbosity) const = 0;

    virtual PlanStatsDetails getWinningPlanStatsQueryPlanner(bool /*printBytecode*/) const {
        return getWinningPlanStats(ExplainOptions::Verbosity::kQueryPlanner);
    }

    /**
     * Returns statistics for the trial period of the winning plan selected by the multi-planner.
     */
    virtual PlanStatsDetails getWinningPlanTrialStats() const = 0;

    /**
     * Returns statistics that detail candidate plans rejected by the multi-planner. If no
     * multi-planning has been performed, an empty vector is returned.
     *
     * The 'verbosity' level parameter determines the amount of information to be returned.
     */
    virtual std::vector<PlanStatsDetails> getRejectedPlansStats(
        ExplainOptions::Verbosity verbosity) const = 0;

    /**
     * Returns an object containing what query knobs the planner hit during plan enumeration. This
     * is specific to classic.
     */
    PlanEnumeratorExplainInfo getEnumeratorInfo() const {
        return _enumeratorExplainInfo;
    }
    void updateEnumeratorExplainInfo(const PlanEnumeratorExplainInfo& other) {
        _enumeratorExplainInfo.merge(other);
    }

    void setQuerySolution(const QuerySolution* qs) {
        _solution = qs;
    }

    /**
     * Returns the per-collection sampling metadata to be emitted under
     * queryPlanner.ceSamplingMetadata in explain output. Returns boost::none if no sampling
     * metadata is available (e.g., CBR was not used, or this is not a classic-engine plan).
     */
    virtual boost::optional<StringMap<cost_based_ranker::SamplingMetadata>> getCeSamplingMetadata()
        const {
        return boost::none;
    }

    /**
     * Returns a hash of the join plan cache key. Returns boost::none if the query is not eligible
     * for join optimization.
     */
    virtual boost::optional<uint32_t> getJoinPlanCacheKeyHash() const {
        return boost::none;
    }

protected:
    const QuerySolution* _solution{nullptr};
    PlanEnumeratorExplainInfo _enumeratorExplainInfo;
};
}  // namespace mongo
