// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

/**
 * EXPAND table of QueryKnob<T>s mirroring the server parameters in query_optimization_knobs.idl.
 */

#pragma once

#include "mongo/db/mongod_options_storage_gen.h"
#include "mongo/db/query/query_knobs/query_knob.h"
#include "mongo/db/query/query_optimization_knobs_gen.h"
#include "mongo/db/storage/storage_options.h"
#include "mongo/util/modules.h"

namespace mongo {
// MSVC C1001 workaround: MSVC cannot use a member access expression (e.g.
// storageGlobalParams.noTableScan) as a non-type template argument. Bind the target member to a
// named reference so the KNOB() macro can pass it as a simple identifier.
// TODO (SERVER-129983): Remove this workaround once the underlying MSVC ICE is fixed.
inline Atomic<bool>& gKnobNoTableScan = storageGlobalParams.noTableScan;
}  // namespace mongo

// clang-format off
#define MONGO_EXPAND_QUERY_KNOBS_OPTIMIZATION(KNOB)                                      \
    /* Multi-plan ranking */                                                              \
    KNOB(kPlanEvaluationWorks,                                                            \
         kInternalQueryPlanEvaluationWorksName,                                           \
         internalQueryPlanEvaluationWorks,                                                \
         getPlanEvaluationWorks)                                                          \
    KNOB(kPlanEvaluationMaxResults,                                                       \
         kInternalQueryPlanEvaluationMaxResultsName,                                      \
         internalQueryPlanEvaluationMaxResults,                                           \
         getPlanEvaluationMaxResultsForOp)                                                \
    KNOB(kPlanEvaluationCollFraction,                                                     \
         kInternalQueryPlanEvaluationCollFractionName,                                    \
         internalQueryPlanEvaluationCollFraction,                                         \
         getPlanEvaluationCollFraction)                                                   \
    KNOB(kPlanTotalEvaluationCollFraction,                                                \
         kInternalQueryPlanTotalEvaluationCollFractionName,                               \
         internalQueryPlanTotalEvaluationCollFraction,                                    \
         getPlanTotalEvaluationCollFraction)                                              \
    KNOB(kSbePlanEvaluationMaxMemoryBytes,                                                \
         kInternalQuerySBEPlanEvaluationMaxMemoryBytesName,                               \
         internalQuerySBEPlanEvaluationMaxMemoryBytes,                                    \
         getSbePlanEvaluationMaxMemoryBytes)                                              \
    KNOB(kPlanTieBreakingWithIndexHeuristics,                                             \
         kInternalQueryPlanTieBreakingWithIndexHeuristicsName,                            \
         internalQueryPlanTieBreakingWithIndexHeuristics,                                 \
         getPlanTieBreakingWithIndexHeuristics)                                           \
    KNOB(kPlannerEnableSortIndexIntersection,                                             \
         kInternalQueryPlannerEnableSortIndexIntersectionName,                            \
         internalQueryPlannerEnableSortIndexIntersection,                                 \
         getPlannerEnableSortIndexIntersection)                                           \
    KNOB(kPlannerEnableIndexPruning,                                                      \
         kInternalQueryPlannerEnableIndexPruningName,                                     \
         internalQueryPlannerEnableIndexPruning,                                          \
         getPlannerEnableIndexPruning)                                                    \
    KNOB(kConcurrentMultiPlanningThreshold,                                               \
         kInternalQueryConcurrentMultiPlanningThresholdName,                              \
         internalQueryConcurrentMultiPlanningThreshold,                                   \
         getConcurrentMultiPlanningThreshold)                                             \
    KNOB(kMaxConcurrentMultiPlanJobsPerCacheKey,                                          \
         kInternalQueryMaxConcurrentMultiPlanJobsPerCacheKeyName,                         \
         internalQueryMaxConcurrentMultiPlanJobsPerCacheKey,                              \
         getMaxConcurrentMultiPlanJobsPerCacheKey)                                        \
    /* Planning and enumeration */                                                        \
    KNOB(kForceIntersectionPlans,                                                         \
         kInternalQueryForceIntersectionPlansName,                                        \
         internalQueryForceIntersectionPlans,                                             \
         getForceIntersectionPlans)                                                       \
    KNOB(kPlannerEnableIndexIntersection,                                                 \
         kInternalQueryPlannerEnableIndexIntersectionName,                                \
         internalQueryPlannerEnableIndexIntersection,                                     \
         getPlannerEnableIndexIntersection)                                               \
    KNOB(kPlannerEnableHashIntersection,                                                  \
         kInternalQueryPlannerEnableHashIntersectionName,                                 \
         internalQueryPlannerEnableHashIntersection,                                      \
         getPlannerEnableHashIntersection)                                                \
    KNOB(kEnumerationPreferLockstepOrEnumeration,                                         \
         kInternalQueryEnumerationPreferLockstepOrEnumerationName,                        \
         internalQueryEnumerationPreferLockstepOrEnumeration,                             \
         getEnumerationPreferLockstepOrEnumeration)                                       \
    KNOB(kPlanOrChildrenIndependently,                                                    \
         kInternalQueryPlanOrChildrenIndependentlyName,                                   \
         internalQueryPlanOrChildrenIndependently,                                        \
         getPlanOrChildrenIndependently)                                                  \
    KNOB(kPlannerGenerateCoveredWholeIndexScans,                                          \
         kInternalQueryPlannerGenerateCoveredWholeIndexScansName,                         \
         internalQueryPlannerGenerateCoveredWholeIndexScans,                              \
         getPlannerGenerateCoveredWholeIndexScans)                                        \
    KNOB(kPlannerMaxIndexedSolutions,                                                     \
         kInternalQueryPlannerMaxIndexedSolutionsName,                                    \
         internalQueryPlannerMaxIndexedSolutions,                                         \
         getPlannerMaxIndexedSolutions)                                                   \
    KNOB(kMaxEstimatedScanBytes,                                                          \
         kMaxEstimatedScanBytesName,                                                      \
         internalQueryMaxEstimatedScanBytes,                                              \
         getMaxEstimatedScanBytes)                                                        \
    KNOB(kMaxEstimatedScanBytesDryRun,                                                    \
         kMaxEstimatedScanBytesDryRunName,                                                \
         internalQueryMaxEstimatedScanBytesDryRun,                                        \
         getMaxEstimatedScanBytesDryRun)                                                  \
    KNOB(kMaxScansToExplode,                                                              \
         kInternalQueryMaxScansToExplodeName,                                             \
         internalQueryMaxScansToExplode,                                                  \
         getMaxScansToExplodeForOp)                                                       \
    KNOB(kPlannerUseMultiplannerForSingleSolutions,                                       \
         kInternalQueryPlannerUseMultiplannerForSingleSolutionsName,                      \
         internalQueryPlannerUseMultiplannerForSingleSolutions,                           \
         getUseMultiplannerForSingleSolutions)                                            \
    KNOB(kMinAllPlansEnumerationSubsetLevel,                                              \
         kInternalMinAllPlansEnumerationSubsetLevelName,                                  \
         internalMinAllPlansEnumerationSubsetLevel,                                       \
         getInternalMinAllPlansEnumerationSubsetLevel)                                    \
    KNOB(kMaxAllPlansEnumerationSubsetLevel,                                              \
         kInternalMaxAllPlansEnumerationSubsetLevelName,                                  \
         internalMaxAllPlansEnumerationSubsetLevel,                                       \
         getInternalMaxAllPlansEnumerationSubsetLevel)                                    \
    /* Plan cache */                                                                      \
    KNOB(kDisablePlanCache,                                                               \
         kInternalQueryDisablePlanCacheName,                                              \
         internalQueryDisablePlanCache,                                                   \
         getDisablePlanCache)                                                             \
    KNOB(kCacheMaxEntriesPerCollection,                                                   \
         kInternalQueryCacheMaxEntriesPerCollectionName,                                  \
         internalQueryCacheMaxEntriesPerCollection,                                       \
         getCacheMaxEntriesPerCollection)                                                 \
    KNOB(kCacheMaxSizeBytesBeforeStripDebugInfo,                                          \
         kInternalQueryCacheMaxSizeBytesBeforeStripDebugInfoName,                         \
         internalQueryCacheMaxSizeBytesBeforeStripDebugInfo,                              \
         getCacheMaxSizeBytesBeforeStripDebugInfo)                                        \
    KNOB(kCacheEvictionRatio,                                                             \
         kInternalQueryCacheEvictionRatioName,                                            \
         internalQueryCacheEvictionRatio,                                                 \
         getCacheEvictionRatio)                                                           \
    KNOB(kCacheWorksGrowthCoefficient,                                                    \
         kInternalQueryCacheWorksGrowthCoefficientName,                                   \
         internalQueryCacheWorksGrowthCoefficient,                                        \
         getCacheWorksGrowthCoefficient)                                                  \
    KNOB(kCacheDisableInactiveEntries,                                                    \
         kInternalQueryCacheDisableInactiveEntriesName,                                   \
         internalQueryCacheDisableInactiveEntries,                                        \
         getCacheDisableInactiveEntries)                                                  \
    /* Parsing */                                                                         \
    KNOB(kPipelineLengthLimit,                                                            \
         kInternalPipelineLengthLimitName,                                                \
         internalPipelineLengthLimit,                                                     \
         getPipelineLengthLimit)                                                          \
    KNOB(kMaxSubPipelineViewDepth,                                                        \
         kInternalMaxSubPipelineViewDepthName,                                            \
         internalMaxSubPipelineViewDepth,                                                 \
         getMaxSubPipelineViewDepth)                                                      \
    KNOB(kPartialFilterExpressionMaxDepth,                                                \
         kInternalPartialFilterExpressionMaxDepthName,                                    \
         internalPartialFilterExpressionMaxDepth,                                         \
         getPartialFilterExpressionMaxDepth)                                              \
    /* Planning and enumeration continued */                                              \
    KNOB(kEnumerationMaxOrSolutions,                                                      \
         kInternalQueryEnumerationMaxOrSolutionsName,                                     \
         internalQueryEnumerationMaxOrSolutions,                                          \
         getEnumerationMaxOrSolutions)                                                    \
    KNOB(kEnumerationMaxIntersectPerAnd,                                                  \
         kInternalQueryEnumerationMaxIntersectPerAndName,                                 \
         internalQueryEnumerationMaxIntersectPerAnd,                                      \
         getEnumerationMaxIntersectPerAnd)                                                \
    KNOB(kIgnoreUnknownJSONSchemaKeywords,                                                \
         kInternalQueryIgnoreUnknownJSONSchemaKeywordsName,                               \
         internalQueryIgnoreUnknownJSONSchemaKeywords,                                    \
         getIgnoreUnknownJSONSchemaKeywords)                                              \
    KNOB(kPlannerIgnoreIndexWithCollationForRegex,                                        \
         kInternalQueryPlannerIgnoreIndexWithCollationForRegexName,                       \
         internalQueryPlannerIgnoreIndexWithCollationForRegex,                            \
         getPlannerIgnoreIndexWithCollationForRegex)                                      \
    KNOB(kExplainJoinCostComponents,                                                      \
         kInternalQueryExplainJoinCostComponentsName,                                     \
         internalQueryExplainJoinCostComponents,                                          \
         getExplainJoinCostComponents)                                                    \
    /* Join optimization */                                                               \
    KNOB(kEnableJoinOptimization,                                                         \
         kInternalEnableJoinOptimizationName,                                             \
         internalEnableJoinOptimization,                                                  \
         isJoinOrderingEnabled)                                                           \
    KNOB(kRandomJoinOrderSeed,                                                            \
         kInternalRandomJoinOrderSeedName,                                                \
         internalRandomJoinOrderSeed,                                                     \
         getRandomJoinOrderSeed)                                                          \
    KNOB(kMaxNodesInJoinGraph,                                                            \
         kInternalMaxNodesInJoinGraphName,                                                \
         internalMaxNodesInJoinGraph,                                                     \
         getMaxNodesInJoinGraph)                                                          \
    KNOB(kMaxEdgesInJoinGraph,                                                            \
         kInternalMaxEdgesInJoinGraphName,                                                \
         internalMaxEdgesInJoinGraph,                                                     \
         getMaxEdgesInJoinGraph)                                                          \
    KNOB(kInferSingleTablePredicates,                                                     \
         kInternalInferSingleTablePredicatesName,                                         \
         internalInferSingleTablePredicates,                                              \
         getInferSingleTablePredicates)                                                   \
    KNOB(kMaxNumberNodesConsideredForImplicitEdges,                                       \
         kInternalMaxNumberNodesConsideredForImplicitEdgesName,                           \
         internalMaxNumberNodesConsideredForImplicitEdges,                                \
         getMaxNumberNodesConsideredForImplicitEdges)                                     \
    KNOB(kEnableJoinEnumerationHJOrderPruning,                                            \
         kInternalEnableJoinEnumerationHJOrderPruningName,                                \
         internalEnableJoinEnumerationHJOrderPruning,                                     \
         getEnableJoinEnumerationHJOrderPruning)                                          \
    KNOB(kEnableJoinOptimizationUseIndexUniqueness,                                       \
         kInternalEnableJoinOptimizationUseIndexUniquenessName,                           \
         internalEnableJoinOptimizationUseIndexUniqueness,                                \
         getEnableJoinOptimizationUseIndexUniqueness)                                     \
    KNOB(kJoinPlanSamplingSize,                                                           \
         kInternalJoinPlanSamplingSizeName,                                               \
         internalJoinPlanSamplingSize,                                                    \
         getInternalJoinPlanSamplingSize)                                                 \
    KNOB(kJoinEnumerateCollScanPlans,                                                     \
         kInternalJoinEnumerateCollScanPlansName,                                         \
         internalJoinEnumerateCollScanPlans,                                              \
         getInternalJoinEnumerateCollScanPlans)                                           \
    KNOB(kEnableJoinPlanCache,                                                            \
         kInternalEnableJoinPlanCacheName,                                                \
         internalEnableJoinPlanCache,                                                     \
         getEnableJoinPlanCache)                                                          \
    /* Sampling / cardinality estimation */                                               \
    KNOB(kSamplingMarginOfError,                                                          \
         kSamplingMarginOfErrorName,                                                      \
         samplingMarginOfError,                                                           \
         getSamplingMarginOfError)                                                        \
    KNOB(kSamplingSizeOverride,                                                           \
         kInternalSamplingSizeOverrideName,                                               \
         internalSamplingSizeOverride,                                                    \
         getSamplingSizeOverride)                                                         \
    KNOB(kNumChunksForChunkBasedSampling,                                                 \
         kInternalQueryNumChunksForChunkBasedSamplingName,                                \
         internalQueryNumChunksForChunkBasedSampling,                                     \
         getNumChunksForChunkBasedSampling)                                               \
    /* Pipeline rewrites */                                                               \
    KNOB(kEnablePathArrayness,                                                            \
         kInternalEnablePathArraynessName,                                                \
         internalEnablePathArrayness,                                                     \
         getEnablePathArrayness)                                                          \
    KNOB(kEnablePipelineOptimizationAdditionalTestingRules,                               \
         kInternalEnablePipelineOptimizationAdditionalTestingRulesName,                   \
         internalEnablePipelineOptimizationAdditionalTestingRules,                        \
         getEnablePipelineOptimizationAdditionalTestingRules)                             \
    /* cpp_class enum knobs */                                                            \
    KNOB(kPlanRanker,                                                                     \
         kInternalQueryPlanRankerName,                                                    \
         QueryPlanRanker,                                                                 \
         getPlanRanker)                                                                   \
    KNOB(kCBRCEMode,                                                                      \
         kInternalQueryCBRCEModeName,                                                     \
         QueryCBRCEMode,                                                                  \
         getCBRCEMode)                                                                    \
    KNOB(kPlanRankingStrategyForAutomaticQueryPlanRankerMode,                             \
         kAutomaticCEPlanRankingStrategyName,                                             \
         QueryPlanRankingStrategyForAutomaticQueryPlanRankerMode,                         \
         getPlanRankingStrategyForAutomaticQueryPlanRankerMode)                           \
    KNOB(kSamplingConfidenceInterval,                                                     \
         kSamplingConfidenceIntervalName,                                                 \
         SamplingConfidenceInterval,                                                      \
         getConfidenceInterval)                                                           \
    KNOB(kSamplingCEMethod,                                                               \
         kInternalQuerySamplingCEMethodName,                                              \
         CBRSamplingCEMethod,                                                             \
         getInternalQuerySamplingCEMethod)                                                \
    KNOB(kJoinReorderMode,                                                                \
         kInternalJoinReorderModeName,                                                    \
         JoinReorderMode,                                                                 \
         getJoinReorderMode)                                                              \
    KNOB(kJoinPlanTreeShape,                                                              \
         kInternalJoinPlanTreeShapeName,                                                  \
         JoinPlanTreeShape,                                                               \
         getJoinPlanTreeShape)                                                            \
    KNOB(kJoinMethod,                                                                     \
         kInternalJoinMethodName,                                                         \
         ForcedJoinMethod,                                                                \
         getJoinMethod)                                                                   \
    KNOB(kJoinSamplingCEMethod,                                                           \
         kInternalJoinOptimizationSamplingCEMethodName,                                   \
         JoinSamplingCEMethod,                                                            \
         getInternalJoinOptimizationSamplingCEMethod)                                     \
    /* Boolean simplification */                                                          \
    KNOB(kEnableBooleanExpressionsSimplifier,                                             \
         kInternalQueryEnableBooleanExpressionsSimplifierName,                            \
         internalQueryEnableBooleanExpressionsSimplifier,                                 \
         getEnableBooleanExpressionsSimplifier)                                           \
    KNOB(kMaximumNumberOfUniquePredicatesToSimplify,                                      \
         kInternalQueryMaximumNumberOfUniquePredicatesToSimplifyName,                     \
         internalQueryMaximumNumberOfUniquePredicatesToSimplify,                          \
         getMaximumNumberOfUniquePredicatesToSimplify)                                    \
    KNOB(kMaximumNumberOfMintermsInSimplifier,                                            \
         kInternalQueryMaximumNumberOfMintermsInSimplifierName,                           \
         internalQueryMaximumNumberOfMintermsInSimplifier,                                \
         getMaximumNumberOfMintermsInSimplifier)                                          \
    KNOB(kMaxNumPrimeImplicants,                                                          \
         kInternalQueryMaxNumPrimeImplicantsName,                                         \
         internalQueryMaxNumPrimeImplicants,                                              \
         getMaxNumPrimeImplicants)                                                        \
    KNOB(kMaxSizeFactorToSimplify,                                                        \
         kInternalQueryMaxSizeFactorToSimplifyName,                                       \
         internalQueryMaxSizeFactorToSimplify,                                            \
         getMaxSizeFactorToSimplify)                                                      \
    KNOB(kDoNotOpenContainedOrsInSimplifier,                                              \
         kInternalQueryDoNotOpenContainedOrsInSimplifierName,                             \
         internalQueryDoNotOpenContainedOrsInSimplifier,                                  \
         getDoNotOpenContainedOrsInSimplifier)                                            \
    /* Other optimization settings */                                                     \
    KNOB(kAutoParameterizationMaxParameterCount,                                          \
         kInternalQueryAutoParameterizationMaxParameterCountName,                         \
         internalQueryAutoParameterizationMaxParameterCount,                              \
         getAutoParameterizationMaxParameterCount)                                        \
    KNOB(kEnableCSTParser,                                                                \
         kInternalQueryEnableCSTParserName,                                               \
         internalQueryEnableCSTParser,                                                    \
         getEnableCSTParser)                                                              \
    KNOB(kExtraPredicateForReversedIn,                                                    \
         kInternalQueryExtraPredicateForReversedInName,                                   \
         internalQueryExtraPredicateForReversedIn,                                        \
         getExtraPredicateForReversedIn)                                                  \
    KNOB(kPermitMatchSwappingForComplexRenames,                                           \
         kInternalQueryPermitMatchSwappingForComplexRenamesName,                          \
         internalQueryPermitMatchSwappingForComplexRenames,                               \
         getPermitMatchSwappingForComplexRenames)                                         \
    KNOB(kPlannerPushdownFilterToIxscanForSort,                                           \
         kInternalQueryPlannerPushdownFilterToIxscanForSortName,                          \
         internalQueryPlannerPushdownFilterToIxscanForSort,                               \
         getPlannerPushdownFilterToIxscanForSort)                                         \
    KNOB(kTransformHoistPolicy,                                                           \
         kInternalQueryTransformHoistPolicyName,                                          \
         TransformHoistPolicy,                                                            \
         getTransformHoistPolicy)                                                         \
    KNOB(kTransformHoistMaximumPaths,                                                     \
         kInternalQueryTransformHoistMaximumPathsName,                                    \
         internalQueryTransformHoistMaximumPaths,                                         \
         getTransformHoistMaximumPaths)                                                   \
    KNOB(kSamplingBySequentialScan,                                                       \
         kInternalQuerySamplingBySequentialScanName,                                      \
         internalQuerySamplingBySequentialScan,                                           \
         getSamplingBySequentialScan)                                                     \
    KNOB(kSamplingByStrides,                                                              \
         kInternalQuerySamplingByStridesName,                                             \
         internalQuerySamplingByStrides,                                                  \
         getSamplingByStrides)                                                            \
    KNOB(kNumWorksPerPlanForMPEstimation,                                                 \
         kInternalQueryNumWorksPerPlanForMPEstimationName,                                \
         internalQueryNumWorksPerPlanForMPEstimation,                                     \
         getNumWorksPerPlanForMPEstimation)                                               \
    KNOB(kMinRequiredImprovementRatioForCostBasedRankerChoice,                            \
         kInternalQueryMinRequiredImprovementRatioForCostBasedRankerChoiceName,           \
         internalQueryMinRequiredImprovementRatioForCostBasedRankerChoice,                \
         getMinRequiredImprovementRatioForCostBasedRankerChoice)                          \
    KNOB(kMaxPipelineRewrites,                                                            \
         kInternalQueryMaxPipelineRewritesName,                                           \
         internalQueryMaxPipelineRewrites,                                                \
         getMaxPipelineRewrites)                                                          \
    KNOB(kEnableDependencyGraphValidation,                                                \
         kInternalEnableDependencyGraphValidationName,                                    \
         internalEnableDependencyGraphValidation,                                         \
         getEnableDependencyGraphValidation)                                              \
    KNOB(kNoTableScan,                                                                    \
         kNotablescanName,                                                                \
         gKnobNoTableScan,                                                                \
         getNoTableScan)                                                                  \
    /* End MONGO_EXPAND_QUERY_KNOBS_OPTIMIZATION */
// clang-format on

namespace mongo::query_knobs {
DECLARE_QUERY_KNOBS(QueryOptimizationKnobs, MONGO_EXPAND_QUERY_KNOBS_OPTIMIZATION)
}  // namespace mongo::query_knobs
