# -*- mode: python -*-

Import(
    [
        "env",
    ]
)

env = env.Clone()

env.SConscript(
    must_exist=1,
    dirs=[
        "boolean_simplification",
        "bson",
        "ce",
        "client_cursor",
        "collation",
        "cost_based_ranker",
        "datetime",
        "optimizer",
        "plan_cache",
        "query_settings",
        "query_stats",
        "query_shape",
        "query_tester",
        "search",
        "stage_builder/sbe",
        "stats",
        "virtual_collection",
        "write_ops",
    ],
    exports=[
        "env",
    ],
)

env.CppUnitTest(
    target="express_execution_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="db_query_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="canonical_query_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)

env.Benchmark(
    target="query_planner_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)

env.Benchmark(
    target="point_query_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)

env.Benchmark(
    target="complex_query_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)
