# -*- mode: python -*-

Import('env')

env.Library(
    target='watchdog',
    source=[
        'watchdog.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/service_context',
        '$BUILD_DIR/mongo/db/storage/storage_options',
    ]
)

env.Library(
    target='watchdog_register',
    source=[
        'watchdog_register.cpp',
    ],
)

env.Library(
    target='watchdog_mongod',
    source=[
        'watchdog_mongod.cpp',
        env.Idlc('watchdog_mongod.idl')[0],
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/commands/server_status',
        'watchdog',
        ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/server_options_core',
        '$BUILD_DIR/mongo/idl/server_parameter',
        'watchdog_register',
        ],
)

env.CppUnitTest(
    target='watchdog_test',
    source=[
        'watchdog_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/service_context_test_fixture',
        '$BUILD_DIR/mongo/util/clock_source_mock',
        'watchdog',
    ],
)
