# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="immutable_test",
    source=[],
    LIBDEPS=[],
    PROVE_ALIASES=["server-programmability"],
)

env.Benchmark(
    target="immutable_absl_comparison_bm",
    source=[],
)

env.Benchmark(
    target="immutable_std_comparison_bm",
    source=[],
)
