# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target='immutable_test',
    source=[
        'immutable_ordered_test.cpp',
        'immutable_unordered_test.cpp',
        'immutable_vector_test.cpp',
    ],
    LIBDEPS=[],
)

env.Benchmark(
    target='immutable_absl_comparison_bm',
    source=[
        'immutable_absl_comparison_bm.cpp',
    ],
)

env.Benchmark(
    target='immutable_std_comparison_bm',
    source=[
        'immutable_std_comparison_bm.cpp',
    ],
)
