# -*- mode: python; -*-

Import("env")

env = env.Clone()

# Should not be referenced outside this SConscript file.
env.Library(
    target='kv_engine_core',
    source=[
        'kv_catalog.cpp',
        'kv_collection_catalog_entry.cpp',
        ],
    LIBDEPS=[
        '$BUILD_DIR/bongo/bson/util/bson_extract',
        '$BUILD_DIR/bongo/db/concurrency/lock_manager',
        '$BUILD_DIR/bongo/db/index/index_descriptor',
        '$BUILD_DIR/bongo/db/index_names',
        '$BUILD_DIR/bongo/db/namespace_string',
        '$BUILD_DIR/bongo/db/storage/bson_collection_catalog_entry',
        ],
    )

# Should not be referenced outside this SConscript file.
env.Library(
    target='kv_database_catalog_entry_core',
    source=['kv_database_catalog_entry_base.cpp'],
    LIBDEPS=[
        '$BUILD_DIR/bongo/base',
        '$BUILD_DIR/bongo/db/storage/bson_collection_catalog_entry',
        '$BUILD_DIR/bongo/db/storage/kv/kv_engine_core',
    ],
)

# Should not be referenced outside this SConscript file.
env.Library(
    target='kv_storage_engine',
    source=['kv_storage_engine.cpp'],
    LIBDEPS=[
        '$BUILD_DIR/bongo/base',
        '$BUILD_DIR/bongo/db/storage/kv/kv_engine_core',
        '$BUILD_DIR/bongo/db/storage/storage_options',
        'kv_database_catalog_entry_core',
    ],
)

env.Library(
    target='kv_engine',
    source=[
        'kv_database_catalog_entry.cpp',
        ],
    LIBDEPS=[
        '$BUILD_DIR/bongo/db/index/index_access_methods',
        'kv_database_catalog_entry_core',
        'kv_engine_core',
        'kv_storage_engine',
        ],
    )

# Stubs out KVDatabaseCatalogEntry::getIndex() for testing.
# Should not be referenced outside this SConscript file.
env.Library(
    target='kv_engine_mock',
    source=[
        'kv_database_catalog_entry_mock.cpp'
        ],
    LIBDEPS=[
        '$BUILD_DIR/bongo/db/storage/storage_options',
        'kv_database_catalog_entry_core',
        'kv_engine_core',
        'kv_storage_engine',
        ]
    )

env.Library(
    target='kv_engine_test_harness',
    source=[
        'kv_catalog_feature_tracker_test.cpp',
        'kv_engine_test_harness.cpp',
        'kv_engine_test_snapshots.cpp',
        ],
    LIBDEPS=[
        '$BUILD_DIR/bongo/db/service_context',
        '$BUILD_DIR/bongo/db/storage/storage_options',
        '$BUILD_DIR/bongo/unittest/unittest',
        '$BUILD_DIR/bongo/util/clock_source_mock',
        'kv_engine_mock',
        ],
    )

env.CppUnitTest(
    target='kv_database_catalog_entry_test',
    source=[
        'kv_database_catalog_entry_test.cpp',
        ],
    LIBDEPS=[
        'kv_engine_mock',
        '$BUILD_DIR/bongo/db/catalog/collection_options',
        '$BUILD_DIR/bongo/db/namespace_string',
        '$BUILD_DIR/bongo/db/storage/devnull/storage_devnull_core',
        '$BUILD_DIR/bongo/db/storage/ephemeral_for_test/ephemeral_for_test_record_store',
        ]
    )

env.CppUnitTest(
    target='kv_collection_catalog_entry_test',
    source=[
        'kv_collection_catalog_entry_test.cpp',
        ],
    LIBDEPS=[
        'kv_engine_mock',
        '$BUILD_DIR/bongo/db/catalog/collection_options',
        '$BUILD_DIR/bongo/db/namespace_string',
        '$BUILD_DIR/bongo/db/storage/devnull/storage_devnull_core',
        '$BUILD_DIR/bongo/db/storage/ephemeral_for_test/ephemeral_for_test_record_store',
        ]
    )
