# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/util/net/hostandport.h"
types:
    HostAndPort:
        bson_serialization_type: string
        description: A string representing a host and port of a mongod or mongos process.
        cpp_type: HostAndPort
        serializer: HostAndPort::toString
        deserializer: HostAndPort::parseThrowing
        is_view: false
