# Copyright (C) 2025-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    mod_visibility: pub
    cpp_namespace: "mongo::extension"
    cpp_includes:
        - "mongo/db/extension/public/api.h"

imports:
    - "mongo/db/basic_types.idl"

enums:
    MongoExtensionPositionRequirement:
        description: >-
            What specific position the stage must occupy within the pipeline, if any.
        type: string
        values:
            kNone: "none"
            kFirst: "first"
            kLast: "last"
    MongoExtensionHostTypeRequirement:
        description: >-
            Where the stage is permitted to be run in a sharded cluster.
        type: string
        values:
            kNone: "none"
            kLocalOnly: "localOnly"
            kRunOnceAnyNode: "runOnceAnyNode"
            kAnyShard: "anyShard"
            kRouter: "router"
            kAllShardHosts: "allShardHosts"
    MongoExtensionPrivilegeResourcePattern:
        description: What resource the privilege applies to.
        type: string
        values:
            kNamespace: "namespace"
    MongoExtensionPrivilegeAction:
        description: >-
            Allowed actions for this stage. Currently, these are constrained to read-only actions
            on a specific namespace.
        type: string
        values:
            kFind: "find"
            kListIndexes: "listIndexes"
            kListSearchIndexes: "listSearchIndexes"
            kPlanCacheRead: "planCacheRead"
            kCollStats: "collStats"
            kIndexStats: "indexStats"

structs:
    MongoExtensionPrivilegeActionEntry:
        description: >-
            Represents one allowed action entry in the requiredPrivilege field.
            Each entry wraps a MongoExtensionPrivilegeAction enum to satisfy the IDL restriction
            that arrays cannot directly contain enums.
        fields:
            action:
                type: MongoExtensionPrivilegeAction
    MongoExtensionRequiredPrivilege:
        description: A constrained privilege specification.
        fields:
            resourcePattern:
                description: Kinds of resources targetable by the access control system.
                type: MongoExtensionPrivilegeResourcePattern
            actions:
                description: Actions required on the target.
                type: array<MongoExtensionPrivilegeActionEntry>
    MongoExtensionStaticProperties:
        description: >-
            Properties specified by the extension that remain static throughout its lifetime, such as
            stage constraints (where the stage can run, where it must be in the pipeline, what
            resources it may require, etc.)
        strict: false
        fields:
            position:
                description: What position the stage must occupy in the pipeline.
                type: MongoExtensionPositionRequirement
                default: kNone
            hostType:
                description: Where the stage can be executed when the pipeline is run in a sharded cluster.
                type: MongoExtensionHostTypeRequirement
                default: kNone
            requiresInputDocSource:
                description: >-
                    Whether this stage requires an input document source (i.e., it does not generate
                    results itself, and must imstead pull inputs from an input DocumentSource).
                type: bool
                default: true
            requiredPrivileges:
                type: array<MongoExtensionRequiredPrivilege>
                optional: true
