# -*- mode: python -*-

Import("env")

env.Library(
    target="document_value_test_util",
    source=[
        "document_value_test_util.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/unittest/unittest",
        "document_value",
    ],
)

env.Benchmark(
    target="document_bm",
    source=[
        "document_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/concurrency/lock_manager",
        "$BUILD_DIR/mongo/db/server_base",
        "document_value",
    ],
)
