# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='router_session',
    source=[
        'router_transaction_state.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/logical_session_id',
        '$BUILD_DIR/mongo/db/repl/read_concern_args',
        '$BUILD_DIR/mongo/s/common_s',
    ],
)

env.CppUnitTest(
    target='router_transaction_test',
    source=[
        'router_transaction_state_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/s/sharding_router_test_fixture',
        'router_session',
    ]
)
