# Copyright (C) 2023-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/session/logical_session_id.idl"
    - "mongo/s/database_version.idl"

enums:
    MultiUpdateCoordinatorPhase:
        description: The phase of a MultiUpdateCoordinator.
        type: string
        values:
            kUnused: "unused"
            kAcquireSession: "acquireSession"
            kBlockMigrations: "blockMigrations"
            kPerformUpdate: "performUpdate"
            kCleanup: "cleanup"
            kDone: "done"

structs:
    MultiUpdateCoordinatorMetadata:
        description: Contains immutable fields for a MultiUpdateCoordinator.
        strict: false
        fields:
            _id:
                type: uuid
                description: Unique identifier for the operation. 
                cpp_name: id
            updateCommand:
                type: object_owned
                description: The original multi update command that triggered the coordinator.
            ns:
                cpp_name: nss
                type: namespacestring
                description: "The namespace of the collection being updated."

    MultiUpdateCoordinatorMutableFields:
        description: Contains mutable fields for a MultiUpdateCoordinator.
        strict: false
        fields:
            phase:
                type: MultiUpdateCoordinatorPhase
                description: The phase of the MultiUpdateCoordinator.
                default: kUnused
            result:
                type: object_owned
                description: >-
                    Stores the result of the underlying update command.
                optional: true
            lsid:
                type: LogicalSessionId
                description: "The sessionId to track this update."
                optional: true
            txnNumber:
                type: TxnNumber
                description: "The txnNumber for the update session."
                optional: true

    MultiUpdateCoordinatorDocument:
        description: State document for MultiUpdateCoordinator.
        strict: false        
        inline_chained_structs: true
        chained_structs:
            MultiUpdateCoordinatorMetadata: metadata
        fields:
            mutableFields:
                type: MultiUpdateCoordinatorMutableFields
                default: true
