# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='batch_write_types',
    source=[
        'batched_command_request.cpp',
        'batched_command_response.cpp',
        'batched_upsert_detail.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/commands',
        '$BUILD_DIR/mongo/db/common',
        '$BUILD_DIR/mongo/db/error_labels',
        '$BUILD_DIR/mongo/db/ops/write_ops_parsers',
        '$BUILD_DIR/mongo/db/repl/optime',
        '$BUILD_DIR/mongo/db/vector_clock',
        '$BUILD_DIR/mongo/rpc/command_status',
        '$BUILD_DIR/mongo/s/common_s',
    ],
)

env.Library(
    target='write_without_shard_key_util',
    source=[
        'write_without_shard_key_util.cpp',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/s/grid',
    ],
)

env.Library(
    target='cluster_write_ops',
    source=[
        'batch_write_exec.cpp',
        'batch_write_op.cpp',
        'write_op.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/commands/server_status_core',
        '$BUILD_DIR/mongo/db/pipeline/pipeline',
        '$BUILD_DIR/mongo/db/pipeline/process_interface/mongos_process_interface',
        '$BUILD_DIR/mongo/s/sharding_router_api',
        'batch_write_types',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/catalog/collection_uuid_mismatch_info',
    ],
)
