# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# abortReshardCollection IDL file

global:
    mod_visibility: private
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/s/resharding/common_types.idl"

commands:
    abortReshardCollection:
        description: "The public abortReshardCollection command on mongos."
        command_name: abortReshardCollection
        strict: true
        namespace: type
        api_version: ""
        type: namespacestring

    _configsvrAbortReshardCollection:
        command_name: _configsvrAbortReshardCollection
        cpp_name: ConfigsvrAbortReshardCollection
        description: "The internal abortReshardCollection command on the config server."
        strict: false
        namespace: type
        api_version: ""
        type: namespacestring
        fields:
            provenance:
                type: ReshardingProvenance
                description: "The source operation that called this resharding operation."
                optional: true

    _shardsvrAbortReshardCollection:
        command_name: _shardsvrAbortReshardCollection
        cpp_name: ShardsvrAbortReshardCollection
        description: "The internal command used by resharding coordinator to abort participants."
        strict: false
        namespace: type
        api_version: ""
        type: uuid
        reply_type: OkReply
        fields:
            userCanceled:
                type: bool
                optional: false
                description: "Determines whether the resharding opertion was user aborted."

    abortMoveCollection:
        description: "The public command on mongos that aborts a moveCollection commmand."
        command_name: abortMoveCollection
        strict: false
        namespace: type
        api_version: ""
        type: namespacestring

    abortRewriteCollection:
        description: "The public command on mongos that aborts a rewriteCollection commmand."
        command_name: abortRewriteCollection
        strict: false
        namespace: type
        api_version: ""
        type: namespacestring

    abortUnshardCollection:
        description: "The public command on mongos that aborts a unshardCollection commmand."
        command_name: abortUnshardCollection
        strict: false
        namespace: type
        api_version: ""
        type: namespacestring
