# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# This IDL file describes the BSON format for the autoSplitVector command.

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/s/auto_split_vector.h"

imports:
    - "mongo/db/basic_types.idl"

types:
    bson_vector:
        bson_serialization_type: any
        description: "An array of objects representing the split keys."
        cpp_type: "std::vector<mongo::BSONObj>"
        deserializer: ::mongo::parseSplitKeys
        # Deserializer uses getOwned.
        is_view: false

structs:
    AutoSplitVectorResponse:
        description: "The reply of an autoSplitVector command."
        mod_visibility: public
        strict: false
        is_command_reply: true
        fields:
            splitKeys: bson_vector
            continuation:
                type: bool
                description: "Whether there are more split points available for the requested range"

commands:
    autoSplitVector:
        command_name: autoSplitVector
        cpp_name: AutoSplitVectorRequest
        description: "Returns the split points for a chunk, given a range and the maximum chunk size."
        strict: false
        namespace: concatenate_with_db
        api_version: ""
        mod_visibility: public
        fields:
            keyPattern:
                type: object_owned
                description: "Shard key pattern of the collection"
            min:
                type: object_owned
                description: "Min key of the chunk"
            max:
                type: object_owned
                description: "Max key of the chunk"
            maxChunkSizeBytes:
                type: safeInt64
                description: "Max chunk size of the collection expressed in bytes"
            limit:
                type: int
                description: "Max number of split points to look for"
                optional: true
