# Copyright (C) 2020-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/drop_database.idl"
    - "mongo/db/commands/rename_collection.idl"
    - "mongo/idl/basic_types.idl"
    - "mongo/s/chunk_version.idl"
    - "mongo/s/database_version.idl"
    - "mongo/s/chunk_version.idl"

structs:
    RenameCollectionResponse:
        description: "Response for the rename collection command"
        strict: false
        fields:
            collectionVersion:
                type: ChunkVersion
                description: "Latest version of the collection"
                optional: false

    CreateCollectionResponse:
        description: "Response of the create collection command"
        strict: false
        fields:
            collectionUUID:
                type: uuid
                description: "UUID of the created collection"
                optional: true
            collectionVersion:
                type: ChunkVersion
                description: "Latest version of the collection"
                optional: false

commands:
    _shardsvrCreateCollection:
        command_name: _shardsvrCreateCollection
        cpp_name: ShardsvrCreateCollection
        description: "The internal createCollection command for a shard."
        strict: false
        namespace: concatenate_with_db
        fields:
            shardKey:
                type: object
                description: "The index specification document to use as the shard key."
                optional: true
            unique:
                type: bool
                description: "Whether the shard key index should enforce a unique constraint"
                optional: true
            numInitialChunks:
                type: safeInt64
                description: "The number of chunks to create initially when sharding an empty collection with a hashed shard key."
                optional: true
            presplitHashedZones:
                type: bool
                description: "True if the chunks should be pre-split based on the existing zones when sharding a collection with hashed shard key"
                optional: true
            initialSplitPoints:
                type: array<object>
                description: "A specific set of points to create initial splits at, currently used only by mapReduce"
                optional: true
            collation:
                type: object
                description: "The collation to use for the shard key index."
                optional: true

    _shardsvrDropDatabase:
        description: "Parser for the shardDropDatabase command"
        command_name: _shardsvrDropDatabase
        namespace: type
        type: safeInt64
        cpp_name: ShardsvrDropDatabase
        reply_type: DropDatabaseReply

    _shardsvrDropCollection:
        description: "Parser for the _shardsvrDropCollection command"
        command_name: _shardsvrDropCollection
        namespace: concatenate_with_db
        cpp_name: ShardsvrDropCollection
        strict: true
        reply_type: DropDatabaseReply

    _shardsvrRenameCollection:
        command_name: _shardsvrRenameCollection
        cpp_name: ShardsvrRenameCollection
        description: "Internal renameCollection command for a shard."
        strict: false
        namespace: concatenate_with_db
        fields:
            to:
                type: namespacestring
                description: "The new namespace for the collection being renamed."
            dropTarget:
                type: bool
                description: "If true, mongod will drop the target of renameCollection prior to
                renaming the collection."
                default: false
            stayTemp:
                type: bool
                description: "If true, the original collection will remain temp if it was temp
                before the rename."
                default: false
