# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    mod_visibility: private
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/s/request_types/update_zone_key_range_serialization.h"

imports:
    - "mongo/db/basic_types.idl"

types:
    StringOrNull:
        bson_serialization_type: any
        description: "Either a string or null."
        cpp_type: boost::optional<std::string>
        serializer: "::mongo::stringOrNullSerializeToBSON"
        deserializer: "::mongo::stringOrNullParseFromBSON"

commands:
    updateZoneKeyRange:
        description: "The public updateZoneKeyRange command to update zone key ranges for a collection on mongos."
        strict: true
        namespace: type
        command_name: updateZoneKeyRange
        api_version: ""
        type: namespacestring
        fields:
            min:
                description: "Inclusive lower bound of the range of shard key values."
                type: object
            max:
                description: "Exclusive upper bound of the range of shard key values."
                type: object
            zone:
                description: "The name of the zone to be updated."
                type: StringOrNull

    _configsvrUpdateZoneKeyRange:
        description: "The internal updateZoneKeyRange command to update zone key ranges for a collection on the config server."
        strict: false
        namespace: type
        command_name: _configsvrUpdateZoneKeyRange
        cpp_name: ConfigsvrUpdateZoneKeyRange
        api_version: ""
        type: namespacestring
        fields:
            min:
                description: "Inclusive lower bound of the range of shard key values."
                type: object
            max:
                description: "Exclusive upper bound of the range of shard key values."
                type: object
            zone:
                description: "The name of the zone to be updated."
                type: StringOrNull
