# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0
global:
    cpp_namespace: "mongo"
    mod_visibility: public

enums:
    AccessCheck:
        description: "List of supported access checks in AuthorizationSession"
        type: string
        values:
            kCheckAuthorizedToListCollections: "check_authorized_to_list_collections"
            kCheckCursorSessionPrivilege: "check_cursor_session_privilege"
            kGetAuthenticatedRoleNames: "get_authenticated_role_names"
            kGetAuthenticatedUserName: "get_authenticated_user_name"
            kGetAuthenticatedUser: "get_authenticated_user"
            kIsAuthenticated: "is_authenticated"
            kIsAuthenticatedAsUserWithRole: "is_authenticated_as_user_with_role"
            kIsAuthorizedForAnyActionOnAnyResourceInDB: "is_authorized_for_any_action_on_any_resource_in_db"
            kIsAuthorizedForAnyActionOnResource: "is_authorized_for_any_action_on_resource"
            kIsAuthorizedToChangeAsUser: "is_authorized_to_change_as_user"
            kIsAuthorizedToCreateRole: "is_authorized_to_create_role"
            kIsAuthorizedToParseNamespaceElement: "is_authorized_to_parse_namespace_element"
            kIsCoAuthorized: "is_coauthorized"
            kIsCoauthorizedWith: "is_coauthorized_with"
            kIsCoauthorizedWithClient: "is_coauthorized_with_client"
            kIsImpersonating: "is_impersonating"
            kIsUsingLocalhostBypass: "is_using_localhost_bypass" # Called in common code in commands.cpp dispatch
            kLookupUser: "lookup_user"
            kShouldIgnoreAuthChecks: "should_ignore_auth_checks"
