# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/util/net/http_client.h"
    mod_visibility: public

imports:
    - "mongo/db/basic_types.idl"

structs:
    OAuthAuthorizationServerMetadata:
        description: "Information advertised from an RFC8414 compliant authorization server metadata endpoint"
        strict: false
        generate_comparison_operators: true
        fields:
            issuer:
                description: "The authorization server's issuer identifier"
                cpp_name: issuer
                type: string
                validator: {callback: "HttpClient::endpointIsSecure"}
            authorization_endpoint:
                description: "URL of the authorization server's authorization endpoint"
                cpp_name: authorizationEndpoint
                type: string
                optional: true
                validator: {callback: "HttpClient::endpointIsSecure"}
            token_endpoint:
                description: "URL of the authorization server's token endpoint"
                cpp_name: tokenEndpoint
                type: string
                optional: true
                validator: {callback: "HttpClient::endpointIsSecure"}
            device_authorization_endpoint:
                description: "URL of the authorization server's device authorization endpoint"
                cpp_name: deviceAuthorizationEndpoint
                type: string
                optional: true
                validator: {callback: "HttpClient::endpointIsSecure"}
            jwks_uri:
                description: "URL of the authorization server's jwks endpoint"
                cpp_name: jwksUri
                type: string
                validator: {callback: "HttpClient::endpointIsSecure"}
