# Copyright (C) 2020-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#
global:
    cpp_namespace: "mongo::auth"
    cpp_includes:
    - "mongo/db/auth/sasl_payload.h"

imports:
    - "mongo/idl/basic_types.idl"

types:
    SaslPayload:
        description: "A base64 string or BinData value"
        bson_serialization_type: any
        cpp_type: SaslPayload
        deserializer: "mongo::auth::SaslPayload::parseFromBSON"
        serializer: "mongo::auth::SaslPayload::serializeToBSON"

structs:
    SaslReply:
        description: "Response for saslStart and saslContinue commands"
        strict: false
        is_command_reply: true
        fields:
            conversationId:
                # In practice, this field is always populated as 1.
                description: "Unique identifier for this SASL authentication session"
                type: int
                stability: stable
            done:
                description: "Whether or not the authentication has completed"
                type: bool
                stability: stable
            payload:
                description: "SASL payload"
                type: SaslPayload
                stability: stable

commands:
    saslStart:
        description: "Begin a SASL based authentication session"
        api_version: "1"
        access_check:
            none: true
        command_name: saslStart
        namespace: ignored
        cpp_name: SaslStartCommand
        reply_type: SaslReply
        strict: true
        fields:
            mechanism:
                description: "SASL mechanism used for authentication"
                type: string
                stability: stable
            autoAuthorize:
                # This field is ignored and assumed to always be true.
                description: "Automatically authorized user once authenticated"
                type: safeBool
                default: true
                stability: stable
            options:
                description: "SASL mechanism specific options"
                type: object_owned
                optional: true
                stability: stable
            payload:
                description: "Initial client message for SASL exchange"
                type: SaslPayload
                stability: stable

    saslContinue:
        description: "Continue a SASL based authentication session"
        api_version: "1"
        access_check:
            none: true
        command_name: saslContinue
        namespace: ignored
        cpp_name: SaslContinueCommand
        reply_type: SaslReply
        strict: true
        fields:
            conversationId:
                # This field is expected to be 1, any other value generates an error.
                description: "Unique identifier for this SASL authentication session"
                type: int
                stability: stable
            payload:
                description: "SASL payload"
                type: SaslPayload
                stability: stable
