# -*- mode: python; -*-

from functools import partial

import libdeps_tool as libdeps

Import("env")
Import("get_option")

env = env.Clone()

stitchSupportEnv = env.Clone()
if get_option("link-model") == "dynamic-sdk":
    # TODO(SERVER-59134): This fails to honor the libdeps-debug flag
    stitchSupportEnv["LIBDEPS_SHLIBEMITTER"] = partial(
        libdeps.libdeps_emitter,
        builder="SharedArchive",
        visibility_map=libdeps.dependency_visibility_honored,
    )

# Please see the note in ../mongo_embedded/SConscript about how to
# interpret and adjust the current and compatibility versions.
stitchSupportEnv.AppendUnique(
    SHLINKFLAGS=[
        "$MONGO_EXPORT_FILE_SHLINKFLAGS",
    ],
)

env.AutoInstall(
    "$PREFIX_INCLUDEDIR/stitch_support/v1/stitch_support",
    source=["stitch_support.h"],
    AIB_COMPONENT="stitch-support",
    AIB_ROLE="dev",
)

if get_option("link-model") != "dynamic-sdk":
    stitchSupportTestEnv = env.Clone()
    unitTest = stitchSupportTestEnv.CppUnitTest(
        target="stitch_support_test",
        source=[],
        UNITTEST_HAS_CUSTOM_MAINLINE=True,
        AIB_COMPONENT="stitch-support-test",
    )
