# -*- mode: python; -*-


Import("env")
Import("get_option")

env = env.Clone()

env.AutoInstall(
    "$PREFIX_INCLUDEDIR/stitch_support/v1/stitch_support",
    source=["stitch_support.h"],
    AIB_COMPONENT="stitch-support",
    AIB_ROLE="dev",
)

if get_option("link-model") != "dynamic-sdk":
    stitchSupportTestEnv = env.Clone()
    unitTest = stitchSupportTestEnv.CppUnitTest(
        target="stitch_support_test",
        source=[],
        UNITTEST_HAS_CUSTOM_MAINLINE=True,
        AIB_COMPONENT="stitch-support-test",
    )
