# -*- mode: python -*-

Import('env')

env = env.Clone()

timeZoneEnv = env.Clone()
timeZoneEnv.InjectThirdParty(libraries=['timelib'])
timeZoneEnv.Library(
    target='date_time_support',
    source=[
        'date_time_support.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/service_context',
        '$BUILD_DIR/third_party/shim_timelib',
    ]
)

timeZoneEnv.Library(
    target='init_timezone_data',
    source=[
        'init_timezone_data.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/server_options_core',
        '$BUILD_DIR/third_party/shim_timelib',
        'date_time_support',
    ]
)

timeZoneEnv.CppUnitTest(
    target='query_datetime_test',
    source=[
        'date_time_support_test.cpp',
    ],
    LIBDEPS=[
        'date_time_support',
    ]
)

timeZoneEnv.CppLibfuzzerTest(
    target='date_time_support_fuzzer',
    source=[
        'date_time_support_fuzzer.cpp',
    ],
    LIBDEPS=[
        'date_time_support',
    ]
)
