# -*- mode: python -*-

Import("env")

env = env.Clone()

timeZoneEnv = env.Clone()
timeZoneEnv.InjectThirdParty(libraries=["timelib"])
timeZoneEnv.CppUnitTest(
    target="date_time_support_test",
    source=[
        "date_time_support_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/concurrency/lock_manager",
        "$BUILD_DIR/mongo/transport/transport_layer_common",
        "date_time_support",
    ],
)

timeZoneEnv.CppLibfuzzerTest(
    target="date_time_support_fuzzer",
    source=[
        "date_time_support_fuzzer.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/concurrency/lock_manager",
        "$BUILD_DIR/mongo/transport/transport_layer_common",
        "date_time_support",
    ],
)
