// type declarations for query.js

declare class DBQuery {

    constructor(mongo, db, collection, ns, filter, projection, limit, skip, batchSize, options)

    addOption()
    allowDiskUse()
    allowPartialResults()
    arrayAccess()
    batchSize()
    clone()
    close()
    collation()
    comment()
    count()
    explain()
    forEach()
    getClusterTime()
    getId()
    hasNext()
    help()
    hint()
    isClosed()
    isExhausted()
    itcount()
    length()
    limit()
    map()
    max()
    maxTimeMS()
    min()
    next()
    noCursorTimeout()
    objsLeftInBatch()
    pretty()
    projection()
    rawData()
    readConcern()
    readOnly()
    readPref()
    returnKey()
    shellPrint()
    showDiskLoc()
    showRecordId()
    size()
    skip()
    sort()
    tailable()
    toArray()
    toString()
}
declare class DBCommandCursor {}
declare module QueryHelpers {}
declare var ___it___
