// type declarations for shell_utils_extended.h

declare function _copyFileRange()
declare function _getEnv()

/**
 * Retrieves the nth BSONObj in a BSON dump file
 * 
 * @param filename {String} filename of the dump file
 * @param n {Number} index of the object to retrieve
 * 
 * @returns {BSONObj} fetched object
 */
declare function _getObjInDumpFile()

/**
 * Retrieves the nth BSONObj from the BSON testing corpus.  The
 * corpus contains a variety of edge cases for testing BSON
 * interactions.  It is generated by //src/mongo/bson/util:bson_corpus
 * 
 * @param n {Number} index of the object to retrieve
 * 
 * @returns {BSONObj} fetched object
 */
declare function _getObjInCorpus()

/**
 * Retrieves the number of BSONObj in a BSON dump file
 * 
 * @param filename {String} filename of the dump file
 * 
 * @returns {Number} number of objects
 */
declare function _numObjsInDumpFile()

/**
 * Retrieves the number of BSONObj in the BSON testing corpus.  The
 * corpus contains a variety of edge cases for testing BSON
 * interactions.  It is generated by //src/mongo/bson/util:bson_corpus
 * 
 * @returns {Number} number of objects
 */
declare function _numObjsInCorpus()

declare function _readDumpFile()
declare function appendFile()
declare function cat()
declare function cd()
declare function copyDir()
declare function copyFile()
declare function decompressBSONColumn()
declare function getFileMode()
declare function getHostName()
declare function getStringWidth()
declare function hostname()
declare function listFiles()
declare function ls()
declare function md5sumFile()
declare function mkdir()
declare function passwordPrompt()
declare function pwd()
declare function removeFile()
declare function umask()
declare function writeFile()
