// type declarations for shell_utils_launcher.h

declare function _readTestPipes()
declare function _runMongoProgram()
declare function _runningMongoChildProcessIds()
declare function _startMongoProgram()
declare function _stopMongoProgram()
declare function _writeTestPipe()
declare function _writeTestPipeBsonFile()
declare function _writeTestPipeBsonFileSync()
declare function _writeTestPipeObjects()
declare function checkProgram()
declare function clearRawMongoProgramOutput()
declare function convertTrafficRecordingToBSON()
declare function copyDbpath()
declare function getFCVConstants()
declare function pathExists()
declare function rawMongoProgramOutput()
declare function resetDbpath()
declare function run()
declare function runNonMongoProgram()
declare function runNonMongoProgramQuietly()
declare function runProgram()
declare function stopMongoProgramByPid()
declare function waitMongoProgram()
declare function waitProgram()
declare function replayWorkloadRecordingFile()
