# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/versioning_protocol/chunk_version.idl"

structs:
    GossipedRoutingCache:
        description: Gossip metadata related to a node's collection routing table cache version.
        strict: false
        # This structure is private for the catalog_and_routing.router_role module, but due to the
        # way the service entry point is organized, it needs to know the names of the fields of
        # each subsystem, even if they are private. There should be a better way to achieve this
        # that's not exposing private details of the module.
        mod_visibility: needs_replacement
        fields:
            nss:
                description: The collection this gossip relates to.
                type: namespacestring
            collectionVersion:
                description: The cached collection routing table version.
                type: ChunkVersion
