# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='write_ops_exec',
    source=[
        'write_ops_exec.cpp',
        ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/catalog_raii',
        '$BUILD_DIR/mongo/db/curop',
        '$BUILD_DIR/mongo/db/repl/oplog',
        '$BUILD_DIR/mongo/db/repl/repl_coordinator_interface',
        '$BUILD_DIR/mongo/db/s/sharding_runtime_d',
        '$BUILD_DIR/mongo/db/write_ops',
        '$BUILD_DIR/mongo/util/fail_point',
    ],
)

env.Library(
    target='write_ops_parsers',
    source=[
        'write_ops_parsers.cpp',
        env.Idlc('write_ops.idl')[0],
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/dbmessage',
        '$BUILD_DIR/mongo/idl/idl_parser',
    ],
)

env.Library(
    target='write_ops_parsers_test_helpers',
    source=[
        'write_ops_parsers_test_helpers.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/dbmessage',
    ],
)

env.CppUnitTest(
    target='write_ops_parsers_test',
    source='write_ops_parsers_test.cpp',
    LIBDEPS=[
        'write_ops_parsers',
        'write_ops_parsers_test_helpers',
    ],
)

env.CppIntegrationTest(
    target='write_ops_document_stream_integration_test',
    source='write_ops_document_stream_integration_test.cpp',
    LIBDEPS=[
        '$BUILD_DIR/mongo/client/clientdriver',
        '$BUILD_DIR/mongo/util/version_impl',
    ],
)

env.CppUnitTest(
    target='write_ops_retryability_test',
    source='write_ops_retryability_test.cpp',
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/auth/authmocks',
        '$BUILD_DIR/mongo/db/query_exec',
        '$BUILD_DIR/mongo/db/repl/mock_repl_coord_server_fixture',
        '$BUILD_DIR/mongo/db/repl/oplog_entry',
    ],
)
