# -*- mode: python -*-

Import("env")

env.Library(
    target='lock_mgr',
    source=[
        'lock_mgr.cpp',
        'd_concurrency.cpp',
        'lock_stat.cpp',
        'lock_state.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base/base',
        '$BUILD_DIR/third_party/shim_boost',
        '$BUILD_DIR/mongo/foundation',
        '$BUILD_DIR/mongo/server_parameters'
    ],
)

