# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="lock_manager_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="exception_util_test",
    source=[],
    LIBDEPS=[],
    PROVE_ALIASES=["server-programmability"],
)

env.Benchmark(
    target="lock_manager_bm",
    source=[
        "lock_manager_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "lock_manager",
    ],
    CONSOLIDATED_TARGET="first_half_bm",
)

env.PrettyPrinterTest(target="lock_gdb_test.py")
