# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="lock_manager_test",
    source=[
        "fast_map_noalloc_test.cpp",
        "fill_locker_info_test.cpp",
        "lock_manager_test.cpp",
        "lock_stats_test.cpp",
        "locker_test.cpp",
        "resource_catalog_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/db/query/query_stats/query_stats",
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "$BUILD_DIR/mongo/db/service_context_test_fixture",
        "$BUILD_DIR/mongo/transport/transport_layer_common",
        "$BUILD_DIR/mongo/transport/transport_layer_mock",
        "exception_util",
        "lock_manager",
    ],
)

env.CppUnitTest(
    target="exception_util_test",
    source=[
        "exception_util_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/service_context_d_test_fixture",
        "$BUILD_DIR/mongo/transport/transport_layer_mock",
        "exception_util",
    ],
    PROVE_ALIASES=["server-programmability"],
)

env.Benchmark(
    target="lock_manager_bm",
    source=[
        "lock_manager_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "lock_manager",
    ],
    CONSOLIDATED_TARGET="first_half_bm",
)

env.PrettyPrinterTest(target="lock_gdb_test.py")
