# Image used by bazel remote execution hosts.

FROM ubuntu:20.04

RUN apt-get update && apt-get install -y build-essential

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libxml2-dev

CMD ["/bin/bash"]
