# -*- mode: python -*-

Import("env")

env = env.Clone()

mongotmock = env.BazelProgram(
    target="mongotmock",
    source=[],
    AIB_COMPONENT="mongotmock",
    AIB_COMPONENTS_EXTRA=["dist-test"],
)
