# -*- mode: python -*-

Import('env')

env = env.Clone()

env.Library(
    target='cst',
    source=[
        'bson_lexer.cpp',
        'c_node.cpp',
        'pipeline_parser_gen.cpp',
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
    ]
)

env.CppUnitTest(
    target='cst_test',
    source=[
        'cst_test.cpp',
    ],
    LIBDEPS=[
        'cst',
    ]
)
