load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "datagen",
    srcs = glob(["*.py"]),
    imports = [".."],
    deps = [
        "@pypi//:faker",
        "@pypi//:numpy",
        "@pypi//:pymongo",
    ],
)
