# DO NOT EDIT: automatically built by dist/stat.py. */

no_scale_per_second_list = [
    'async: current work queue length',
    'async: maximum work queue length',
    'cache: bytes currently in the cache',
    'cache: eviction currently operating in aggressive mode',
    'cache: files with active eviction walks',
    'cache: hazard pointer maximum array length',
    'cache: maximum bytes configured',
    'cache: maximum page size at eviction',
    'cache: pages currently held in the cache',
    'cache: percentage overhead',
    'cache: tracked bytes belonging to internal pages in the cache',
    'cache: tracked bytes belonging to leaf pages in the cache',
    'cache: tracked bytes belonging to overflow pages in the cache',
    'cache: tracked dirty bytes in the cache',
    'cache: tracked dirty pages in the cache',
    'connection: files currently open',
    'data-handle: connection data handles currently active',
    'log: maximum log file size',
    'log: number of pre-allocated log files to create',
    'log: total log buffer size',
    'LSM: application work units currently queued',
    'LSM: merge work units currently queued',
    'LSM: switch work units currently queued',
    'reconciliation: split bytes currently awaiting free',
    'reconciliation: split objects currently awaiting free',
    'session: open cursor count',
    'session: open session count',
    'thread-state: active filesystem fsync calls',
    'thread-state: active filesystem read calls',
    'thread-state: active filesystem write calls',
    'transaction: transaction checkpoint currently running',
    'transaction: transaction checkpoint generation',
    'transaction: transaction checkpoint max time (msecs)',
    'transaction: transaction checkpoint min time (msecs)',
    'transaction: transaction checkpoint most recent time (msecs)',
    'transaction: transaction checkpoint total time (msecs)',
    'transaction: transaction range of IDs currently pinned',
    'transaction: transaction range of IDs currently pinned by a checkpoint',
    'transaction: transaction range of IDs currently pinned by named snapshots',
    'block-manager: checkpoint size',
    'block-manager: file allocation unit size',
    'block-manager: file bytes available for reuse',
    'block-manager: file magic number',
    'block-manager: file major version number',
    'block-manager: file size in bytes',
    'block-manager: minor version number',
    'btree: btree checkpoint generation',
    'btree: column-store fixed-size leaf pages',
    'btree: column-store internal pages',
    'btree: column-store variable-size deleted values',
    'btree: column-store variable-size leaf pages',
    'btree: column-store variable-size RLE encoded values',
    'btree: fixed-record size',
    'btree: maximum internal page key size',
    'btree: maximum internal page size',
    'btree: maximum leaf page key size',
    'btree: maximum leaf page size',
    'btree: maximum leaf page value size',
    'btree: maximum tree depth',
    'btree: number of key/value pairs',
    'btree: overflow pages',
    'btree: row-store internal pages',
    'btree: row-store leaf pages',
    'cache: overflow values cached in memory',
    'LSM: bloom filters in the LSM tree',
    'LSM: chunks in the LSM tree',
    'LSM: highest merge generation in the LSM tree',
    'LSM: total size of bloom filters',
    'reconciliation: maximum blocks required for a page',
    'session: open cursor count',
]
no_clear_list = [
    'async: maximum work queue length',
    'cache: bytes currently in the cache',
    'cache: eviction currently operating in aggressive mode',
    'cache: files with active eviction walks',
    'cache: maximum bytes configured',
    'cache: maximum page size at eviction',
    'cache: pages currently held in the cache',
    'cache: percentage overhead',
    'cache: tracked bytes belonging to internal pages in the cache',
    'cache: tracked bytes belonging to leaf pages in the cache',
    'cache: tracked bytes belonging to overflow pages in the cache',
    'cache: tracked dirty bytes in the cache',
    'cache: tracked dirty pages in the cache',
    'connection: files currently open',
    'data-handle: connection data handles currently active',
    'log: maximum log file size',
    'log: number of pre-allocated log files to create',
    'log: total log buffer size',
    'LSM: application work units currently queued',
    'LSM: merge work units currently queued',
    'LSM: switch work units currently queued',
    'reconciliation: split bytes currently awaiting free',
    'reconciliation: split objects currently awaiting free',
    'session: open cursor count',
    'session: open session count',
    'thread-state: active filesystem fsync calls',
    'thread-state: active filesystem read calls',
    'thread-state: active filesystem write calls',
    'transaction: transaction checkpoint currently running',
    'transaction: transaction checkpoint generation',
    'transaction: transaction checkpoint max time (msecs)',
    'transaction: transaction checkpoint min time (msecs)',
    'transaction: transaction checkpoint most recent time (msecs)',
    'transaction: transaction checkpoint total time (msecs)',
    'transaction: transaction range of IDs currently pinned',
    'transaction: transaction range of IDs currently pinned by a checkpoint',
    'transaction: transaction range of IDs currently pinned by named snapshots',
    'btree: btree checkpoint generation',
    'session: open cursor count',
]
prefix_list = [
    'data-handle',
    'reconciliation',
    'LSM',
    'log',
    'cache',
    'transaction',
    'cursor',
    'connection',
    'session',
    'block-manager',
    'thread-yield',
    'async',
    'btree',
    'thread-state',
    'compression',
]
groups = {'cursor': ['cursor', 'session'], 'lsm': ['LSM', 'transaction'], 'system': ['connection', 'data-handle', 'session', 'thread-state'], 'evict': ['block-manager', 'cache', 'connection', 'thread-state'], 'memory': ['cache', 'connection', 'reconciliation']}