# -*- mode: python -*-

Import("env")

env = env.Clone()

# This library contains the initializers to run option parsing.  This is separated into its own
# library because some code that is shared between many different binaries needs to link against the
# options_parser library, but not all these binaries need to actually run the option parsing.
# Linking against this library will cause the option parsing initializer to actually be run.
env.Library(
    "options_parser_init",
    ["options_parser_init.cpp"],
    LIBDEPS=["options_parser"],
)

env.CppUnitTest(
    target="options_parser_test",
    source=[
        "environment_test.cpp",
        "options_parser_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/unittest/unittest",
        "options_parser",
    ],
)
