# -*- mode: python -*-

Import("env")

env = env.Clone()

env.AppendUnique(
    FORCEINCLUDES=[
        "mongo/platform/basic.h",
    ],
)

mongoTest = env.BazelProgram(
    target="mongotest",
    source=[],
    AIB_COMPONENT="mongotest",
    AIB_COMPONENTS_EXTRA=[
        "devcore",
        "dist-test",
    ],
)
