# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    mod_visibility: private
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/topology/remove_shard.idl"

commands:
    transitionToDedicatedConfigServer:
        command_name: transitionToDedicatedConfigServer
        cpp_name: TransitionToDedicatedConfigServer
        strict: true
        description: "The public transitionToDedicatedConfigServer command on mongos for transitioning a config shard to a dedicated config server."
        namespace: ignored
        api_version: ""
        reply_type: RemoveShardResponse

    _configsvrTransitionToDedicatedConfigServer:
        command_name: _configsvrTransitionToDedicatedConfigServer
        cpp_name: ConfigsvrTransitionToDedicatedConfig
        strict: false
        description: "The internal _configsvrTransitionToDedicatedConfigServer command for transitioning a config shard to a dedicated config server."
        namespace: ignored
        api_version: ""
        reply_type: RemoveShardResponse

    startTransitionToDedicatedConfigServer:
        command_name: startTransitionToDedicatedConfigServer
        description: "The public startTransitionToDedicatedConfigServer command on mongos"
        cpp_name: StartTransitionToDedicatedConfigServer
        strict: false
        namespace: ignored
        api_version: ""

    getTransitionToDedicatedConfigServerStatus:
        command_name: getTransitionToDedicatedConfigServerStatus
        description: "The public getTransitionToDedicatedConfigServerStatus command on mongos"
        cpp_name: GetTransitionToDedicatedConfigServerStatus
        strict: false
        namespace: ignored
        api_version: ""

    commitTransitionToDedicatedConfigServer:
        command_name: commitTransitionToDedicatedConfigServer
        description: "The public commitTransitionToDedicatedConfigServer command on mongos"
        cpp_name: CommitTransitionToDedicatedConfigServer
        strict: false
        namespace: ignored
        api_version: ""

    stopTransitionToDedicatedConfigServer:
        command_name: stopTransitionToDedicatedConfigServer
        description: "The public stopTransitionToDedicatedConfigServer command on mongos"
        cpp_name: StopTransitionToDedicatedConfigServer
        strict: false
        namespace: ignored
        api_version: ""
