# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="db_bucket_catalog_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="timeseries_sizing_test",
    source=[],
    LIBDEPS=[],
)
