.TH MONGORESTORE "1" "June 2009" "10gen" "Mongo Database"
.SH "NAME"
mongorestore \- the Mongo restoration tool
.SH "SYNOPSIS"
\fBmongorestore [\fIOPTIONS\fR]\fR
.SH "DESCRIPTION"
.PP
\fBmongorestore\fR
is a tool to use the output from mongodump to restore a database.
.SH "OPTIONS"
.TP
.B \-\-help
show usage information
.TP
.B \-\-version
show version information
.TP
.B \-h, \-\-host HOST
server to connect to (default HOST=localhost)
.TP
.B\-\-port arg
server port. Can also use \-\-host hostname:port
.TP
.B \-\-ipv6
enable IPv6 support (disabled by default)
.TP
.B \-u|\-\-username USERNAME
specify user to log in as
.TP
.B \-p|\-\-password PASSWORD
specify password of user (notice there is no space)
.TP
.B \-d, \-\-db DATABASE
database to use
.TP
.B \-c, \-\-c COLLECTION
collection to use
.TP
.B \-\-dbpath PATH
directly access mongod data files in this path, instead of connecting to a mongod instance
.TP
.B \-\-directoryperdb
if dbpath specified, each db is in a separate directory
.TP
.B \-\-objcheck
validate object before inserting
.TP
.B \-\-filter arg
filter to apply before inserting
.TP
.B \-\-drop
drop each collection before import
.TP
.B \-\-oplogReplay
replay oplog for point-in-time restore
.SH "COPYRIGHT"
.PP
Copyright 2007\-2011 10gen
.SH "SEE ALSO"
For more information, please refer to the MongoDB wiki, available at http://www.mongodb.org.
.SH "AUTHOR"
Kristina Chodorow
