.TH MONGOIMPORT "1" "January 2010" "10gen" "Mongo Database"
.SH "NAME"
mongoimport \- the Mongo import tool
.SH "SYNOPSIS"
\fBmongoimport [\fIOPTIONS\fR]\fR
.SH "DESCRIPTION"
.PP
\fBmongoimport\fR
is a tool to import a MongoDB collection from JSON, CSV, or TSV. The query can be filtered or a list of fields to input can be given.
.\".SH "EXAMPLES"
.\".TP
.\".B mongoimport -d test -c test1 --csv -f "name,num"
.\"import documents from test.test1 in CSV format
.SH "OPTIONS"
.TP
.B \-\-help
show usage information
.TP
.B \-\-version
show version information
.TP
.B \-v, \-\-verbose
be more verbose (include multiple times for more verbosity
e.g. \-vvvvv)
.TP
.B \-h, \-\-host HOST
server to connect to (default HOST=localhost)
.TP
.B\-\-port arg
server port. Can also use \-\-host hostname:port
.TP
.B \-\-ipv6
enable IPv6 support (disabled by default)
.TP
.B \-u|\-\-username USERNAME
specify user to log in as
.TP
.B \-p|\-\-password PASSWORD
specify password of user
.TP
.B \-\-dbpath PATH
directly access mongod data files in this path, instead of connecting to a mongod instance
.TP
.B \-\-directoryperdb
if dbpath specified, each db is in a separate directory
.TP
.B \-d, \-\-db DATABASE
database to use
.TP
.B \-c, \-\-c COLLECTION
collection to use
.TP
.B \-f, \-\-fields FIELDS
comma\-separated list of field names
.TP
.B \-\-fieldFile FILE
file with fields names \- 1 per line
.TP
.B \-\-ignoreBlanks
if given, empty fields in csv and tsv will be ignored
.TP
.B \-\-type TYPE
type of file to import.  default: json (json,csv,tsv)
.TP
.B \-\-file FILE
file to import from; if not specified stdin is used
.TP
.B \-\-drop
drop collection first
.TP
.B \-\-headerline
CSV,TSV only \- use first line as headers
.TP
.B \-\-upsert
insert or update objects that already exist
.TP
.B \-\-upsertFields ARG
comma-separated fields for the query part of the upsert. You should
make sure this is indexed
.TP
.B \-\-stopOnError
stop importing at first error rather than continuing
.TP
.B \-\-jsonArray
load a json array, not one item per line. Currently limited to 16MB.
.SH "COPYRIGHT"
.PP
Copyright 2007\-2011 10gen
.SH "SEE ALSO"
For more information, please refer to the MongoDB wiki, available at http://www.mongodb.org.
.SH "AUTHOR"
Kristina Chodorow
