.\" Documentation for the MongoDB shell
.TH MONGOD "1" "June 2009" "10gen" "Mongo Database"
.SH "NAME"
mongod \- the Mongo Daemon
.SH "SYNOPSIS"
.SH "DESCRIPTION"
.PP
\fBmongod\fR
is a core MongoDB daemon. You are not supposed to call it directly, please refer to the wiki if necessary.
.SH "COPYRIGHT"
.PP
Copyright 2007\-2009 10gen
.SH "SEE ALSO"
For more information, please refer to the MongoDB wiki, available at http://www.mongodb.org.
.SH "AUTHOR"
Antonin Kral
