.TH mongoreplay 1
.SH MONGOREPLAY
\fBmongoreplay\f1 is a traffic capture and replay tool for MongoDB
that you can use to inspect and record commands sent to a MongoDB
instance, and then replay those commands back onto another host at a
later time.
.PP
Starting in MongoDB 4.4, \fBmongoreplay\f1 is removed from MongoDB
packaging. \fBmongoreplay\f1 and its related documentation are migrated
to the mongodb\-labs (https://github.com/mongodb\-labs/mongoreplay)
github project. Projects in \fBmongodb\-labs\f1 are experimental and not
officially supported by MongoDB.
.PP
For documentation on \fBmongoreplay\f1, please refer to the
mongodb\-labs (https://github.com/mongodb\-labs/mongoreplay)
github project.