# -*- mode: python -*-

Import("env")

env = env.Clone()

env.SConscript(
    must_exist=1,
    dirs=[
        "algebra",
    ],
    exports=[
        "env",
    ],
)

# Lightweight test utils.
env.Library(
    target="unit_test_utils",
    source=[
        "utils/unit_test_utils.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/bson/dotted_path_support",
        "$BUILD_DIR/mongo/db/query/optimizer/optimizer_rewrites",
        "$BUILD_DIR/mongo/unittest/unittest",
    ],
)

env.CppUnitTest(
    target="optimizer_test",
    source=[
        "explain_paths_exprs_test.cpp",
        "optimizer_test.cpp",
        "reference_tracker_test.cpp",
        "rewrites/const_eval_test.cpp",
        "rewrites/path_optimizer_test.cpp",
        "unit_test_infra_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/exec/sbe/query_sbe",  # needed to register extended type destruction for MakeObjSpec :(
        "unit_test_utils",
    ],
)

optimizer_gdb_test_program = env.Program(
    target="optimizer_gdb_test_program",
    source=[
        "optimizer_gdb_test_program.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "$BUILD_DIR/mongo/db/service_context_test_fixture",
        "optimizer_rewrites",
        "unit_test_utils",
    ],
    AIB_COMPONENT="pretty-printer-tests",
    AIB_COMPONENTS_EXTRA=["dist-test"],
)
optimizer_gdb_test_program_installed = env.GetAutoInstalledFiles(optimizer_gdb_test_program[0])

env.PrettyPrinterTest("optimizer_gdb_test.py", TEST_PROGRAM=optimizer_gdb_test_program_installed)
