# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="stats_cache_loader_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="stats_cache_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="stats_path_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="type_collision_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="type_count_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="ce_histogram_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="value_utils_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(target="value_utils_bm", source=[])
