# -*- mode: python -*-

Import("env")

env.Library(
    target= 'btree',
    source= [
        'btree_logic.cpp',
        'btree_interface.cpp',
        'key.cpp'
        ],
    LIBDEPS= [
        '$BUILD_DIR/mongo/bson'
        ]
    )

env.Library(
    target= 'btree_test_help',
    source= [
        'btree_test_help.cpp'
        ],
    LIBDEPS= [
        'btree',
        '$BUILD_DIR/mongo/db/structure/record_store_v1_test_help'
        ]
    )

env.CppUnitTest(
    target='btree_logic_test',
    source=['btree_logic_test.cpp'
            ],
    LIBDEPS=[
        'btree_test_help'
        ]
    )

env.CppUnitTest(
    target='btree_builder_test',
    source=['btree_builder_test.cpp'
            ],
    LIBDEPS=[
        'btree_test_help'        
        ]
    )
