# -*- mode: python; -*-

Import("env")

env.Library(target="unittest",
            source=[
                'death_test.cpp',
                'temp_dir.cpp',
                'unittest.cpp',
                'unittest_helpers.cpp',
            ],
            LIBDEPS=['$BUILD_DIR/mongo/util/foundation',
                     '$BUILD_DIR/mongo/util/options_parser/options_parser',
            ])

env.Library("unittest_main", ['unittest_main.cpp'],
            LIBDEPS=[
                'unittest',
                '$BUILD_DIR/mongo/base',
                 ])

env.Library("unittest_crutch", ['crutch.cpp'], LIBDEPS=['$BUILD_DIR/mongo/base'])


env.CppUnitTest('unittest_test', 'unittest_test.cpp')
env.CppUnitTest('fixture_test', 'fixture_test.cpp')
env.CppUnitTest('temp_dir_test', 'temp_dir_test.cpp')

env.Library(
    target='concurrency',
    source=[
        'barrier.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ],
)
