# -*- mode: python; -*-

Import("env")

env.Library("unittest", ['unittest.cpp', 'temp_dir.cpp'],
            LIBDEPS=['$BUILD_DIR/mongo/foundation',
                     '$BUILD_DIR/mongo/util/options_parser/options_parser',
            ])

env.Library("unittest_main", ['unittest_main.cpp'],
            LIBDEPS=[
                'unittest',
                '$BUILD_DIR/mongo/base/base',
                '$BUILD_DIR/mongo/signal_handlers_synchronous',
                 ])

env.Library("unittest_crutch", ['crutch.cpp'])


env.CppUnitTest('unittest_test', 'unittest_test.cpp')
env.CppUnitTest('fixture_test', 'fixture_test.cpp')
env.CppUnitTest('temp_dir_test', 'temp_dir_test.cpp')
