# Copyright (C) 2019-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo::unittest"
    configs:
        source: cli
        initializer:
            register: addUnitTestOptions

configs:
    list:
        description: 'List all test suites in this unit test.'
        arg_vartype: Switch
        default: false
    suite:
        description: 'Test suite name. Specify --suite more than once to run multiple suites.'
        arg_vartype: StringVector
    filter:
        description: 'Test case name filter. Specify the substring of the test names.'
        arg_vartype: String
    repeat:
        description: 'Specifies the number of runs for each test.'
        arg_vartype: Int
        default: 1
    verbose:
        description: "Log more verbose output.  Specify one or more 'v's to increase verbosity."
        arg_vartype: String
        implicit: v

