Import("env")

env = env.Clone()

env.Benchmark(
    target="storage_key_string_bm",
    source=[
        "key_string_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "key_string",
    ],
)

ksdecode = env.BazelProgram(
    target="ksdecode",
    source=[],
    AIB_COMPONENT="ksdecode",
    AIB_COMPONENTS_EXTRA=[
        "dist-test",
    ],
)

env.CppUnitTest(
    target="key_string_test",
    source=[],
    LIBDEPS=[],
)

env.CppLibfuzzerTest(
    target="key_string_to_bson_fuzzer",
    source=[],
)
