# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="db_transaction_test",
    source=[
        "integer_interval_set_test.cpp",
        "transaction_api_test.cpp",
        "transaction_history_iterator_test.cpp",
        "transaction_operations_test.cpp",
        "transaction_participant_retryable_writes_test.cpp",
        "transaction_participant_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/db/dbhelpers",
        "$BUILD_DIR/mongo/db/op_observer/op_observer",
        "$BUILD_DIR/mongo/db/op_observer/op_observer_impl",
        "$BUILD_DIR/mongo/db/op_observer/operation_logger_impl",
        "$BUILD_DIR/mongo/db/repl/image_collection_entry",
        "$BUILD_DIR/mongo/db/repl/mock_repl_coord_server_fixture",
        "$BUILD_DIR/mongo/db/repl/replica_set_aware_service",
        "$BUILD_DIR/mongo/db/repl/storage_interface_impl",
        "$BUILD_DIR/mongo/db/service_context_d_test_fixture",
        "$BUILD_DIR/mongo/db/session/session_catalog_mongod",
        "$BUILD_DIR/mongo/db/stats/transaction_stats",
        "$BUILD_DIR/mongo/db/storage/storage_control",
        "$BUILD_DIR/mongo/executor/inline_executor",
        "$BUILD_DIR/mongo/s/sharding_router_api",
        "transaction",
        "transaction_api",
        "transaction_operations",
    ],
)

env.Benchmark(
    target="transaction_operations_bm",
    source=[
        "transaction_operations_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/concurrency/lock_manager",
        "$BUILD_DIR/mongo/db/repl/oplog_entry",
        "$BUILD_DIR/mongo/db/server_base",
        "transaction_operations",
    ],
)
