# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='cmdline_utils',
    source=[
        'censor_cmdline.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/util/options_parser/options_parser',
    ])

env.CppUnitTest('censor_cmdline_test',
                'censor_cmdline_test.cpp',
                LIBDEPS=['cmdline_utils', '$BUILD_DIR/mongo/unittest/unittest'])
