// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#include "mongo/db/exec/agg/change_stream_check_topology_change_stage.h"

#include "mongo/db/exec/agg/document_source_to_stage_registry.h"
#include "mongo/db/pipeline/document_source_change_stream_check_topology_change.h"

#include <string_view>

namespace mongo {

boost::intrusive_ptr<exec::agg::Stage> documentSourceChangeStreamCheckTopologyChangeToStageFn(
    const boost::intrusive_ptr<DocumentSource>& documentSource) {
    auto* changeStreamCheckTopologyChangeDS =
        dynamic_cast<DocumentSourceChangeStreamCheckTopologyChange*>(documentSource.get());

    tassert(10561310,
            "expected 'DocumentSourceChangeStreamCheckTopologyChange' type",
            changeStreamCheckTopologyChangeDS);

    return make_intrusive<exec::agg::ChangeStreamCheckTopologyChangeStage>(
        changeStreamCheckTopologyChangeDS->kStageName,
        changeStreamCheckTopologyChangeDS->getExpCtx());
}

namespace exec::agg {

REGISTER_AGG_STAGE_MAPPING(_internalChangeStreamCheckTopologyChange,
                           DocumentSourceChangeStreamCheckTopologyChange::id,
                           documentSourceChangeStreamCheckTopologyChangeToStageFn)

ChangeStreamCheckTopologyChangeStage::ChangeStreamCheckTopologyChangeStage(
    std::string_view stageName, const boost::intrusive_ptr<ExpressionContext>& pExpCtx)
    : Stage(stageName, pExpCtx) {}

GetNextResult ChangeStreamCheckTopologyChangeStage::doGetNext() {
    // This stage is mostly a no-op since MongoDB v8.3. It is only present in pipelines that are
    // generated by older versions of mongos. The stage will pass through all events except any
    // 'migrateChunkToNewShard' events. Change stream pipelines generated by new versions of mongos
    // will not include this stage at all.
    while (true) {
        auto input = pSource->getNext();
        if (!input.isAdvanced()) {
            return input;
        }

        auto opTypeField = input.getDocument()[DocumentSourceChangeStream::kOperationTypeField];
        if (opTypeField.getType() != BSONType::string ||
            opTypeField.getStringData() != DocumentSourceChangeStream::kNewShardDetectedOpType) {
            return input;
        }

        // Getting here means that a 'migrateChunkToNewShard' event was received. This should be a
        // very rare exception.
        input.releaseDocument();
    }
}

}  // namespace exec::agg
}  // namespace mongo
