# exit immediately if virtualenv is not found
set -o errexit

evergreen_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)/.."
. "$evergreen_dir/prelude_workdir.sh"
. "$evergreen_dir/prelude_python.sh"

python_loc=$(which ${python})
echo "python_loc set to $python_loc"

venv_dir="${workdir}/venv"
if [ -d "$venv_dir" ] && [ -z "${FORCE_CREATE:-}" ]; then
    exit 0
fi

# uv version pin — canonical source is buildscripts/uv_version.txt. Kept in
# lockstep across every uv installer in the repo (uv_sync.sh, set_up_workstation.sh,
# Dockerfiles, powercycle bootstrap, pyproject.toml `export` group).
UV_VERSION="$(cat "$evergreen_dir/../buildscripts/uv_version.txt")"

# Standalone venv that holds the `uv` binary. We keep it separate from the
# main venv so that the dependency installer is not itself a managed dep —
# this mirrors the prior split between `$POETRY_VENV` and `$venv_dir`.
UV_VENV="${workdir}/uv_venv"
if [ "Windows_NT" = "$OS" ]; then
    UV_VENV_PYTHON="$UV_VENV/Scripts/python.exe"
else
    UV_VENV_PYTHON="$UV_VENV/bin/python3"
fi
"$python_loc" -m venv "$UV_VENV"

# Loop 5 times to retry the uv install — we have seen weird network errors
# that can sometimes mess up the pip install. By retrying we would like to
# only see errors that happen consistently.
for i in {1..5}; do
    "$UV_VENV_PYTHON" -m pip install --disable-pip-version-check "uv==${UV_VERSION}" && RET=0 && break || RET=$? && sleep 1
    echo "Python failed to install uv, retrying..."
done

if [ $RET -ne 0 ]; then
    echo "Pip install error for uv"
    exit $RET
fi

"$python_loc" -m venv "$venv_dir"

# Adding README file for using this venv locally
cat <<EOF >>venv_readme.txt
This is an archive of the Python venv generated by this Evergreen build.
You can use it locally to avoid needing to manually set up the Python environment.

Before activating it you should adjust it for your local environment.
Run the following commands to do that:

echo "Updating virtual env directory in activate script"
pushd venv; venv_dir=\$(pwd); popd
EOF
if [ "Windows_NT" = "$OS" ]; then
    cat <<EOF >>venv_readme.txt
sed -i -e "s:VIRTUAL_ENV=\".*\":VIRTUAL_ENV=\"\$venv_dir\":" "\$venv_dir/Scripts/activate"
EOF
else
    cat <<EOF >>venv_readme.txt
sed -i -e "s:VIRTUAL_ENV=\".*\":VIRTUAL_ENV=\"\$venv_dir\":" "\$venv_dir/bin/activate"

echo "Adding back python symlinks"
pushd venv/bin
rm python python3
ln -s "$python_loc" python3
ln -s python3 python
python3_dot_locs=\$(ls python3.*)
for p in \$python3_dot_locs; do
  rm "\$p"
  ln -s python3 "\$p"
done
popd
EOF
fi # End of README file

# venv creates its Scripts/activate file with CLRF endings, which
# cygwin bash does not like. dos2unix it
# (See https://bugs.python.org/issue32451)
if [ "Windows_NT" = "$OS" ]; then
    dos2unix "${workdir}/venv/Scripts/activate"
fi

export VIRTUAL_ENV_DISABLE_PROMPT=yes

# the whole prelude cannot be imported because it requires pyyaml to be
# installed, which happens just below.
. "$evergreen_dir/prelude_venv.sh"

activate_venv
echo "Upgrading pip to 25.3 and wheel to 0.45.1"

# Loop 5 times to retry the pip install
# We have seen weird network errors that can sometimes mess up the pip install
# By retrying we would like to only see errors that happen consistently
for i in {1..5}; do
    python -m pip --disable-pip-version-check install "pip==25.3" "wheel==0.45.1" && RET=0 && break || RET=$? && sleep 1
    echo "Python failed to install pip and wheel, retrying..."
done

if [ $RET -ne 0 ]; then
    echo "Pip install error for wheel and pip version"
    exit $RET
fi

cd src

# Fix for Python 3.13+ on Windows: Python 3.11.4+ converts VIRTUAL_ENV to Cygwin path format
# (e.g., /cygdrive/c/path) when running under Cygwin/MSYS bash, but sys.prefix remains a
# Windows path (e.g., C:\path). This breaks venv detection in tools that compare these
# paths. Normalize VIRTUAL_ENV back to Windows format so uv can detect the venv correctly.
# See: https://github.com/python/cpython/issues/103088
if [ "Windows_NT" = "$OS" ] && [ -n "$VIRTUAL_ENV" ]; then
    if [[ "$VIRTUAL_ENV" == /cygdrive/* ]] || [[ "$VIRTUAL_ENV" == /[a-z]/* ]]; then
        VIRTUAL_ENV=$(cygpath -w "$VIRTUAL_ENV")
        export VIRTUAL_ENV
    fi
fi

# SERVER-XXXX: cryptography 41+ ships a Rust extension and PyPI carries
# no s390x / ppc64le wheels for it, so on those archs uv has to build
# from sdist. The sdist build uses maturin which needs a matching rust
# toolchain (`stable-<arch>-unknown-linux-gnu`) installed via rustup;
# the rhel83-zseries-small and rhel81-power8-small distros ship rustup
# but not the host-arch toolchain. Install it on demand. On x86_64 /
# aarch64 the precompiled wheel is used so this step is unnecessary.
case "$(uname -m 2>/dev/null)" in
s390x | ppc64le)
    if command -v rustup >/dev/null 2>&1; then
        rust_target="stable-$(uname -m)-unknown-linux-gnu"
        if ! rustup toolchain list 2>/dev/null | grep -q "${rust_target}"; then
            echo "Installing rust toolchain ${rust_target} for cryptography sdist build..."
            rustup toolchain install "${rust_target}" --profile minimal --no-self-update || true
        fi
    fi
    ;;
esac

# Loop 5 times to retry full venv install
# We have seen weird network errors that can sometimes mess up the pip install
# By retrying we would like to only see errors that happen consistently
# Point uv at the activated venv ($venv_dir) explicitly via UV_PROJECT_ENVIRONMENT.
count=0
for i in {1..5}; do
    UV_PROJECT_ENVIRONMENT="$VIRTUAL_ENV" "$UV_VENV_PYTHON" -m uv sync --locked --all-groups --no-install-project && RET=0 && break || RET=$? && sleep 1

    echo "uv failed to install required deps, retrying..."
    sleep $((count * count * 20))
    count=$((count + 1))
done

if [ $RET -ne 0 ]; then
    echo "uv install error for full venv"
    exit $RET
fi

cd ..

python -m pip freeze >pip-requirements.txt
