# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Benchmark(
    target="op_observer_bm",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="db_op_observer_test",
    source=[],
    LIBDEPS=[],
)
