# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo::query_settings"
    cpp_includes:
        - "mongo/db/query/query_feature_flags_gen.h"
    mod_visibility: private

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/query/query_feature_flags.idl"
    - "mongo/db/query/query_settings/query_settings.idl"
    - "mongo/db/topology/cluster_parameters/cluster_server_parameter.idl"

structs:
    QuerySettingsClusterParameterValue:
        description: "The underlying value of the query settings cluster parameter."
        inline_chained_structs: true
        chained_structs:
            ClusterServerParameter: clusterServerParameter
        fields:
            settingsArray:
                type: array<QueryShapeConfiguration>
                stability: stable

server_parameters:
    querySettings:
        description: >-
            Query settings for all query shapes will be stored within this cluster
            server parameter.
        set_at: cluster
        cpp_class:
            name: QuerySettingsClusterParameter
            override_set: true
        redact: false
        omit_in_ftdc: true
