# Copyright (C) 2023-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
  cpp_namespace: "mongo::query_settings"
  cpp_includes:
    - "mongo/db/query/query_settings/query_framework_serialization.h"


imports:
  - "mongo/db/basic_types.idl"
  - "mongo/db/query/index_hint.idl"
  - "mongo/db/query/query_knobs.idl"
  - "mongo/db/query/query_shape/query_shape_hash.idl"

types:
  QueryFramework:
    description: >-
      Enum representing the query engine version as a combination of execution
      engine and optimizer being used when executing the query.
    bson_serialization_type : string
    cpp_type: "mongo::QueryFrameworkControlEnum"
    deserializer: "::mongo::query_settings::query_framework::parse"
    serializer: "::mongo::query_settings::query_framework::serialize"
    is_view: false

structs:
  Namespace:
    description: >-
      Struct representing a namespace. An alternative definition of the
      NamespaceString.
    fields:
      db:
        type: string
        stability: unstable
      coll:
        type: string
        stability: unstable

  IndexHintSpec:
    description: "Struct representing the index hint spec."
    fields:
      ns:
        type: Namespace
        optional: true
        stability: unstable
      allowedIndexes:
        type: array<IndexHint>
        stability: unstable

  QuerySettings:
    description: >-
      Struct representing possible settings that may be applied to a given query.
    fields:
      indexHints:
        type:
          variant: [IndexHintSpec, array<IndexHintSpec>]
        optional: true
        stability: unstable
      queryFramework:
        type: QueryFramework
        optional: true
        stability: unstable
      reject:
        type: optionalBool
        stability: unstable

  QueryShapeConfiguration:
    description: >-
      Struct representing configuration for a particular query shape of the
      'representativeQuery'. Configuration consists of query settings that will
      be applied to all query instances of the query shape.
    fields:
      queryShapeHash: QueryShapeHash
      settings: QuerySettings
      representativeQuery:
        type: object_owned
        optional: true
