# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target="utils",
    source=[
        "query_settings_hash.cpp",
        "query_settings_utils.cpp",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/db/query/canonical_query",
        "$BUILD_DIR/mongo/db/query/query_shape/query_shape",
        "manager",
    ],
)

env.CppUnitTest(
    target="query_settings_serialization_test",
    source=[
        "index_hints_serialization_test.cpp",
        "query_framework_serialization_test.cpp",
    ],
    LIBDEPS=[
        "query_settings",
    ],
)

env.Benchmark(
    target="query_settings_lookup_bm",
    source=[
        "query_settings_lookup_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/canonical_query",
        "$BUILD_DIR/mongo/db/query/query_test_service_context",
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "$BUILD_DIR/mongo/db/service_context_test_fixture",
        "$BUILD_DIR/mongo/util/processinfo",
        "manager",
        "utils",
    ],
)
