# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="query_settings_serialization_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="query_settings_lookup_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="query_bm",
)
