# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/server_options.h"
    configs:
        section: GRPC Options
        source: [cli, ini, yaml]

configs:
    "net.grpc.port":
        description: gRPC listener port
        short_name: grpcPort
        arg_vartype: Int
        cpp_varname: serverGlobalParams.grpcPort
        validator: {gte: 1, lte: 65535}
        # Default is defined in mongo/db/server_options.h
        # default: 27021
    "net.grpc.serverMaxThreads":
        description: Limit of maximum number of gRPC session threads
        short_name: grpcServerMaxThreads
        arg_vartype: Int
        cpp_varname: serverGlobalParams.grpcServerMaxThreads
        validator: {gte: 1}
        # Default is defined in mongo/db/server_options.h
        # default: 1000

server_parameters:
    grpcKeepAliveTimeMs:
        description:
            "The interval in milliseconds between PING frames to check the liveness of
            established gRPC channels. Runtime updates will only apply to newly created
            channels."
        set_at: [startup, runtime]
        default: 2147483647 # INT_MAX
        cpp_varname: "serverGlobalParams.grpcKeepAliveTimeMs"
        redact: false

    grpcKeepAliveTimeoutMs:
        description:
            "The timeout in milliseconds for a PING frame to be acknowledged. If the client
            does not receive an acknowledgment within this time, it will close the
            connection. Runtime updates will only apply to newly created channels."
        set_at: [startup, runtime]
        default: 20000
        cpp_varname: "serverGlobalParams.grpcKeepAliveTimeoutMs"
        redact: false
