# -*- mode: python -*-

Import("env")

env = env.Clone()
env.InjectThirdParty(libraries=["grpc"])

env.CppUnitTest(
    target="grpc_transport_layer_test",
    source=[],
    LIBDEPS=[],
)

protoEnv = env.Clone()
protoEnv.InjectThirdParty(libraries=["proto"])
protoEnv.AppendUnique(
    PROTOC_GEN_TYPES=[["cpp", protoEnv.Dir(".")]],
    PROTOC_PLUGINS={
        "grpc": {
            "plugin": "$PROTOC_GRPC_PLUGIN",
            "options": ["generate_mock_code=true"],
            "gen_out": protoEnv.Dir("."),
            "exts": [".grpc.pb.cc", ".grpc.pb.h"],
        },
    },
    CPPPATH=[protoEnv.Dir(".")],
)
protoEnv.Append(
    CPPPATH=[
        "$BUILD_DIR/third_party/protobuf/dist/src",
        "#/bazel-bin",
    ]
)

protoEnv.CppUnitTest(target="grpc_core_test", source=[])
