# -*- mode: python -*-

Import('env')

env = env.Clone()

env.Library(
    target='grpc_transport_layer',
    source=[
        'wire_version_provider.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/wire_version',
    ],
)
