# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="db_bson_test",
    source=[
        "dotted_path_support_test.cpp",
    ],
    LIBDEPS=[
        "dotted_path_support",
    ],
)
