# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Benchmark(
    target="tracking_allocator_bm",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="tracking_allocator_test",
    source=[],
    LIBDEPS=[],
)
