#! /bin/sh

rm -f vgout.*

# Add
#	--db-attach=yes
# to wait on a debugger attach.
valgrind \
    --leak-check=yes \
    --log-file=vgout.%p \
    --read-var-info=yes \
    --suppressions=../format/vt.suppress \
    --track-fds=yes \
    ./t
