# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target='logv2_test',
    source=[
        'logv2_component_test.cpp',
        'logv2_test.cpp',
        'redaction_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/auth/security_token',
        '$BUILD_DIR/mongo/db/server_base',
    ],
)

env.Benchmark(
    target='logv2_bm',
    source=[
        'logv2_bm.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ],
)

env.Library(
    target='logv2_options',
    source=[
        'logv2_options.cpp',
        'logv2_options.idl',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/server_base',
    ],
)
