/**
 *    Copyright (C) 2025-present MongoDB, Inc.
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the Server Side Public License, version 1,
 *    as published by MongoDB, Inc.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    Server Side Public License for more details.
 *
 *    You should have received a copy of the Server Side Public License
 *    along with this program. If not, see
 *    <http://www.mongodb.com/licensing/server-side-public-license>.
 *
 *    As a special exception, the copyright holders give permission to link the
 *    code of portions of this program with the OpenSSL library under certain
 *    conditions as described in each individual source file and distribute
 *    linked combinations including the program with the OpenSSL library. You
 *    must comply with the Server Side Public License in all respects for
 *    all of the code used other than as permitted herein. If you modify file(s)
 *    with this exception, you may extend this exception to your version of the
 *    file(s), but you are not obligated to do so. If you do not wish to do so,
 *    delete this exception statement from your version. If you delete this
 *    exception statement from all source files in the program, then also delete
 *    it in the license file.
 */
#pragma once

#include "mongo/db/query/compiler/optimizer/join/cardinality_estimator.h"
#include "mongo/db/query/compiler/optimizer/join/join_reordering_context.h"
#include "mongo/db/query/compiler/optimizer/join/plan_enumerator.h"
#include "mongo/util/modules.h"

namespace mongo::join_ordering {

struct ReorderedJoinSolution {
    // Winning plan lowered to SBE for use by the executor.
    std::unique_ptr<QuerySolution> soln;

    // Base node of new join order.
    NodeId baseNode;

    // Only populated for explain. Pairs rejected QuerySolutions with their base nodes.
    std::vector<std::pair<std::unique_ptr<QuerySolution>, NodeId>> rejectedSolns;

    // Only populated for explain. Estimate information for QuerySolutionNodes in 'soln'.
    cost_based_ranker::EstimateMap estimates;
};

/**
 * Construct a 'QuerySolution' with a pseudo-random join ordering based on the given seed. Performs
 * a random walk of the join graph in 'ctx' to determine the join order, the provided parameters to
 * specify the shape of tree and the method to use, and invokes the bottom up enumerator while
 * hinting all this information to get a join order. If the enumerator fails, will retry generating
 * a randomized hint up to 'maxRandomHintTries' times (this excludes the first attempt).
 *
 * The cost & cardinality estimators may be null, since they're not used for choosing a plan-
 * however, if they're not null, costs and cardinalities of all join plan nodes will be generated.
 *
 * When 'method' is set to boost::none, a random method will be picked for each subset according to
 * the provided seed.
 *
 * Note: The defaults below are set to maximize the space of plans this function can generate (i.e.
 * ZIG_ZAG means any plan shape we can generated, and we disable HJ pruning/ don't specify a single
 * JoinMethod), but can be overriden to produce only a narrower subset of plans.
 */
StatusWith<ReorderedJoinSolution> constructSolutionWithRandomOrder(
    const JoinReorderingContext& ctx,
    JoinCardinalityEstimator* estimator,
    JoinCostEstimator* coster,
    int seed,
    PlanTreeShape planShape = PlanTreeShape::ZIG_ZAG,
    boost::optional<JoinMethod> method = boost::none,
    bool enableHJOrderPruning = false,
    size_t maxRandomHintRetries = 3);

/**
 * Construct a 'QuerySolution' with a join ordering based on the result generated by bottom-up
 * Sellinger-style join optimization.
 */
StatusWith<ReorderedJoinSolution> constructSolutionBottomUp(const JoinReorderingContext& ctx,
                                                            JoinCardinalityEstimator& estimator,
                                                            JoinCostEstimator& coster,
                                                            EnumerationStrategy strategy);

}  // namespace mongo::join_ordering
