// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0
#pragma once

#include "mongo/db/query/compiler/optimizer/join/cardinality_estimator.h"
#include "mongo/db/query/compiler/optimizer/join/join_reordering_context.h"
#include "mongo/db/query/compiler/optimizer/join/plan_enumerator.h"
#include "mongo/db/query/multiple_collection_accessor.h"
#include "mongo/db/query/plan_cache/join_plan_cache.h"
#include "mongo/util/modules.h"

namespace mongo::join_ordering {

struct ReorderedJoinSolution {
    // Winning plan lowered to SBE for use by the executor.
    std::unique_ptr<QuerySolution> soln;

    // Base node of new join order.
    NodeId baseNode;

    // Only populated for explain. Pairs rejected QuerySolutions with their base nodes.
    std::vector<std::pair<std::unique_ptr<QuerySolution>, NodeId>> rejectedSolns;

    // Only populated for explain. Estimate information for QuerySolutionNodes in 'soln'.
    cost_based_ranker::EstimateMap estimates;

    // Populated by constructSolutionBottomUp only; nullptr signals "do not cache".
    std::unique_ptr<CachedJoinPlan> cachedJoinPlan;
};

/**
 * Construct a 'QuerySolution' with a pseudo-random join ordering based on the given seed. Performs
 * a random walk of the join graph in 'ctx' to determine the join order, the provided parameters to
 * specify the shape of tree and the method to use, and invokes the bottom up enumerator while
 * hinting all this information to get a join order. If the enumerator fails, will retry generating
 * a randomized hint up to 'maxRandomHintRetries' times (this excludes the first attempt).
 *
 * The cost & cardinality estimators may be null, since they're not used for choosing a plan-
 * however, if they're not null, costs and cardinalities of all join plan nodes will be generated.
 *
 * When 'method' is set to boost::none, a random method will be picked for each subset according to
 * the provided seed.
 *
 * Note: The defaults below are set to maximize the space of plans this function can generate (i.e.
 * ZIG_ZAG means any plan shape we can generated, and we disable HJ pruning/ don't specify a single
 * JoinMethod), but can be overriden to produce only a narrower subset of plans.
 */
StatusWith<ReorderedJoinSolution> constructSolutionWithRandomOrder(
    const JoinReorderingContext& ctx,
    JoinCardinalityEstimator* estimator,
    JoinCostEstimator* coster,
    int seed,
    PlanTreeShape planShape = PlanTreeShape::ZIG_ZAG,
    boost::optional<JoinMethod> method = boost::none,
    bool enableHJOrderPruning = false,
    size_t maxRandomHintRetries = 3);

/**
 * Construct a 'QuerySolution' with a join ordering based on the result generated by bottom-up
 * Sellinger-style join optimization.
 */
StatusWith<ReorderedJoinSolution> constructSolutionBottomUp(const JoinReorderingContext& ctx,
                                                            JoinCardinalityEstimator& estimator,
                                                            JoinCostEstimator& coster,
                                                            EnumerationStrategy strategy,
                                                            bool populateCachedPlan);

/**
 * Converts the join plan rooted at 'nodeId' in 'registry' into an owning 'CachedJoinPlan' tree
 * suitable for storage in the 'JoinPlanCache'. 'ctx' is required to resolve join predicates and
 * embedding fields via the join graph.
 */
std::unique_ptr<CachedJoinPlan> toCachedJoinPlan(const JoinReorderingContext& ctx,
                                                 const JoinPlanNodeRegistry& registry,
                                                 JoinPlanNodeId nodeId);

/**
 * Reconstructs a 'QuerySolutionNode' tree from 'plan'. Uses 'joinGraph' to get each
 * 'CanonicalQuery' associated with each node (via stored NodeIds, which correctly handles
 * self-joins), and 'collections' + 'opCtx' to build IndexEntry objects with correct multikey
 * information via 'indexEntryFromIndexCatalogEntry'.
 */
std::unique_ptr<QuerySolutionNode> fromCachedJoinPlan(OperationContext* opCtx,
                                                      const JoinGraph& joinGraph,
                                                      const MultipleCollectionAccessor& collections,
                                                      const AvailableIndexes& perCollIdxs,
                                                      const CachedJoinPlan& plan);

}  // namespace mongo::join_ordering
