// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#pragma once

#include "mongo/db/shard_role/shard_role.h"
#include "mongo/util/modules.h"
#include "mongo/util/uuid.h"

#include <boost/optional/optional.hpp>

[[MONGO_MOD_PUBLIC]];

namespace mongo {

/**
 * Clones the collection "shortFrom" to the capped collection "shortTo" with a size of "size".
 * If targetUUID is provided, then the newly capped collection will get that UUID. Otherwise, the
 * UUID for the newly capped collection will be randomly generated.
 */
void cloneCollectionAsCapped(OperationContext* opCtx,
                             Database* db,
                             const CollectionAcquisition& fromColl,
                             CollectionAcquisition& toColl,
                             long long size,
                             bool temp,
                             const boost::optional<UUID>& targetUUID = boost::none);

/**
 * Converts the collection "collectionName" to a capped collection with a size of "size".
 * If targetUUID is provided, then the newly capped collection will get that UUID. Otherwise, the
 * UUID for the newly capped collection will be randomly generated.
 * The 'fromMigrate' parameter will be used to mark each oplog entry generated by this method
 * through the homonymous field.
 */
void convertToCapped(OperationContext* opCtx,
                     const NamespaceString& collectionName,
                     long long size,
                     bool fromMigrate,
                     const boost::optional<UUID>& targetUUID = boost::none);
}  // namespace mongo
