# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo::analyze_shard_key"
    # TODO SERVER-118592: Determine the visibility of this idl once we move it out of the query module.
    mod_visibility: needs_replacement

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/pipeline/legacy_runtime_constants.idl"
    - "mongo/s/analyze_shard_key_common.idl"

structs:
    QueryAnalyzerDocument:
        description:
            "Represents a document storing the query analyzer configuration for a collection
            as configured via the configureQueryAnalyzer command."
        strict: false
        fields:
            _id:
                type: namespacestring
                description: "The namespace of the collection."
                cpp_name: ns
            collUuid:
                type: uuid
                description: "The UUID of the collection."
                cpp_name: collectionUuid
            startTime:
                type: date
                description: "The time at which query sampling began."
            stopTime:
                type: date
                description: "The time at which query sampling ended."
                optional: true
        inline_chained_structs: true
        chained_structs:
            QueryAnalyzerConfiguration: configuration

    SampledReadCommand:
        description: "The command object for a sampled read query."
        strict: false
        fields:
            filter:
                type: object
                description: "The filter for the read."
            collation:
                type: object
                description: "The collation for the read."
            let:
                type: object
                description: "The user-specified constants for the read."
                optional: true

    SampledQueryDocument:
        description: "Represents a document storing a sampled read or write query."
        strict: false
        fields:
            _id:
                type: uuid
                description: "The unique sample id for the read or write."
                cpp_name: sampleId
            ns:
                type: namespacestring
                description: "The namespace of the collection for the read or write."
            collectionUuid:
                type: uuid
                description: "The UUID of the collection for the read or write."
            cmdName:
                type: SampledCommandName
                description: "The command name for the read or write."
            cmd:
                type: object
                description: "The command object for the read or write."
            expireAt:
                type: date
                description: "The time at which the document should be deleted by the TTL monitor."

    SampledQueryDiffDocument:
        description: "Represents a document storing the diff for a sampled write query."
        strict: false
        fields:
            _id:
                type: uuid
                description: "The unique sample id for the write."
                cpp_name: sampleId
            ns:
                type: namespacestring
                description: "The namespace of the collection for the write."
            collectionUuid:
                type: uuid
                description: "The UUID of the collection for the write."
            diff:
                type: object
                description: "The diff for the write."
            expireAt:
                type: date
                description: "The time at which the document should be deleted by the TTL monitor."

    AnalyzeShardKeySplitPointId:
        description:
            "Represents the unique id for a document storing one of the split points created
            by an analyzeShardKey command."
        strict: false
        fields:
            analyzeShardKeyId:
                type: uuid
                description: "The unique id for the command that generated this split point."
            splitPointId:
                type: uuid
                description: "The unique id for this split point."

    AnalyzeShardKeySplitPointDocument:
        description:
            "Represents a document storing one of the split points created by an
            analyzeShardKey command."
        strict: false
        fields:
            _id:
                type: AnalyzeShardKeySplitPointId
                cpp_name: id
            ns:
                type: namespacestring
            splitPoint:
                type: object
            expireAt:
                type: date
                description: "The time at which the document should be deleted by the TTL monitor."
