# Copyright (C) 2019-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

# ChunkVersion IDL type definition

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/s/chunk_version.h"

imports:
    - "mongo/db/basic_types.idl"

structs:
    CollectionGenerationBase:
        description: Represents the generation part of a collection version which changes every time
                     the collection undergoes some major transformation. This is the most
                     significant part of the version of a collection.
        strict: false
        fields:
            e:
                type: objectid
                description: "Collection epoch"
                cpp_name: Epoch
            t:
                type: timestamp
                description: "Collection timestamp"
                cpp_name: Timestamp

    CollectionPlacementBase:
        description: Represents the chunk-placement part of a collection version, which is
                     subordinate to the collection generation.
        strict: false
        fields:
            v:
                type: timestamp
                description: "Bitwise concatenation of the 32-bit major/minor versions"
                cpp_name: Version

    ChunkVersion60Format:
        description: New chunk version format with is parsed by 6.0 binaries but only generated
                     starting with the 6.0 binaries when the FCV is 6.0.
        strict: false
        chained_structs:
            CollectionGenerationBase: Generation
            CollectionPlacementBase: Placement

types:
    # The canonical serialisation format for ChunkVersions
    ChunkVersion:
        bson_serialization_type: any
        description: An object representing a chunk version for a collection.
        cpp_type: ChunkVersion
        serializer: ChunkVersion::serialize
        deserializer: ChunkVersion::parse
