
# Copyright (C) 2020-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
  cpp_namespace: "mongo"
  cpp_includes:
    - "mongo/s/mongos_server_parameters.h"

imports:
    - "mongo/db/basic_types.idl"

server_parameters:
  readHedgingMode:
    description: >-
        Enables hedged reads.
    set_at: [ startup, runtime ]
    cpp_class:
      name: HedgingModeServerParameter

  maxTimeMSForHedgedReads:
    description: >-
        The maxTimeMS to set on hedged reads.
    set_at: [ startup, runtime ]
    cpp_vartype: AtomicWord<int>
    cpp_varname: "gMaxTimeMSForHedgedReads"
    validator:
        gte: 0
    default: 150

  mongosShutdownTimeoutMillisForSignaledShutdown:
    description: >-
        The time taken for quiesce mode at shutdown in response to SIGTERM.
    set_at: [ startup, runtime ]
    cpp_vartype: AtomicWord<int>
    cpp_varname: "mongosShutdownTimeoutMillisForSignaledShutdown"
    default: 15000
    validator:
        gte: 0

  loadBalancerPort:
    description: >-
        The port over which proxied connections using the Proxy Protocol may be made.
        A value of 0 disables the port entirely.
    set_at: [ startup ]
    cpp_vartype: AtomicWord<int>
    cpp_varname: "loadBalancerPort"
    default: 0
    validator: { gte: 0, lte: 65535 }
