// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#pragma once

#include "mongo/base/error_codes.h"
#include "mongo/bson/bsonobj.h"
#include "mongo/bson/bsonobjbuilder.h"
#include "mongo/db/client.h"
#include "mongo/db/global_catalog/chunk_manager.h"
#include "mongo/db/namespace_string.h"
#include "mongo/db/operation_context.h"
#include "mongo/db/server_options.h"
#include "mongo/db/sharding_environment/shard_id.h"
#include "mongo/db/topology/cluster_role.h"
#include "mongo/s/analyze_shard_key_common_gen.h"
#include "mongo/s/analyze_shard_key_role.h"
#include "mongo/s/query_analysis_sampler.h"
#include "mongo/s/write_ops/batched_command_request.h"
#include "mongo/transport/session.h"
#include "mongo/util/assert_util.h"
#include "mongo/util/modules.h"
#include "mongo/util/testing_proctor.h"
#include "mongo/util/uuid.h"

#include <memory>
#include <set>
#include <string_view>
#include <vector>

#include <boost/move/utility_core.hpp>
#include <boost/none.hpp>
#include <boost/optional/optional.hpp>

[[MONGO_MOD_PUBLIC]];

namespace mongo {
namespace analyze_shard_key {

struct TargetedSampleId {
public:
    TargetedSampleId(UUID sampleId, ShardId shardId) : _sampleId(sampleId), _shardId(shardId) {};

    bool isFor(ShardEndpoint endpoint) const {
        return _shardId == endpoint.shardName;
    }

    bool isFor(ShardId shardId) const {
        return _shardId == shardId;
    }

    UUID getId() const {
        return _sampleId;
    }

private:
    UUID _sampleId;
    ShardId _shardId;
};

/**
 * Returns a unique sample id for a query if it should be sampled, and none otherwise. Can only be
 * invoked once for each query since generating a sample id causes the number of remaining queries
 * to sample to get decremented.
 */
boost::optional<UUID> tryGenerateSampleId(OperationContext* opCtx,
                                          const NamespaceString& nss,
                                          SampledCommandNameEnum cmdName);
boost::optional<UUID> tryGenerateSampleId(OperationContext* opCtx,
                                          const NamespaceString& nss,
                                          std::string_view cmdName);

/**
 * Similar to 'tryGenerateSampleId()' but assigns the sample id to a random shard out of the given
 * ones.
 */
boost::optional<TargetedSampleId> tryGenerateTargetedSampleId(OperationContext* opCtx,
                                                              const NamespaceString& nss,
                                                              SampledCommandNameEnum cmdName,
                                                              const std::set<ShardId>& shardIds);

boost::optional<TargetedSampleId> tryGenerateTargetedSampleId(OperationContext* opCtx,
                                                              const NamespaceString& nss,
                                                              std::string_view cmdName,
                                                              const std::set<ShardId>& shardIds);

boost::optional<TargetedSampleId> tryGenerateTargetedSampleId(
    OperationContext* opCtx,
    const NamespaceString& nss,
    SampledCommandNameEnum cmdName,
    const std::vector<ShardEndpoint>& endpoints);

boost::optional<TargetedSampleId> tryGenerateTargetedSampleId(
    OperationContext* opCtx,
    const NamespaceString& nss,
    BatchedCommandRequest::BatchType cmdName,
    const std::vector<ShardEndpoint>& endpoints);

ShardId getRandomShardId(const std::set<ShardId>& shardIds);
ShardId getRandomShardId(const std::vector<ShardEndpoint>& endpoints);

BSONObj appendSampleId(const BSONObj& cmdObj, const UUID& sampleId);
void appendSampleId(BSONObjBuilder* bob, const UUID& sampleId);

/**
 * To be invoked by commands on mongod. On a mongod that does not support persisting sampled
 * queries, returns none. On a mongod in a shardsvr replica set, returns the sample id attached in
 * the request. On a mongod in a standalone replica set, returns the sample id as generated by
 * 'tryGenerateSampleId'.
 */
template <typename RequestType>
boost::optional<UUID> getOrGenerateSampleId(OperationContext* opCtx,
                                            const NamespaceString& nss,
                                            const SampledCommandNameEnum cmdName,
                                            const RequestType& request) {
    if (!supportsPersistingSampledQueries(opCtx)) {
        return boost::none;
    }
    if (serverGlobalParams.clusterRole.has(ClusterRole::ShardServer)) {
        const auto isInternalThreadOrClient =
            !opCtx->getClient()->session() || opCtx->getClient()->isInternalClient();
        uassert(ErrorCodes::InvalidOptions,
                "Cannot specify 'sampleId' since it is an internal field",
                !request.getSampleId() || isInternalThreadOrClient ||
                    TestingProctor::instance().isEnabled());
        return request.getSampleId();
    }
    if (serverGlobalParams.clusterRole.has(ClusterRole::None)) {
        uassert(ErrorCodes::InvalidOptions,
                "Cannot specify 'sampleId' since it is an internal field",
                !request.getSampleId());
        return QueryAnalysisSampler::get(opCtx).tryGenerateSampleId(opCtx, nss, cmdName);
    }
    MONGO_UNREACHABLE;
}

}  // namespace analyze_shard_key
}  // namespace mongo
