Import("env")

env.Library(
    target= 'storage_heap1',
    source= [
        'heap1_database_catalog_entry.cpp',
        'heap1_engine.cpp'
        ],
    LIBDEPS= [
        '$BUILD_DIR/mongo/bson',
        '$BUILD_DIR/mongo/db/catalog/collection_options',
        '$BUILD_DIR/mongo/db/structure/record_store',
        '$BUILD_DIR/mongo/foundation',
        ]
    )

env.CppUnitTest(
    target='storage_heap1_test',
    source=['heap1_test.cpp',
            ],
    LIBDEPS=[
        'storage_heap1'
        ]
    )

