Import("env")

env.Library(
    target= 'heap_record_store',
    source= [
        'record_store_heap.cpp'
        ],
    LIBDEPS= [
        '$BUILD_DIR/mongo/bson',
        '$BUILD_DIR/mongo/foundation',
        ]
    )

env.Library(
    target= 'storage_heap1_core',
    source= [
        'heap1_btree_impl.cpp',
        'heap1_database_catalog_entry.cpp',
        'heap1_engine.cpp',
        'heap1_recovery_unit.cpp',
        ],
    LIBDEPS= [
        'heap_record_store',
        '$BUILD_DIR/mongo/bson',
        '$BUILD_DIR/mongo/db/catalog/collection_options',
        '$BUILD_DIR/mongo/db/storage/index_entry_comparison',
        '$BUILD_DIR/mongo/db/index/index_descriptor',
        '$BUILD_DIR/mongo/foundation',
        ]
    )

env.Library(
    target= 'storage_heap1',
    source= [
        'heap1_database_catalog_entry_index_real.cpp',
        'heap1_init.cpp',
        ],
    LIBDEPS= [
        'storage_heap1_core',
        ]
    )

env.Library(
    target= 'storage_heap1_fake',
    source= [
        'heap1_database_catalog_entry_index_test.cpp'
        ],
    LIBDEPS= [
        'storage_heap1_core',
        ]
    )



env.CppUnitTest(
   target='storage_heap1_test',
   source=['heap1_test.cpp'
           ],
   LIBDEPS=[
       'storage_heap1_fake'
       ]
   )

env.CppUnitTest(
   target='storage_heap1_btree_test',
   source=['heap1_btree_impl_test.cpp'
           ],
   LIBDEPS=[
        'storage_heap1_fake',
        '$BUILD_DIR/mongo/db/storage/sorted_data_interface_test_harness'
        ]
   )

env.CppUnitTest(
   target='storage_heap1_record_storetest',
   source=['heap1_record_store_test.cpp'
           ],
   LIBDEPS=[
        'storage_heap1_fake',
        '$BUILD_DIR/mongo/db/storage/record_store_test_harness'
        ]
   )

