# Image used by bazel remote execution hosts.

# Use Amazon Linux 2 as a base image to get a glibc that's old enough to be compatible with all
# supported distros (glibc v2.26)
FROM amazonlinux:2

# glibc-devel is required for headers, libzstd is required by gcc.
RUN yum -y install glibc-devel libzstd

CMD ["/bin/bash"]
