# -*- mode: python -*-

Import("env")

env = env.Clone()
env.CppUnitTest(
    target="tracing_profiler_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="tracing_profiler_bm",
    source=[],
    LIBDEPS=[],
)
