# -*- mode: python -*-

Import("env")

# TODO: config upgrade tests are currently in dbtests
env.Library(
    target='catalog_manager_legacy',
    source=[
        'catalog_manager_legacy.cpp',
        'cluster_client_internal.cpp',
        'config_coordinator.cpp',
        'config_upgrade.cpp',
        'config_upgrade_helpers.cpp',
        'config_upgrade_v0_to_v7.cpp',
        'config_upgrade_v6_to_v7.cpp',
        'distlock.cpp',
        'legacy_dist_lock_manager.cpp',
        'legacy_dist_lock_pinger.cpp',
    ],
    LIBDEPS=[
        'mongo_version_range',
        '$BUILD_DIR/mongo/s/catalog/catalog_manager',
        '$BUILD_DIR/mongo/s/catalog/dist_lock_manager',
    ]
)

env.Library(
    target='mongo_version_range',
    source=[
        'mongo_version_range.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/s/catalog/catalog_types',
    ]
)

env.CppUnitTest(
    target='mongo_version_range_test',
    source=[
        'mongo_version_range_test.cpp',
    ],
    LIBDEPS=[
        'mongo_version_range',
    ]
)
