# -*- mode: python -*-

Import("env")

# TODO: config upgrade tests are currently in dbtests
env.Library(
    target='catalog_manager_legacy',
    source=[
        'catalog_manager_legacy.cpp',
        'cluster_client_internal.cpp',
        'config_coordinator.cpp',
        'config_upgrade.cpp',
        'config_upgrade_helpers.cpp',
        'config_upgrade_v0_to_v7.cpp',
        'config_upgrade_v6_to_v7.cpp',
        'distlock.cpp',
        'legacy_dist_lock_manager.cpp',
        'legacy_dist_lock_pinger.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/s/catalog/catalog_manager',
        '$BUILD_DIR/mongo/s/catalog/dist_lock_manager',
        '$BUILD_DIR/mongo/s/client/sharding_client',
    ]
)


env.CppUnitTest(
    target='catalog_manager_legacy_test',
    source=[
        'config_coordinator_test.cpp',
    ],
    LIBDEPS=[
        'catalog_manager_legacy',
        '$BUILD_DIR/mongo/coredb',
        '$BUILD_DIR/mongo/coreserver',
        '$BUILD_DIR/mongo/db/auth/authorization_manager_mock_init',
        '$BUILD_DIR/mongo/s/coreshard',
        '$BUILD_DIR/mongo/s/mongoscore',
        '$BUILD_DIR/mongo/mongocommon',
    ]
)

