# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='timeseries_idl',
    source=[
        'timeseries.idl',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/idl/idl_parser',
        '$BUILD_DIR/mongo/idl/server_parameter',
    ],
)

env.Library(
    target='bucket_catalog',
    source=[
        'bucket_catalog.cpp',
        'minmax.cpp',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/catalog/database_holder',
        '$BUILD_DIR/mongo/db/commands/server_status',
        '$BUILD_DIR/mongo/db/concurrency/write_conflict_exception',
        '$BUILD_DIR/mongo/db/views/views',
        '$BUILD_DIR/mongo/util/fail_point',
        'timeseries_idl',
    ],
)

env.Library(
    target='timeseries_index_schema_conversion_functions',
    source=[
        'timeseries_index_schema_conversion_functions.cpp',
    ],
    LIBDEPS_PRIVATE=[
        'timeseries_idl',
    ],
)

env.Library(
    target='timeseries_lookup',
    source=[
        'timeseries_lookup.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        'timeseries_idl',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/catalog/collection_catalog',
    ],
)

env.CppUnitTest(
    target='db_timeseries_test',
    source=[
        'bucket_catalog_test.cpp',
        'minmax_test.cpp',
        'timeseries_index_schema_conversion_functions_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/catalog/catalog_test_fixture',
        'bucket_catalog',
        'timeseries_index_schema_conversion_functions',
    ],
)
