# -*- mode: python -*-

Import("env")

env = env.Clone()

env.SConscript(
    must_exist=1,
    dirs=[
        "bucket_catalog",
    ],
    exports=[
        "env",
    ],
)

env.Library(
    target="timeseries_collmod",
    source=[
        "timeseries_collmod.cpp",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/db/catalog/catalog_helpers",
        "$BUILD_DIR/mongo/db/coll_mod_command_idl",
        "$BUILD_DIR/mongo/db/exec/bucket_unpacker",
        "$BUILD_DIR/mongo/db/index_commands_idl",
        "$BUILD_DIR/mongo/db/server_base",
        "$BUILD_DIR/mongo/db/shard_role",
        "catalog_helper",
        "timeseries_conversion_util",
        "timeseries_options",
    ],
)

env.CppUnitTest(
    target="db_timeseries_test",
    source=[
        "bucket_compression_test.cpp",
        "timeseries_dotted_path_support_test.cpp",
        "timeseries_extended_range_test.cpp",
        "timeseries_index_schema_conversion_functions_test.cpp",
        "timeseries_options_test.cpp",
        "timeseries_update_delete_util_test.cpp",
        "timeseries_write_util_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/catalog/catalog_test_fixture",
        "$BUILD_DIR/mongo/db/catalog/collection_crud",
        "$BUILD_DIR/mongo/db/record_id_helpers",
        "$BUILD_DIR/mongo/db/shard_role",
        "$BUILD_DIR/mongo/db/timeseries/bucket_catalog/bucket_catalog",
        "bucket_compression",
        "timeseries_conversion_util",
        "timeseries_extended_range",
        "timeseries_options",
        "timeseries_write_util",
    ],
)

env.Library(
    target="timeseries_op_observer",
    source=[
        "timeseries_op_observer.cpp",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/db/catalog/collection_catalog",
        "$BUILD_DIR/mongo/db/concurrency/lock_manager",
        "$BUILD_DIR/mongo/db/op_observer/op_observer",
        "$BUILD_DIR/mongo/db/timeseries/bucket_catalog/bucket_catalog",
        "timeseries_extended_range",
    ],
)
