# Image used by bazel remote execution hosts.

FROM ubuntu:18.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    libxml2-dev \
    libssl-dev \
    systemtap-sdt-dev

CMD ["/bin/bash"]
