# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    mod_visibility: public

server_parameters:
    internalQueryAlwaysMergeOnPrimaryShard:
        description: >-
            Formerly, if this was set to true on mongos, all aggregations delivered to the mongos
            which require a merging shard would select the primary shard as the merger. However,
            because shard targeting no longer relies on the notion of a primary shard, this knob
            is a no-op and is maintained to avoid breaking any configurations that depend on this
            knob.
        cpp_vartype: Atomic<bool>
        cpp_varname: internalQueryAlwaysMergeOnPrimaryShard
        set_at: [startup, runtime]
        default: false
        redact: false

    internalQueryProhibitMergingOnMongoS:
        description: >-
            If set to true on mongos, all aggregations which could otherwise merge on the mongos will be
            obliged to merge on a shard instead. Pipelines which are redirected to the shards will obey the
            value of internalQueryAlwaysMergeOnPrimaryShard. False by default, meaning that pipelines capable
            of merging on mongoS will always do so.
        cpp_vartype: Atomic<bool>
        cpp_varname: internalQueryProhibitMergingOnMongoS
        set_at: [startup, runtime]
        default: false
        redact: false

    internalQueryDisableExchange:
        description: >-
            If set to true on mongos then the cluster query planner will not produce plans with the exchange.
            False by default, so the queries run with exchanges.
        cpp_vartype: Atomic<bool>
        cpp_varname: internalQueryDisableExchange
        set_at: [startup, runtime]
        default: false
        redact: false
