# -*- mode: python -*-

Import("env")

env = env.Clone()

env.SConscript(
    must_exist=1,
    dirs=[
        "exec",
        "planner",
    ],
    exports=[
        "env",
    ],
)

env.Library(
    target="mongos_docs_needed_bounds",
    source=[
        "document_source_visitor_docs_needed_bounds.cpp",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/db/pipeline/docs_needed_bounds_visitor",
        "exec/router_exec_stage",
    ],
)
