# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="network_executor_test",
    source=[],
)

env.CppUnitTest(
    target="task_executor_test",
    source=[],
    PROVE_ALIASES=["server-programmability"],
)

env.CppIntegrationTest(
    target="executor_integration_test",
    source=[],
)
