# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="histogram_estimation_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="maxdiff_histogram_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="generated_histograms_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="sampling_estimator_test",
    source=[
        "sampling_estimator_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/catalog/catalog_test_fixture",
        "$BUILD_DIR/mongo/db/query_exec",
    ],
)

env.Benchmark(
    target="histogram_bm",
    source=["ce_histogram_bm.cpp"],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/query_test_service_context",
        "ce_test_utils",
    ],
    CONSOLIDATED_TARGET="second_half_bm",
)

env.BazelProgram(
    target="histogram_estimation_accuracy_analysis_program",
    source=[],
    LIBDEPS=[],
)
