# Copyright (C) 2022-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#
global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

structs:
    StatsBucket:
        description: "Histogram bucket"
        fields:
            upperBoundary:
                type: IDLAnyType
            boundaryCount:
                type: long
            rangeCount:
                type: long
            rangeDistincts:
                type: long
            cumulativeCount:
                type: long
            cumulativeDistincts:
                type: long

    BoolCount:
        description: "Tracks count of booleans separately from histogram buckets and other type
counts"
        fields:
            trueCount:
                type: long
            falseCount:
                type: long

    TypeTag:
        description: "SBE types and their corresponding frequencies in the histogram"
        fields:
            typeName:
                type: string
            count:
                type: long

    StatsArrayHistogram:
        description: "Array Histogram"
        fields:
            minHistogram:
                type: array<StatsBucket>
            maxHistogram:
                type: array<StatsBucket>
            uniqueHistogram:
                type: array<StatsBucket>
            boolCount:
                type: BoolCount
            typeCount:
                type: array<TypeTag>

    StatsPath:
        description: "Serialized representation of data statistics for a key path"
        fields:
            _id:
                type: string
            documents:
                type: long
            documentsSampled:
                type: long
                optional: true
            samplingRate:
                type: double
                optional: true
            samplesRequested:
                type: long
                optional: true
            boolCount:
                type: BoolCount
                optional: true
            typeCount:
                type: array<TypeTag>
                optional: true
            scalarHistogram:
                type: array<StatsBucket>
                optional: true
            arrayStatistics:
                type: StatsArrayHistogram
                optional: true
