# -*- mode: python -*-

import platform

Import(
    [
        "env",
        "get_option",
    ]
)

env = env.Clone()
env.CppUnitTest(
    target="platform_test",
    source=[],
    PROVE_ALIASES=["server-programmability"],
)

env.Benchmark(
    target="endian_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="first_half_bm",
)

if get_option("link-model") == "dynamic":
    env.CppUnitTest(
        target="visibility1_test",
        source=[],
        LIBDEPS=[],
        PROVE_ALIASES=["server-programmability"],
    )

    env.CppUnitTest(
        target="visibility2_test",
        source=[],
        LIBDEPS=[],
        PROVE_ALIASES=["server-programmability"],
    )

env.CppUnitTest(
    target="rwmutex_test",
    source=[],
    LIBDEPS=[],
    PROVE_ALIASES=["server-programmability"],
)

env.Benchmark(
    target="rwmutex_bm",
    source=[],
    LIBDEPS=[],
)

if platform.system() == "Linux":
    env.CppUnitTest(
        target="throw_hook_test",
        source=[],
        LIBDEPS=[],
        PROVE_ALIASES=["server-programmability"],
    )
