# -*- mode: python -*-

Import(
    [
        "env",
        "http_client",
        "ssl_provider",
    ]
)

env = env.Clone()
env.CppUnitTest(
    target="crypto_test",
    source=[],
    LIBDEPS=[],
)

if ssl_provider == "openssl":
    env.CppUnitTest(
        target="jws_validator_test",
        source=[],
        LIBDEPS=[],
    )

env.Benchmark(
    target="crypto_bm",
    source=[],
    LIBDEPS=[],
)
