# Copyright (C) 2017 MongoDB Inc.
#
# This program is free software: you can redistribute it and/or  modify
# it under the terms of the GNU Affero General Public License, version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# SHA256Block type

global:
  cpp_namespace: "mongo"
  cpp_includes:
    - "mongo/crypto/sha256_block.h"

imports:
  - "mongo/idl/basic_types.idl"

types:
  sha256Block:
    bson_serialization_type: bindata
    bindata_subtype: generic
    description: "A fixed-size byte array that holds the result of a SHA256 computation"
    cpp_type: mongo::SHA256Block
    serializer: "mongo::SHA256Block::toCDR"
    deserializer: "mongo::SHA256Block::fromBinData"
