#! /bin/sh

trap 'rm -f __*; exit 1' 1 2

wt=../../build_posix
bdb=db/build_unix

colflag=0
dump_bdb=0
while :
	do case "$1" in
	# -b means we need to dump the BDB database
	-b)
		dump_bdb=1;
		shift ;;
	# -c means it was a column-store.
	-c)
		colflag=1
		shift ;;
	*)
		break ;;
	esac
done

if test $# -ne 0; then
	echo 'usage: s_dumpcmp [-c]' >&2
	exit 1
fi

# Strip trailing zeros from a dump to deal with differences in fixed-length
# column store behavior between WT and BDB.
strip_zeros() {
	cat > __t

	lines=`wc -l __t | sed 's/[^0-9]//g'`
	while test "`sed -n -e ${lines}p < __t`" = '\00' ; do
		lines=`expr $lines - 1`
	done
	sed -e `expr $lines + 1`,'$d' < __t
}

if test $dump_bdb -eq 1; then
	if test $colflag -eq 0; then
		$bdb/db_dump -p __bdb |
		    sed -e '1,/HEADER=END/d' \
			-e '/DATA=END/d' \
			-e 's/^ //' > __bdb_dump
	else
		$bdb/db_dump -p __bdb |
		    sed -e '1,/HEADER=END/d' \
			-e '/DATA=END/d' \
			-e 's/^ //' |
		    sed -n \
			-e '$p' \
			-e n \
			-e p |
		    strip_zeros > __bdb_dump
	fi
fi

bzext="../../ext/compressors/bzip2_compress/bzip2_compress.so"
if test -e $bzext ; then
	config='extensions=["'$bzext'"]'
else
	config=
fi

if test $colflag -eq 0; then
	$wt/wt -C "$config" dump -p file:__wt > __wt_dump
else
	$wt/wt -C "$config" dump -p file:__wt | strip_zeros > __wt_dump
fi
cmp __wt_dump __bdb_dump > /dev/null || exit 1

exit 0
