#! /bin/sh

wt=../../build_posix
bdb=db/build_unix

colflag=0
dump_bdb=0
while :
	do case "$1" in
	# -b means we need to dump the BDB database
	-b)
		dump_bdb=1;
		shift ;;
	# -c means it was a column-store.
	-c)
		colflag=1
		shift ;;
	*)
		break ;;
	esac
done

if test $# -ne 0; then
	echo 'usage: s_dumpcmp [-c]' >&2
	exit 1
fi

if test $dump_bdb -eq 1; then
	if test $colflag -eq 0; then
		$bdb/db_dump -p __bdb |
		    sed -e '1,/HEADER=END/d' \
			-e '/DATA=END/d' \
			-e 's/^ //' > __bdb_dump
	else
		$bdb/db_dump -p __bdb |
		    sed -e '1,/HEADER=END/d' \
			-e '/DATA=END/d' \
			-e 's/^ //' |
		    sed -n \
			-e '$p' \
			-e n \
			-e p > __bdb_dump
	fi
fi

$wt/wt dump -p file:__wt > __wt_dump
cmp __wt_dump __bdb_dump > /dev/null

exit $?
