# -*- mode: python -*-

Import("env")
env = env.Clone()

env.Library(
    target='tenant_split_state_machine',
    source=[
        'tenant_split_state_machine.idl',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/client/connection_string',
        '$BUILD_DIR/mongo/db/repl/tenant_migration_utils',
        '$BUILD_DIR/mongo/idl/idl_parser'
    ],
)

env.Library(
    target='tenant_split_commands',
    source=[
        'tenant_split_commands.idl',
        'tenant_split_commands.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/client/connection_string',
        '$BUILD_DIR/mongo/db/auth/auth',
        '$BUILD_DIR/mongo/db/repl/tenant_migration_utils',
        '$BUILD_DIR/mongo/idl/idl_parser',
        'tenant_split_state_machine',
    ]
)

env.Library(
    target='tenant_split_donor_service',
    source=[
        'tenant_split_donor_service.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/repl/primary_only_service',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/namespace_string',
    ]
)
