# -*- mode: python -*-

Import("env")
env = env.Clone()

env.CppUnitTest(
    target="db_serverless_test",
    source=[
        "serverless_operation_lock_registry_test.cpp",
        "shard_split_donor_op_observer_test.cpp",
        "shard_split_donor_service_test.cpp",
        "shard_split_utils_test.cpp",
        "shard_split_test_utils.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/db/catalog/catalog_helpers",
        "$BUILD_DIR/mongo/db/commands/create_command",
        "$BUILD_DIR/mongo/db/op_observer/op_observer_util",
        "$BUILD_DIR/mongo/db/repl/primary_only_service_test_fixture",
        "$BUILD_DIR/mongo/db/repl/replmocks",
        "$BUILD_DIR/mongo/db/repl/tenant_migration_access_blocker",
        "$BUILD_DIR/mongo/dbtests/mocklib",
        "serverless_lock",
        "shard_split_donor_service",
        "shard_split_utils",
    ],
)
