# Copyright (C) 2021-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#
global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/repl/tenant_migration_util.h"

imports:
    - "mongo/db/repl/replication_types.idl"
    - "mongo/db/basic_types.idl"

enums:
    ShardSplitDonorState:
        description: "The state of a shard split operation."
        type: string
        values:
            kUninitialized: "uninitialized"
            kAbortingIndexBuilds: "aborting index builds"
            kBlocking: "blocking"
            kCommitted: "committed"
            kAborted: "aborted"

structs:
    ShardSplitDonorDocument:
        description: "The state document for an in-progress shard split operation."
        strict: true
        fields:
            _id:
                type: uuid
                description: "Unique identifier for the shard split operation."
                cpp_name: id
            recipientSetName:
                type: string
                description: "The replica set name for the recipient."
                optional: true
            recipientTagName:
                type: string
                description: "The replica set tag that identifies recipient nodes."
                optional: true
            recipientConnectionString:
                type: connection_string
                description: >-
                    The connection string generated by the donor which it uses to
                    monitor the recipient for split acceptance.
                optional: true
            tenantIds:
                type: array<string>
                optional: true
                description: "The identifier for the list of tenants being migrated."
            state:
                type: ShardSplitDonorState
                description: "The current state of the shard split operation."
                default: kUninitialized
            blockOpTime:
                type: optime
                description: >-
                    The opTime at which writes and causal reads against the databases
                    being migrated should start blocking.
                optional: true
            commitOrAbortOpTime:
                type: optime
                description:
                    The opTime at which the donor's state document was set to 'committed'
                    or 'aborted'.
                optional: true
            abortReason:
                type: object_owned
                description: "The error that caused the split to abort."
                optional: true
            expireAt:
                type: date
                description: >-
                    The wall-clock time at which the state machine document should be
                    removed by the TTL monitor.
                optional: true
