# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target="mongocryptd_core",
    source=[
        "cryptd_main.cpp",
        "cryptd_options.cpp",
        "cryptd_options_init.cpp",
        "cryptd_service_entry_point.cpp",
        "cryptd_watchdog.cpp",
        "cryptd_options_gen.cpp",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/db/commands",
        "$BUILD_DIR/mongo/db/dbmessage",
        "$BUILD_DIR/mongo/db/query/query_stats/query_stats",
        "$BUILD_DIR/mongo/db/repl/repl_coordinator_interface",
        "$BUILD_DIR/mongo/db/server_options_servers",
        "$BUILD_DIR/mongo/db/serverinit",
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "$BUILD_DIR/mongo/db/storage/storage_engine_lock_file",
        "$BUILD_DIR/mongo/db/validate_api_parameters",
        "$BUILD_DIR/mongo/db/windows_options" if env.TargetOSIs("windows") else [],
        "$BUILD_DIR/mongo/executor/network_interface_factory",
        "$BUILD_DIR/mongo/rpc/rpc",
        "$BUILD_DIR/mongo/s/grid",
        "$BUILD_DIR/mongo/transport/message_compressor",
        "$BUILD_DIR/mongo/transport/service_executor",
        "$BUILD_DIR/mongo/transport/session_manager",
        "$BUILD_DIR/mongo/transport/transport_layer",
        "$BUILD_DIR/mongo/transport/transport_layer_manager",
        "$BUILD_DIR/mongo/util/concurrency/spin_lock",
        "$BUILD_DIR/mongo/util/fail_point",
        "$BUILD_DIR/mongo/util/net/network",
        "$BUILD_DIR/mongo/util/ntservice",
        "$BUILD_DIR/mongo/util/options_parser/options_parser_init",
        "$BUILD_DIR/mongo/util/signal_handlers",
        "$BUILD_DIR/mongo/util/testing_options",
        "$BUILD_DIR/mongo/util/version_impl",
        "$BUILD_DIR/mongo/watchdog/watchdog",
    ],
)
