# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target="change_collection_server_status",
    source=[
        "change_collection_server_status.cpp",
        "change_stream_preimages_server_status.cpp",
    ],
    LIBDEPS_PRIVATE=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/db/change_stream_change_collection_manager",
        "$BUILD_DIR/mongo/db/change_stream_pre_image_util",
        "$BUILD_DIR/mongo/db/change_stream_pre_images_collection_manager",
        "$BUILD_DIR/mongo/db/change_stream_serverless_helpers",
        "$BUILD_DIR/mongo/db/commands/server_status_core",
        "$BUILD_DIR/mongo/db/server_base",
        "$BUILD_DIR/mongo/db/shard_role",
    ],
)

env.CppUnitTest(
    target="db_stats_test",
    source=[
        "api_version_metrics_test.cpp",
        "operation_latency_histogram_test.cpp",
        "resource_consumption_metrics_test.cpp",
        "timer_stats_test.cpp",
        "top_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/db/repl/replmocks",
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "$BUILD_DIR/mongo/db/service_context_test_fixture",
        "$BUILD_DIR/mongo/db/shared_request_handling",
        "$BUILD_DIR/mongo/util/clock_source_mock",
        "api_version_metrics",
        "resource_consumption_metrics",
        "timer_stats",
        "top",
    ],
)
