# Copyright (C) 2026-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo::otel::traces"

imports:
    - "mongo/db/basic_types.idl"

structs:
    OpenTelemetryTracingTokenBucketRateLimit:
        description: "Parameters for a rate limit for OpenTelemetry tracing."
        strict: false
        fields:
            refillRate:
                description: "The number tokens to refill per second."
                type: double
                default: 1.0
                validator:
                    gt: 0.0
            maxTokens:
                description: "The maximum number of tokens that can be held in the bucket."
                type: int
                default: 10
                validator:
                    gt: 0

    OpenTelemetryTracingSamplingStrategy:
        description: "Describes how a set of spans should be sampled, e.g., the sampling rate."
        strict: false
        fields:
            samplingFactor:
                description: >-
                    Fraction of spans to sample, in [0.0, 1.0]. A value of 0.0 disables sampling;
                    1.0 samples all spans.
                type: double
                default: 0.000045
                validator:
                    gte: 0.0
                    lte: 1.0
            tokenBucketRateLimit:
                description: >-
                    The rate limit to apply to these samples.
                type: OpenTelemetryTracingTokenBucketRateLimit
                default: true

    OpenTelemetryTracingSpanSelection:
        description: "Identifies a span."
        strict: false
        fields:
            name:
                description: "The span name to match."
                type: string

    OpenTelemetryTracingSample:
        description: "Associates a span selection with a sampling strategy."
        strict: false
        fields:
            spanSelection:
                description: "Identifies which span this entry applies to."
                type: OpenTelemetryTracingSpanSelection
            samplingStrategy:
                description: >-
                    The sampling strategy to apply to the selected span. Uses the default if not
                    provided.
                type: OpenTelemetryTracingSamplingStrategy
                optional: true

    OpenTelemetryTracingSamplingConfig:
        description: "Configuration for head-based sampling of spans to initiate traces."
        strict: false
        fields:
            defaultSampling:
                description: >-
                    The sampling strategy applied to spans that are sampled by default and to
                    sampled spans that don't specify a samplingStrategy.
                    TODO(SERVER-127466): Add relevant span names.
                    TODO(SERVER-127467): Add relevant span names.
                    TODO(SERVER-127468): Add relevant span names.
                type: OpenTelemetryTracingSamplingStrategy
                default: true
            samples:
                description: >-
                    Overrides to sample specific spans, which override the default sampling in cases
                    where both would apply. If no samplingStrategy is provided for an entry, uses
                    defaultSampling.
                type: array<OpenTelemetryTracingSample>
                optional: true

server_parameters:
    openTelemetryTracingSampling:
        description: >-
            Configuration for head-based sampling of spans to initiate traces. This should be an
            OpenTelemetryTracingSamplingConfig BSON document.
        set_at: [startup, runtime]
        cpp_class:
            name: OpenTelemetryTracingSamplingServerParameter
            override_set: true
        redact: false
