# Copyright (C) 2026-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo::otel::traces"

imports:
    - "mongo/db/basic_types.idl"

structs:
    OpenTelemetryTracingSamplingStrategy:
        description: "Describes how a set of spans should be sampled, e.g., the sampling rate."
        strict: false
        fields:
            samplingFactor:
                description: >-
                    Fraction of spans to sample, in [0.0, 1.0]. A value of 0.0 disables sampling;
                    1.0 samples all spans.
                type: double
                default: 0.000045
                validator:
                    gte: 0.0
                    lte: 1.0

    OpenTelemetryTracingSamplingConfig:
        description: "Configuration for head-based sampling of spans to initiate traces."
        strict: false
        fields:
            defaultSampling:
                description: >-
                    The sampling strategy applied to spans that are sampled by default.
                    TODO(SERVER-127466): Add relevant span names.
                    TODO(SERVER-127467): Add relevant span names.
                    TODO(SERVER-127468): Add relevant span names.
                type: OpenTelemetryTracingSamplingStrategy
                default: true

server_parameters:
    openTelemetryTracingSampling:
        description: >-
            Configuration for head-based sampling of spans to initiate traces. This should be an
            OpenTelemetryTracingSamplingConfig BSON document.
        set_at: [startup, runtime]
        cpp_class:
            name: OpenTelemetryTracingSamplingServerParameter
            override_set: true
        redact: false
