# -*- mode: python -*-

Import("env")

env = env.Clone()
env.InjectThirdParty(libraries=[
    's2',
])

env.Library(
    target='vector_search',
    source=[
        'filter_validator.cpp',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/query_expressions',
    ],
)

env.CppUnitTest(
    target='db_query_vector_search_test',
    source=[
        'filter_validator_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/exec/document_value/document_value_test_util',
        '$BUILD_DIR/mongo/db/pipeline/document_source_mock',
        '$BUILD_DIR/mongo/db/query/query_planner',
        '$BUILD_DIR/mongo/db/service_context_non_d',
        '$BUILD_DIR/mongo/db/service_context_test_fixture',
        'vector_search',
    ],
)
