# -*- mode: python -*-

Import("env")

env = env.Clone()
env.InjectThirdParty(libraries=[
    's2',
])

env.Library(
    target='document_source_vector_search',
    source=[
        'document_source_vector_search.cpp',
        'document_source_vector_search.idl',
        'filter_validator.cpp',
        'mongot_cursor.cpp',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/query/plan_executor',
        '$BUILD_DIR/mongo/db/query/search/document_source_search',
        '$BUILD_DIR/mongo/db/query/search/search_task_executors',
        '$BUILD_DIR/mongo/db/shard_role_api',
        '$BUILD_DIR/mongo/executor/task_executor_cursor',
    ],
)

env.CppUnitTest(
    target='db_query_vector_search_test',
    source=[
        'document_source_vector_search_test.cpp',
        'filter_validator_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/auth/authmocks',
        '$BUILD_DIR/mongo/db/exec/document_value/document_value_test_util',
        '$BUILD_DIR/mongo/db/pipeline/document_source_mock',
        '$BUILD_DIR/mongo/db/query/search/document_source_search',
        '$BUILD_DIR/mongo/db/service_context_non_d',
        '$BUILD_DIR/mongo/db/service_context_test_fixture',
        'document_source_vector_search',
    ],
)
