# DO NOT EDIT: automatically built by dist/stat.py. */

no_scale_per_second_list = [
    'async: maximum work queue length',
    'cache: tracked dirty bytes in the cache',
    'cache: bytes currently in the cache',
    'cache: maximum bytes configured',
    'cache: tracked dirty pages in the cache',
    'cache: pages currently held in the cache',
    'conn: files currently open',
    'log: total log buffer size',
    'LSM: App work units currently queued',
    'LSM: Merge work units currently queued',
    'LSM: Switch work units currently queued',
    'reconciliation: split bytes currently awaiting free',
    'reconciliation: split objects currently awaiting free',
    'session: open cursor count',
    'session: open session count',
    'txn: transaction checkpoint currently running',
    'txn: transaction range of IDs currently pinned',
    'block manager: file allocation unit size',
    'block manager: checkpoint size',
    'block manager: file magic number',
    'block manager: file major version number',
    'block manager: minor version number',
    'block manager: file size in bytes',
    'LSM: bloom filters in the LSM tree',
    'LSM: total size of bloom filters',
    'btree: column-store variable-size deleted values',
    'btree: column-store fixed-size leaf pages',
    'btree: column-store internal pages',
    'btree: column-store variable-size leaf pages',
    'btree: number of key/value pairs',
    'btree: fixed-record size',
    'btree: maximum tree depth',
    'btree: maximum internal page item size',
    'btree: maximum internal page size',
    'btree: maximum leaf page item size',
    'btree: maximum leaf page size',
    'btree: overflow pages',
    'btree: row-store internal pages',
    'btree: row-store leaf pages',
    'cache: overflow values cached in memory',
    'LSM: chunks in the LSM tree',
    'LSM: highest merge generation in the LSM tree',
    'reconciliation: maximum blocks required for a page',
    'session: open cursor count',
]
no_clear_list = [
    'cache: bytes currently in the cache',
    'cache: maximum bytes configured',
    'cache: pages currently held in the cache',
    'conn: files currently open',
    'log: total log buffer size',
    'log: maximum log file size',
    'LSM: App work units currently queued',
    'LSM: Merge work units currently queued',
    'LSM: Switch work units currently queued',
    'reconciliation: split bytes currently awaiting free',
    'reconciliation: split objects currently awaiting free',
    'session: open cursor count',
    'session: open session count',
    'txn: transaction checkpoint currently running',
    'txn: transaction range of IDs currently pinned',
    'session: open cursor count',
]
