# DO NOT EDIT: automatically built by dist/stat.py. */

no_scale_per_second_list = [
    'cache: tracked dirty bytes in the cache',
    'cache: bytes currently in the cache',
    'cache: maximum bytes configured',
    'cache: tracked dirty pages in the cache',
    'cache: pages currently held in the cache',
    'files currently open',
    'log: total log buffer size',
    'open cursor count',
    'transaction checkpoint currently running',
    'block manager: file allocation unit size',
    'block manager: checkpoint size',
    'block manager: file magic number',
    'block manager: file major version number',
    'block manager: minor version number',
    'block manager: file size in bytes',
    'bloom filters in the LSM tree',
    'total size of bloom filters',
    'column-store variable-size deleted values',
    'column-store fixed-size leaf pages',
    'column-store internal pages',
    'column-store variable-size leaf pages',
    'total LSM, table or file object key/value pairs',
    'fixed-record size',
    'maximum tree depth',
    'maximum internal page item size',
    'maximum internal page size',
    'maximum leaf page item size',
    'maximum leaf page size',
    'overflow pages',
    'row-store internal pages',
    'row-store leaf pages',
    'overflow values cached in memory',
    'chunks in the LSM tree',
    'highest merge generation in the LSM tree',
    'reconciliation maximum splits for a page',
    'open cursor count',
]
