# DO NOT EDIT: automatically built by dist/stat.py. */

no_scale_per_second_list = [
    'async: maximum work queue length',
    'cache: tracked dirty bytes in the cache',
    'cache: bytes currently in the cache',
    'cache: maximum bytes configured',
    'cache: tracked dirty pages in the cache',
    'cache: pages currently held in the cache',
    'files currently open',
    'log: total log buffer size',
    'LSM App work units currently queued',
    'LSM Merge work units currently queued',
    'LSM Switch work units currently queued',
    'split bytes currently awaiting free',
    'split objects currently awaiting free',
    'open cursor count',
    'open session count',
    'transaction checkpoint currently running',
    'transaction range of IDs currently pinned',
    'block manager: file allocation unit size',
    'block manager: checkpoint size',
    'block manager: file magic number',
    'block manager: file major version number',
    'block manager: minor version number',
    'block manager: file size in bytes',
    'bloom filters in the LSM tree',
    'total size of bloom filters',
    'column-store variable-size deleted values',
    'column-store fixed-size leaf pages',
    'column-store internal pages',
    'column-store variable-size leaf pages',
    'number of key/value pairs',
    'fixed-record size',
    'maximum tree depth',
    'maximum internal page item size',
    'maximum internal page size',
    'maximum leaf page item size',
    'maximum leaf page size',
    'overflow pages',
    'row-store internal pages',
    'row-store leaf pages',
    'overflow values cached in memory',
    'chunks in the LSM tree',
    'highest merge generation in the LSM tree',
    'reconciliation maximum blocks required for a page',
    'open cursor count',
]
