# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

commands:
    duplicateCommandNew:
        description:
            "duplicate command in new commands fails because a command with the same name
            is in compatibility_test_fail_new.idl"
        command_name: duplicateCommandNew
        namespace: ignored
        cpp_name: duplicateCommandNew
        strict: true
        api_version: "1"
        reply_type: OkReply
