# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"

structs:
    HedgingMode:
        description: The hedging mode for mongos.
        fields:
            enabled:
                cpp_name: enabled
                type: bool
                description: Enable hedged reads.
                default: true
