# Copyright (C) 2023-present MongoDB, Inc.

global:
    cpp_namespace: "mongo"
    configs:
        section: 'OIDC Options'
        source: [ cli ]
    cpp_includes:
        - mongo/client/sasl_oidc_client_params.h

imports:
    - "mongo/db/basic_types.idl"

configs:
    oidcAccessToken:
        description: >-
            If set, the shell will pass this token to the server for any user that tries
            authenticating with the MONGODB-OIDC mechanism. This will bypass the device authorization
            grant flow.
        arg_vartype: String
        cpp_varname: oidcClientGlobalParams.oidcAccessToken

structs:
    OIDCDeviceAuthorizationResponse:
        description: "IdP response from the deviceAuthorization endpoint."
        strict: false
        fields:
            device_code:
                description: "Device code to use in token request"
                cpp_name: deviceCode
                type: string
            verification_uri_complete:
                description: "URI for end user authentication"
                cpp_name: verificationUriComplete
                type: string

    OIDCTokenResponse:
        description: IdP response from the token endpoint.
        strict: false
        fields:
            access_token:
                description: "Access token returned to be sent to the server."
                cpp_name: accessToken
                type: string
                optional: true
            refresh_token:
                description: "Refresh token returned to be used for token reacquisition."
                cpp_name: refreshToken
                type: string
                optional: true
            error:
                description: "Error message returned by the token endpoint."
                type: string
                optional: true
