# -*- mode: python -*-

Import("env")

env = env.Clone()

sdam_json_test = env.Program(
    target="sdam_json_test",
    source=[
        "sdam_json_test_runner.cpp",
    ],
    AIB_COMPONENT="sdam-json-test",
    LIBDEPS=[
        "$BUILD_DIR/mongo/client/connection_string",
        "$BUILD_DIR/mongo/db/concurrency/lock_manager",
        "$BUILD_DIR/mongo/util/clock_source_mock",
        "json_test",
        "sdam",
        "sdam_test_util",
    ],
)[0]

server_selection_json_test = env.Program(
    target="server_selection_json_test",
    source=[
        "server_selection_json_test_runner.cpp",
    ],
    AIB_COMPONENT="server-selection-json-test",
    LIBDEPS=[
        "$BUILD_DIR/mongo/client/connection_string",
        "$BUILD_DIR/mongo/util/clock_source_mock",
        "json_test",
        "sdam",
        "sdam_test_util",
    ],
)[0]

env.Library(
    target="json_test",
    source=[
        "json_test_arg_parser.cpp",
        "json_test_runner_cli_options_gen.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "$BUILD_DIR/mongo/util/options_parser/options_parser",
        "sdam",
    ],
)

env.Library(
    target="sdam_test_util",
    source=[
        "mock_topology_manager.cpp",
        "server_description_builder.cpp",
        "topology_description_builder.cpp",
        "topology_listener_mock.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        "sdam",
    ],
)

env.CppUnitTest(
    target="sdam_test",
    source=[
        "election_id_set_version_pair_test.cpp",
        "server_description_test.cpp",
        "server_selector_test.cpp",
        "topology_description_test.cpp",
        "topology_listener_test.cpp",
        "topology_manager_test.cpp",
        "topology_state_machine_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/client/clientdriver_network",
        "$BUILD_DIR/mongo/client/replica_set_monitor_protocol_test_util",
        "$BUILD_DIR/mongo/db/concurrency/lock_manager",
        "$BUILD_DIR/mongo/executor/thread_pool_task_executor_test_fixture",
        "sdam",
        "sdam_test_util",
    ],
)
