# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: mongo::sdam
    cpp_includes:
        - "mongo/db/server_options.h"

server_parameters:
    heartBeatFrequencyMs:
        description: >-
            For the 'sdam' replicaSetMonitorProtocol, determines how long to wait between
            'hello' requests. For the 'streamable' replicaSetMonitorProtocol, duration between rtt
            measurements.
        set_at: startup
        cpp_vartype: int
        cpp_varname: sdamHeartBeatFrequencyMs
        validator:
            gte: 500
        default: 10000
        redact: false
    localThresholdMs:
        description: Determines the width of the latency window used in server selection.
        set_at: startup
        cpp_varname: "mongo::serverGlobalParams.defaultLocalThresholdMillis"
        validator:
            gte: 0
        default: 15
        redact: false
    overloadAwareServerSelectionEnabled:
        description: >-
            Controls whether server selection will avoid selecting servers suspected to be overloaded when performing retries.
        set_at: [startup, runtime]
        cpp_vartype: "Atomic<bool>"
        cpp_varname: gOverloadAwareServerSelectionEnabled
        default: false
        redact: false
    connectTimeoutMs:
        description: Determines the connection timeout used in the replica set monitor.
        set_at: startup
        cpp_vartype: int
        cpp_varname: sdamConnectTimeoutMs
        validator:
            gte: 500
        default: 10000
        redact: false
