# Copyright (C) 2026-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as published by MongoDB, Inc.

# Feature flag for TLS connection handoff.

global:
    cpp_namespace: "mongo::feature_flags"

imports:
    - "mongo/db/basic_types.idl"

feature_flags:
    featureFlagTLSConnectionHandoff:
        description: "Enable the TLS connection handoff transport layer (HandoffTransportLayer)"
        cpp_varname: gFeatureFlagTLSConnectionHandoff
        default: false
        fcv_gated: false
