# This file defines the format of documents stored in config.replica_set_writes_critical_sections.
# Each document is used to represent that the block on writes is enabled, for a particular collection or
# globally.

global:
    mod_visibility: private
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/topology/user_write_block/replica_set_writes_block_reason.idl"

structs:
    ReplicaSetWriteBlockingCriticalSectionDocument:
        description: "Represents an ongoing block of replica set writes critical section."
        generate_comparison_operators: false
        strict: false
        fields:
            _id:
                type: namespacestring
                description:
                    "The namespace of the collection that is under the collection critical
                    section. Empty namespacestring indicates global prevent writes to all collections."
                cpp_name: nss
            enabled:
                type: bool
                default: false
            allowDeletions:
                type: bool
                default: false
            replicaSetWritesBlockReason:
                type: replicaSetWritesBlockReason
                default: kInsufficientDiskSpace
