# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    mod_visibility: needs_replacement

imports:
    - "mongo/db/global_catalog/ddl/configsvr_coordinator.idl"
    - "mongo/db/basic_types.idl"
    - "mongo/db/global_catalog/ddl/sharded_ddl_commands.idl"

enums:
    SetUserWriteBlockModeCoordinatorPhase:
        description: "Current SetUserWriteBlockMode coordinator phase"
        type: string
        values:
            kUnset: "unset"
            # When enabling user write blocking, kPrepare will instruct the shards to start blocking
            # new sharded DDL operations. When disabling user write blocking, kPrepare will instruct
            # the shards to start accepting user writes again.
            kPrepare: "prepare"
            # When enabling user write blocking, kComplete will instruct the shards to start
            # blocking user writes. When disabling user write blocking, kComplete will instruct the
            # shards to start accepting sharded DDL operations again.
            kComplete: "complete"

structs:
    SetUserWriteBlockModeCoordinatorDocument:
        description: ""
        generate_comparison_operators: false
        strict: false
        chained_structs:
            ConfigsvrCoordinatorMetadata: ConfigsvrCoordinatorMetadata
        fields:
            block: bool
            phase:
                type: SetUserWriteBlockModeCoordinatorPhase
                description: "Coordinator phase."
                default: kUnset
