# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="ingress_admission_control_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="throughput_probing_test",
    source=[],
    LIBDEPS=[],
)
