# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="util_concurrency_test",
    source=[],
    LIBDEPS=[],
    PROVE_ALIASES=["server-programmability"],
)

env.CppUnitTest(target="ticketholder_test", source=[])

env.Benchmark(
    target="ticketholder_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="second_half_bm",
)

env.Benchmark(
    target="lock_free_read_list_bm",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="lock_free_read_list_test",
    source=[],
    LIBDEPS=[],
    PROVE_ALIASES=["server-programmability"],
)
