# -*- mode: python -*-

Import("env")

env.StaticLibrary('thread_name',
                  ['thread_name.cpp'],
                  LIBDEPS=['$BUILD_DIR/mongo/base/base',
                           '$BUILD_DIR/third_party/shim_boost'])
