Import("env")

env = env.Clone()

sorterEnv = env.Clone()
sorterEnv.InjectThirdParty(libraries=['snappy'])

sorterEnv.CppUnitTest(
    target='db_sorter_test',
    source=[
        'sorter_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/service_context',
        '$BUILD_DIR/mongo/db/service_context_test_fixture',
        '$BUILD_DIR/mongo/db/storage/encryption_hooks',
        '$BUILD_DIR/mongo/db/storage/storage_options',
        '$BUILD_DIR/mongo/s/is_mongos',
        '$BUILD_DIR/third_party/shim_snappy',
        'sorter_idl',
    ],
)

env.Library(
    target='sorter_idl',
    source=[
        env.Idlc('sorter.idl')[0],
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/base",
        '$BUILD_DIR/mongo/idl/idl_parser',
    ]
)
