# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/util/buildinfo.idl"

enums:
    BuildInfoAuthMode:
        description: Acceptable values for the buildInfoAuthMode server parameter.
        type: string
        values:
            kRequiresAuth: "requiresAuth"
            kVersionOnlyIfPreAuth: "versionOnlyIfPreAuth"
            kAllowedPreAuth: "allowedPreAuth"

server_parameters:
    buildInfoAuthMode:
        description: "Control the level of authorization required to run the buildInfo command"
        set_at: [startup, runtime]
        cpp_class: BuildInfoAuthModeServerParameter
        redact: false

commands:
    buildInfo:
        description: "Return information about the current build environment"
        namespace: ignored
        api_version: ""
        command_name: buildInfo
        command_alias: buildinfo
        cpp_name: BuildInfoCommand
        reply_type: BuildInfo
