# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0
global:
    mod_visibility: private
    cpp_namespace: "mongo"

imports:
    - "mongo/db/auth/auth_types.idl"
    - "mongo/db/auth/parsed_privilege.idl"
    - "mongo/db/basic_types.idl"

structs:
    ConnectionStatusReplyAuthInfo:
        description: "Currently authenticated users and roles, and optional privileges"
        fields:
            authenticatedUsers:
                description: "Currently authenticated users"
                type: array<UserName>
            authenticatedUserRoles:
                description: "Currently held roles for authenticated users"
                type: array<RoleName>
            authenticatedUserPrivileges:
                description: "Currently authorized privileges across granted roles"
                type: array<ParsedPrivilege>
                optional: true

    ConnectionStatusReply:
        description: "Reply to connectionStatus command"
        is_command_reply: true
        fields:
            authInfo:
                description: "Authenticated users and roles"
                type: ConnectionStatusReplyAuthInfo
            uuid:
                description: "UUID of the current client"
                type: uuid

commands:
    connectionStatus:
        description: "Returns information about the current connection"
        api_version: ""
        command_name: connectionStatus
        namespace: ignored
        cpp_name: ConnectionStatusCommand
        reply_type: ConnectionStatusReply
        fields:
            showPrivileges:
                description: "Return detailed privileges"
                type: safeBool
                default: false
