# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"
    mod_visibility: public

server_parameters:
    featureCompatibilityVersion:
        description: "Read-only view of current Feature Compatability Version"
        set_at: "readonly"
        cpp_class:
            name: FeatureCompatibilityVersionParameter
        redact: false

    internalValidateFeaturesAsPrimary:
        deprecated_name: "internalValidateFeaturesAsMaster"
        description: >
            Startup parameter to ignore featureCompatibilityVersion checks. This parameter cannot be set if
            the node is started with --replSet. This should never be set by end users.
        set_at: startup
        cpp_vartype: bool
        cpp_varname: gInternalValidateFeaturesAsPrimary
        default: true
        redact: false

    defaultStartupFCV:
        description: "Startup parameter to set a default FCV at startup"
        set_at: [startup, runtime]
        cpp_vartype: synchronized_value<std::string>
        cpp_varname: gDefaultStartupFCV
        redact: false
