# Copyright (C) 2017 MongoDB Inc.
#
# This program is free software: you can redistribute it and/or  modify
# it under the terms of the GNU Affero General Public License, version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This IDL file describes the BSON format for a LogicalSessionId, and
# handles the serialization to and deserialization from its BSON representation
# for that class.

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/idl/basic_types.idl"

structs:

    FindAndModifyLastError:
        description: "Contains execution details for the findAndModify command"
        strict: true
        fields:
            updatedExisting:
                description: "Specifies whether the command modified an existing document"
                type: bool
                optional: true
            n:
                description: "Specifies the number of documents that were inserted/deleted or
                              matched the update predicate"
                type: safeInt64

    FindAndModifyResult:
        description: "Contains the result from a findAndModify command"
        strict: false
        fields:
            lastErrorObject:
                type: FindAndModifyLastError
            value:
                description: "Contains document before or after the write depending on the 'new'
                              field of the request was set to true or false"
                type: object
