# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/crypto/fle_field_schema.idl"
    - "mongo/crypto/fle_stats.idl"

structs:
    CompactStructuredEncryptionDataCommandReply:
        description: "Reply from the {compactStructuredEncryptionData: ...} command"
        strict: true
        mod_visibility: private
        is_command_reply: true
        fields:
            stats: CompactStats

commands:
    compactStructuredEncryptionData:
        description: "Parser for the 'compactStructuredEncryptionData' command"
        command_name: compactStructuredEncryptionData
        api_version: ""
        namespace: concatenate_with_db
        strict: true
        mod_visibility: public
        reply_type: CompactStructuredEncryptionDataCommandReply
        fields:
            compactionTokens:
                description: |-
                    Map of field path to ECOCToken.
                    Dictionary key/value pairs in the form: { fieldName: "ecocToken" }
                    or { fieldName: { ecoc: "ecocToken", anchorPaddingToken: "anchorPaddingToken" } }
                type: object
            anchorPaddingFactor:
                description: |-
                    Controls number of padding anchors inserted during compaction.
                    Percentage between 0.0 and 1.0 which is multiplied against the number of
                    anchors being compacted in a single compaction for a given
                    field/value/contention factor for range fields.
                type: double
                optional: true
                validator:
                    gte: 0.0
                    lte: 1.0
            encryptionInformation:
                description: The encryptedField schema for the collection.
                type: EncryptionInformation
                optional: true
