# -*- mode: python -*-

Import("env")

env.Library(
    target='server_status_core',
    source=[
        'server_status_internal.cpp',
        'server_status_metric.cpp',
        ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/bson/bson'
        ]
    )

env.CppUnitTest(
    target="index_filter_commands_test",
    source=[
        "index_filter_commands_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/coredb",
        "$BUILD_DIR/mongo/coreserver",
        "$BUILD_DIR/mongo/serveronly",
        "$BUILD_DIR/mongo/util/ntservice_mock",
    ],
    NO_CRUTCH = True,
)

env.CppUnitTest(
    target="mr_test",
    source=[
        "mr_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/coredb",
        "$BUILD_DIR/mongo/coreserver",
        "$BUILD_DIR/mongo/serveronly",
        "$BUILD_DIR/mongo/util/ntservice_mock",
    ],
    NO_CRUTCH = True,
)

env.CppUnitTest(
    target="plan_cache_commands_test",
    source=[
        "plan_cache_commands_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/coredb",
        "$BUILD_DIR/mongo/coreserver",
        "$BUILD_DIR/mongo/serveronly",
        "$BUILD_DIR/mongo/util/ntservice_mock",
    ],
    NO_CRUTCH = True,
)
