# Copyright (C) 2024-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/views/resolved_view.h"

imports:
    - "mongo/db/basic_types.idl"

types:
    resolved_view:
        description:
            "custom IDL type that wraps the cpp_type ResolvedView, used by ShardsvrResolveViewReply.
            The custom serialize and deserialize methods instruct IDL how to covert to/from C++ and BSON.  "
        bson_serialization_type: any
        cpp_type: "mongo::ResolvedView"
        serializer: "mongo::ResolvedView::serializeToBSON"
        deserializer: "mongo::ResolvedView::parseFromBSON"

structs:
    ShardsvrResolveViewReply:
        description: "The response that the primary shard returns to mongos upon receiving a shardsvrResolveView command"
        fields:
            collectionUUID:
                type: uuid
                optional: true
            resolvedView:
                type: resolved_view
                optional: true

commands:
    _shardsvrResolveView:
        command_name: _shardsvrResolveView
        cpp_name: ShardsvrResolveView
        description:
            "Mongos issues this command on the primary shard to resolve the view for search index commands,
            which require the view's name and effectivePipeline included in the request"
        namespace: ignored
        api_version: ""
        strict: true
        reply_type: ShardsvrResolveViewReply
        fields:
            nss:
                description: "current operation namespace"
                type: namespacestring
                optional: false
