# Copyright (C) 2024-present MongoDB, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the Server Side Public License, version 1,
# as published by MongoDB, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Server Side Public License for more details.
#
# You should have received a copy of the Server Side Public License
# along with this program. If not, see
# <http://www.mongodb.com/licensing/server-side-public-license>.
#
# As a special exception, the copyright holders give permission to link the
# code of portions of this program with the OpenSSL library under certain
# conditions as described in each individual source file and distribute
# linked combinations including the program with the OpenSSL library. You
# must comply with the Server Side Public License in all respects for
# all of the code used other than as permitted herein. If you modify file(s)
# with this exception, you may extend this exception to your version of the
# file(s), but you are not obligated to do so. If you do not wish to do so,
# delete this exception statement from your version. If you delete this
# exception statement from all source files in the program, then also delete
# it in the license file.
#

global:
    cpp_namespace: "mongo"

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/query/search/search_query_view_spec.idl"

structs:
    MongotCursorResponse:
        description: "This response from the cursor opened on mongot for a given search index command"
        fields:
            id:
                type: int
                optional: false
            ns:
                type: namespacestring
                optional: false
            firstBatch:
                description: "array of BSONObjs where each element conveys the information of a single search index on mongot"
                type: array<object_owned>
                optional: false
    SearchIndexManagerResponse:
        description: >-
            The SearchIndexManager's response from running the search index command specified 
            in shardsvrRunSearchIndexCommand.userCmd.
        fields:
            ok:
                description: "Result of the command execution."
                type: safeDouble
                validator: {gte: 0.0, lte: 1.0}
                optional: false
            cursor:
                description: "Mongot responds with this field only for $listSearchIndexes"
                type: MongotCursorResponse
                optional: true
            indexesCreated:
                description: >-
                    Mongot responds with this field only for createSearchindexes command.
                type: array<object_owned>
                optional: true
    ShardsvrRunSearchIndexCommandReply:
        description: "The response that the shard returns to mongos upon receiving a response from the search index manager"
        is_command_reply: true
        fields:
            searchIndexManagerResponse:
                type: SearchIndexManagerResponse
                optional: true
            ok:
                description: "Result of the command execution."
                type: safeDouble
                validator: {gte: 0.0, lte: 1.0}
                optional: false

commands:
    shardsvrRunSearchIndexCommand:
        command_name: _shardsvrRunSearchIndexCommand
        cpp_name: ShardsvrRunSearchIndex
        description: >-
            This test-only command is used by mongos to replicate a search index command on all 
            shards so they may forward said command to their coupled mongot. This is only required
            for testing search index commands. Please see src/mongo/db/query/search/search_index_command_testing_helper.h 
            for more details.
        namespace: ignored
        api_version: ""
        strict: true
        reply_type: ShardsvrRunSearchIndexCommandReply
        fields:
            resolvedNss:
                description: "collection name value."
                type: namespacestring
                optional: false
            userCmd:
                description: "The original user search index command request."
                type: object
                optional: false
            view:
                description: >-
                    If the search index command is being run on a sharded view, mongos will use this field to forward the view 
                    information required to issue an index command on mongot
                type: SearchQueryViewSpec
                optional: true
            mongotAlreadyInformed:
                description: >-
                    This string represents the host and port connection string running a mongot 
                    that was originally issued the index command. When replicating this command 
                    on other mongots, we don't want to repeat on this mongot.
                type: string
                optional: false
