# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0
global:
    cpp_namespace: "mongo"
    mod_visibility: public

imports:
    - "mongo/db/basic_types.idl"
    - "mongo/db/sharding_environment/sharding_types.idl"

structs:
    AdditionalParticipantInfo:
        description:
            "Contains information about a participant added to the transaction by
            another participant"
        strict: false
        fields:
            shardId:
                description: "The name of the shard that was added as a participant"
                type: shard_id
            readOnly:
                description:
                    "True if the shard has the transaction in progress but has not done a
                    write for it"
                optional: true
                type: bool
            term:
                description:
                    "Replication term observed for the participant when the sub-router
                    contacted it."
                optional: true
                type: long

    TxnResponseMetadata:
        description:
            "Contains fields a participant attaches in responses to successful transaction
            statements"
        strict: false
        fields:
            readOnly:
                description:
                    "True if the shard has the transaction in progress but has not done a
                    write for it"
                optional: true
                type: bool
            additionalParticipants:
                description: "Additional participants in the transaction"
                optional: true
                type: array<AdditionalParticipantInfo>
    TxnRecoveryToken:
        description: "Contains info for retrying the commit of a sharded transaction"
        fields:
            recoveryShardId:
                description: "The id of the shard that can make progress committing the transaction"
                type: shard_id
                optional: true
                stability: stable

    EndOfTransactionScopesInfo:
        description: >-
            Currently not used, but declared here for forward-compatibility with proposed
            changes in an upcoming update adding change stream endOfTransaction (EOT) support.
        strict: false

    CommitTransactionOplogObject:
        description: A document representing the 'o' field of a 'commitTransaction' oplog entry.
        fields:
            commitTransaction:
                type: int
                default: 1
            commitTimestamp:
                type: timestamp
                optional: true
                description:
                    "Specifies the timestamp at which the multi-document transaction should
                    be committed.  Required for prepared transactions, not permitted for
                    unprepared ones."
            count:
                type: long
                optional: true
                description:
                    "The number of in-transaction operations applied in a transaction.
                    This field is required only for unprepared transactions."
            endOfTransactionScopes:
                type: EndOfTransactionScopesInfo
                optional: true
                description:
                    "Currently not used, but declared here for forward-compatibility with proposed
                    changes in an upcoming update adding change stream endOfTransaction (EOT) support."

    AbortTransactionOplogObject:
        description: A document representing the 'o' field of an 'abortTransaction' oplog entry.
        fields:
            abortTransaction:
                type: int
                default: 1

commands:
    commitTransaction:
        description: "commitTransaction Command"
        command_name: commitTransaction
        namespace: ignored
        cpp_name: CommitTransaction
        strict: true
        api_version: "1"
        access_check:
            none: true
        fields:
            commitTimestamp:
                description:
                    "Timestamp at which to commit the transaction. Required for prepared
                    transactions and illegal for non-prepared ones."
                optional: true
                type: timestamp
                stability: stable
            recoveryToken:
                description:
                    "A mongos that doesn't know about this transaction can attempt to make
                    progress on commit by processing using the info in the recoveryToken."
                optional: true
                type: TxnRecoveryToken
                stability: stable
        reply_type: OkReply

    abortTransaction:
        description: "abortTransaction Command"
        command_name: abortTransaction
        namespace: ignored
        cpp_name: AbortTransaction
        strict: true
        api_version: "1"
        access_check:
            none: true
        fields:
            recoveryToken:
                description:
                    "A mongos that doesn't know about this transaction can attempt to make
                    progress on abort by processing using the info in the recoveryToken."
                optional: true
                type: TxnRecoveryToken
                stability: stable
        reply_type: OkReply
