# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library('cmdline_utils', ['censor_cmdline.cpp'],
                              LIBDEPS=['$BUILD_DIR/bongo/base'])

env.CppUnitTest('censor_cmdline_test',
                'censor_cmdline_test.cpp',
                LIBDEPS=['cmdline_utils', '$BUILD_DIR/bongo/unittest/unittest'])
