package(default_visibility = ["//visibility:public"])

load(":mongo_linux_cross_toolchain_test.bzl", "mongo_linux_cross_toolchain_test_suite")

exports_files([
    "mongo_linux_cross_toolchain.bzl",
    "mongo_linux_cross_toolchain_flags_v5.bzl",
])

mongo_linux_cross_toolchain_test_suite(name = "mongo_linux_cross_toolchain_test")
