# -*- mode: python -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target="db_ops_test",
    source=[],
    LIBDEPS=[],
)

env.CppIntegrationTest(
    target="db_ops_integration_test",
    source=[],
    LIBDEPS=[],
)
