// Copyright (c) MongoDB, Inc.
// SPDX-License-Identifier: SSPL-1.0

#pragma once

#include "mongo/bson/bsonmisc.h"
#include "mongo/bson/bsonobj.h"
#include "mongo/bson/bsonobjbuilder.h"
#include "mongo/db/operation_context.h"
#include "mongo/db/query/write_ops/single_write_result_gen.h"
#include "mongo/db/query/write_ops/write_ops.h"
#include "mongo/db/query/write_ops/write_ops_gen.h"
#include "mongo/db/repl/oplog_entry.h"
#include "mongo/db/repl/oplog_entry_gen.h"
#include "mongo/util/modules.h"

namespace mongo {

class BSONObjBuilder;
class OperationContext;

[[MONGO_MOD_PUBLIC]] const BSONObj kWouldChangeOwningShardSentinel(BSON("$wouldChangeOwningShard"
                                                                        << 1));

template <typename OplogEntryType>
[[MONGO_MOD_PUBLIC]] bool isWouldChangeOwningShardSentinelOplogEntry(
    const OplogEntryType& oplogEntry) {
    return (oplogEntry.getOpType() == repl::OpTypeEnum::kNoop) &&
        (oplogEntry.getObject().woCompare(kWouldChangeOwningShardSentinel) == 0) &&
        oplogEntry.getObject2() && oplogEntry.getObject2()->isEmpty();
}

/**
 * Returns the single write result corresponding to the given oplog entry for document update. I.e.,
 * the single write result that would have been returned by the statement that would have resulted
 * in the given oplog entry. The oplog entries are assumed to be properly formed and have the
 * correct op type.
 * Uses the 'upsertedId' for an upsert operation if it's provided.
 */
SingleWriteResult parseOplogEntryForUpdate(
    const repl::OplogEntry& entry, const boost::optional<BSONElement>& upsertedId = boost::none);

/**
 * Returns the response for a findAndModify request based on the oplog entries generated by
 * the operation.
 */
write_ops::FindAndModifyCommandReply parseOplogEntryForFindAndModify(
    OperationContext* opCtx,
    const write_ops::FindAndModifyCommandRequest& request,
    const repl::OplogEntry& oplogEntry);

}  // namespace mongo
