# -*- mode: python -*-
Import("env")

env = env.Clone()

env.Library(
    target="idl_parser",
    source=[
        'idl_parser.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ]
)

env.CppUnitTest(
    target='idl_test',
    source=[
        'idl_test.cpp',
        env.Idlc('unittest_import.idl')[0],
        env.Idlc('unittest.idl')[0],
	],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/namespace_string',
        '$BUILD_DIR/mongo/idl/idl_parser',
        '$BUILD_DIR/mongo/util/uuid',
    ],
)
