#    Copyright (C) 2018-present MongoDB, Inc.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the Server Side Public License, version 1,
#    as published by MongoDB, Inc.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
#    Server Side Public License for more details.
#
#    You should have received a copy of the Server Side Public License
#    along with this program. If not, see 
#    <http://www.mongodb.com/licensing/server-side-public-license>.
#
#    As a special exception, the copyright holders give permission to link the 
#    code of portions of this program with the OpenSSL library under certain
#    conditions as described in each individual source file and distribute
#    linked combinations including the program with the OpenSSL library. You 
#    must comply with the Server Side Public License in all respects for 
#    all of the code used other than as permitted herein. If you modify file(s)
#    with this exception, you may extend this exception to your version of the 
#    file(s), but you are not obligated to do so. If you do not wish to do so, 
#    delete this exception statement from your version. If you delete this
#    exception statement from all source files in the program, then also delete
#    it in the license file.
#

global:
    cpp_namespace: "mongo::test"
    cpp_includes:
    - "mongo/idl/server_parameter_specialized_test.h"
    - "mongo/platform/atomic_word.h"

server_parameters:
    specializedDummy:
        description: "Specialized server parameter with dummy value."
        set_at: [ startup, runtime ]
        cpp_class: SpecializedDummyServerParameter
    specializedWithCtor:
        description: "Provide a custom constructor implementation."
        set_at: startup
        cpp_class:
            name: SpecializedConstructorServerParameter
            override_ctor: true
    specializedWithValue:
        description: "Attach a simple value."
        set_at: startup
        cpp_class:
            name: SpecializedWithValueServerParameter
            data: std::int32_t
        default: 43
    specializedWithStringValue:
        description: "Attach a string."
        set_at: startup
        cpp_class:
            name: SpecializedWithStringValueServerParameter
            data: std::string
        default: 'Hello World'
    specializedWithAtomicValue:
        description: "Attach a thread safe value."
        set_at: [ startup, runtime ]
        cpp_class:
            name: SpecializedWithAtomicValueServerParameter
            data: AtomicWord<std::int32_t>
        default: 42
    specializedWithMultiValue:
        description: "Attach a struct."
        set_at: startup
        cpp_class:
            name: SpecializedMultiValueServerParameter
            data: ExtraDataForServerParameter
            override_set: true
    specializedWithCtorAndValue:
        description: "Attach a simple value and a constum constructor."
        set_at: startup
        cpp_class:
            name: SpecializedWithCtorAndValueServerParameter
            data: std::int32_t
            override_ctor: true
        default: 44
    specializedWithOptions:
        description: "Use optional attributes."
        set_at: startup
        cpp_class: SpecializedWithOptions
        redact: true
        test_only: false
        condition: { expr: true }
        deprecated_name: deprecatedWithOptions
