# -*- mode: python -*-

Import("env")

env.CppUnitTest(
    target="db_sbe_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="abt_unit_test_infra_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="sbe_abt_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="makeobj_spec_hash_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="abt_lower_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="abt_lower_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="first_half_bm",
)

env.Benchmark(
    target="sbe_vm_bm",
    source=[],
    LIBDEPS=[],
    BAZEL_BENCHMARK_TAG="first_half_bm",
)

env.Benchmark(
    target="sbe_expression_bm",
    source=[],
    LIBDEPS=[],
)
