# -*- mode: python -*-

Import("env")

env.CppUnitTest(
    target="db_sbe_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="abt_unit_test_infra_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="sbe_abt_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="makeobj_spec_hash_test",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="abt_lower_test",
    source=[],
    LIBDEPS=[],
)

env.Benchmark(
    target="abt_lower_bm",
    source=[
        "abt/abt_lower_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/unittest/unittest",
        "abt_unit_test_utils",
        "query_sbe_abt",
    ],
)

env.Benchmark(
    target="sbe_vm_bm",
    source=[
        "vm/vm_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/collation/collator_icu",
        "$BUILD_DIR/mongo/unittest/unittest",
        "query_sbe",
    ],
    CONSOLIDATED_TARGET="first_half_bm",
)

env.Benchmark(
    target="sbe_expression_bm",
    source=[
        "expressions/sbe_expression_bm.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/db/pipeline/expression_bm_fixture",
        "$BUILD_DIR/mongo/db/query/query_test_service_context",
        "$BUILD_DIR/mongo/db/query_exec",
        "$BUILD_DIR/mongo/db/service_context_non_d",
        "query_sbe_stages",
    ],
)
