# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target="histogram_helpers",
    source=[
        "scalar_histogram_helpers.cpp",
        "array_histogram_helpers.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/ce/ce_utils",
        "$BUILD_DIR/mongo/db/query/query_index_bounds",
        "$BUILD_DIR/mongo/db/query/stats/stats_histograms",
    ],
)

env.Library(
    target="cbp_ce_test_helpers",
    source=[
        "test_helpers.cpp",
        "accuracy_test_helpers.cpp",
        "histogram_predicate_estimation.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/ce/test_utils",
        "$BUILD_DIR/mongo/db/query/stats/stats_test_utils",
        "histogram_helpers",
    ],
)

env.CppUnitTest(
    target="cbp_histogram_estimation_test",
    source=[
        "histogram_predicate_estimation_test.cpp",
        "scalar_histogram_helpers_test.cpp",
        "array_histogram_helpers_test.cpp",
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/ce/test_utils",
        "$BUILD_DIR/mongo/db/query/stats/stats_test_utils",
        "cbp_ce_test_helpers",
        "histogram_helpers",
    ],
)

env.Benchmark(
    target="cbp_histogram_bm",
    source=["array_histogram_bm.cpp"],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/ce/test_utils",
        "$BUILD_DIR/mongo/db/query/query_test_service_context",
        "$BUILD_DIR/mongo/db/query/stats/stats_test_utils",
        "cbp_ce_test_helpers",
    ],
)

env.Program(
    target="cbp_histogram_estimation_accuracy_test",
    source=["histogram_accuracy_test.cpp"],
    LIBDEPS=[
        "$BUILD_DIR/mongo/db/query/ce/test_utils",
        "$BUILD_DIR/mongo/db/query/stats/stats_test_utils",
        "cbp_ce_test_helpers",
        "histogram_helpers",
    ],
)
