# Copyright (c) MongoDB, Inc.
# SPDX-License-Identifier: SSPL-1.0

# TODO (SERVER-96853): This IDL file is a temporary location for parameters related to
# execution control heuristics. These parameters should be moved to execution_control_parameters.idl
# once the cycle dependency of execution_admission_context is fixed.
global:
    cpp_namespace: "mongo::admission::execution_control"

server_parameters:
    executionControlHeuristicNumAdmissionsDeprioritizeThreshold:
        description: >-
            The number of admissions an operation must perform before it is deprioritized to the low-priority
            ticket pool. This parameter only takes effect when `executionControlHeuristicDeprioritization`
            is true.
        set_at: [startup, runtime]
        cpp_vartype: Atomic<int>
        cpp_varname: gHeuristicNumAdmissionsDeprioritizeThreshold
        default: 3
        validator:
            gte: 0
        redact: false
